Blogpost zu ArchUnit
adessoAG/devblog pull request #165
Opened 2020-08-17 19:34 UTC by klausSchnaithmann

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-08-19 14:31 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Nicht so, wie es aussehen sollte.
Bitte formuliere diese Stelle zu einem ganzen Satz um oder verbinde sie mit dem vorherigen Satz zu einem ganzen Satz.

2020-08-19 14:32 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Nicht so, wie es beim Aufsetzen des Projektes die Architektur noch vorgesehen hatte.
Bitte formuliere diese Stelle zu einem ganzen Satz um oder verbinde sie mit dem vorherigen Satz zu einem ganzen Satz.

2020-08-19 14:32 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Dann verfestigen sie sich durch weiteren Code, der auf diese aufbaut.
```suggestion
Dann verfestigen sie sich durch weiteren Code, der auf diesen Abweichungen aufbaut.
```

2020-08-19 14:32 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +So natürlich, wie über Unit Tests sicherzustellen, dass ein Modul funktioniert:
Bitte formuliere diese Stelle zu einem ganzen Satz um oder verbinde sie mit dem vorherigen Satz zu einem ganzen Satz.

2020-08-19 14:33 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Dieses Beispiel zeigt denke ich, wie einfach die Library Schicht zu verwenden ist.
```suggestion
Dieses Beispiel zeigt, wie einfach die Library Schicht zu verwenden ist. 
```

2020-08-19 14:33 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Neben der Prüfung auf Schichten Architekturen bietet die Library Schicht noch viele weitere Möglichkeiten wie Prüfungen für Hexagonale Architekturen oder auch generelle Programmierrichtlinien.
```suggestion
Neben der Prüfung auf Schichten Architekturen bietet die Library API noch viele weitere Möglichkeiten wie Prüfungen für Hexagonale Architekturen oder auch generelle Programmierrichtlinien. 
```

2020-08-19 14:33 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Wie angekündigt sind die Regeln der Language API selbsterklärend, aufgrund der sprechenden Benennung – die Möglichkeiten aber dennoch sehr vielseitig.
```suggestion
Wie angekündigt sind die Regeln der Language API aufgrund der sprechenden Benennung selbsterklärend – die Möglichkeiten sind aber dennoch sehr vielseitig. 
```

2020-08-19 14:34 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Beim selbst Erstellen einer eigenen Prüfung können wir daher bei der Einschränkung oder der Bedingung ansetzen.
```suggestion
Beim Erstellen einer eigenen Prüfung können wir daher bei der Einschränkung oder der Bedingung ansetzen. 
```

2020-08-19 14:34 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Diese verwendet zu einem großen Teil Konzepte, wie wir sie von der Java Reflection API kennen, erweitert diese aber, um die Beziehungen zwischen Code besser darstellen zu können.
```suggestion
Diese verwendet zu einem großen Teil Konzepte, wie wir sie von der Java Reflection API kennen, erweitert diese aber, um die Beziehungen zwischen Code-Teilen besser darstellen zu können. 
```

2020-08-19 14:34 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Vielleicht zum Beispiel spezielle Annotationen für Prozesse und Services – eine Überprüfung hierauf wäre aber nicht komplizierter als die Prüfung auf den Klassennamen.
```suggestion
Vielleicht existieren spezielle Annotationen für Prozesse und Services – eine Überprüfung hierauf wäre aber nicht komplizierter als die Prüfung auf den Klassennamen. 
```

2020-08-19 14:35 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Insgesamt haben wir bisher denke ich ein gutes Bild erhalten, wie wir mit wenigen Zeilen Code, die dazu recht sprechend sind, architekturelle Vorgaben sicherstellen können.
```suggestion
Insgesamt haben wir bisher ein gutes Bild erhalten, wie wir mit wenigen Zeilen Code, die dazu recht sprechend sind, architekturelle Vorgaben sicherstellen können.
```

2020-08-19 14:35 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Insbesondere bei größeren Legacy Anwendungen ist ein entsprechendes Refactoring ein zeitaufwendiger Prozess und lässt sich eventuell nur Schrittweise durchführen.
```suggestion
Insbesondere bei größeren Legacy Anwendungen ist ein entsprechendes Refactoring ein zeitaufwendiger Prozess, der sich eventuell nur Schrittweise durchführen lässt. 
```

2020-08-19 14:36 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Um diese zu verwenden müssen wir mit FreezingArchRule.freeze() eine vorhandene ArchRule umfassen:
```suggestion
Um diese zu verwenden müssen wir eine vorhandene ArchRule mit FreezingArchRule.freeze() umfassen:
```

2020-08-19 14:36 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Braucht es die Ausnahme wirklich auch im Branch für das kommende Release?
```suggestion
Braucht es die Ausnahme auch im Branch für das kommende Release?
```

2020-08-19 14:38 UTC, jo2 requested changes
Der Artikel liest sich schon sehr gut. Ein paar Sachen habe ich noch angemerkt. Außerdem:
* verwende bitte " statt „ und “, da es sonst zu Encoding-Probleme kommen kann
* Schreibe Schichtenarchitektur bitte einheitlich (bspw. Z. 71, Z. 126)

2020-09-07 10:30 UTC, klausSchnaithmann commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +So natürlich, wie über Unit Tests sicherzustellen, dass ein Modul funktioniert:
Ich habe die Sätze umformuliert. Bitte prüfe, ob das jetzt so passt.

2020-09-07 10:40 UTC, klausSchnaithmann commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Nicht so, wie es beim Aufsetzen des Projektes die Architektur noch vorgesehen hatte.
Ich habe die Sätze umformuliert. Bitte prüfe, ob das jetzt so passt.

2020-09-07 10:46 UTC, klausSchnaithmann commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Diese verwendet zu einem großen Teil Konzepte, wie wir sie von der Java Reflection API kennen, erweitert diese aber, um die Beziehungen zwischen Code besser darstellen zu können.
Ich habe den Satz geändert. Statt Code in "Code-Teilen" zu ändern, heißt es jetzt "Code-Fragmenten". Bitte prüfe, ob das für dich so passt.

2020-09-07 11:03 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Und das ganze auf eine Weise, die sich für Entwickler völlig natürlich anfühlt, sie zu verwenden.
```suggestion
Und das ganze auf eine Weise, die sich für Entwickler völlig natürlich anfühlt.
```
oder
```suggestion
Und das ganze auf eine Weise, deren Verwendung sich für Entwickler völlig natürlich anfühlt.
```

2020-09-07 11:04 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Dieses Beispiel zeigt, wie einfach die Library Schicht zu verwenden ist.
```suggestion
Dieses Beispiel zeigt, wie einfach die Library API zu verwenden ist. 
```
das habe ich bei der ersten Korrektur leider übersehen

2020-09-07 11:11 UTC, jo2 commented on _posts/2020-08-17-Umsetzung-von-Architekturvorgaben-testen.md
> +Um diese zu verwenden müssen wir eine vorhandene ArchRule mit FreezingArchRule.freeze() umfassen:
```suggestion
Um diese zu verwenden, müssen wir eine vorhandene ArchRule mit FreezingArchRule.freeze() umfassen:
```

2020-09-07 11:15 UTC, jo2 requested changes
Zwei Sachen habe ich noch gefunden, die mir beim ersten Review leider entgangen sind, und an einer Stelle habe ich noch eine Verbesserung angemerkt. Kümmere dich bitte außerdem noch um Folgendes:
* Verwende bitte " statt „ und “, da es sonst zu Encoding-Probleme kommen kann
* Schreibe Schichtenarchitektur bitte einheitlich (bspw. Z. 71, Z. 126)

2020-09-09 09:11 UTC, klausSchnaithmann commented
> Zwei Sachen habe ich noch gefunden, die mir beim ersten Review leider entgangen sind, und an einer Stelle habe ich noch eine Verbesserung angemerkt. Kümmere dich bitte außerdem noch um Folgendes:
> 
> * Verwende bitte " statt „ und “, da es sonst zu Encoding-Probleme kommen kann
> * Schreibe Schichtenarchitektur bitte einheitlich (bspw. Z. 71, Z. 126)

Ich habe die Änderungen eingearbeitet.

2020-09-09 12:29 UTC, jo2 submitted a review, later dismissed

2020-09-28 14:38 UTC, acetous approved these changes

2020-09-28 14:42 UTC, acetous approved these changes

2020-09-28 14:43 UTC, merged