Neuer Blogpost: Mobile Cross Platform Entwicklung
adessoAG/devblog pull request #166
Opened 2020-08-19 09:12 UTC by v1nc33

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [X] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [X] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [X] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [X] "title" vergeben
    - [X] "author" angegeben
    - [X] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [X] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [X] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [X] Rechtschreibung korrigiert
  - [X] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [X] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [X] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [X] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [X] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [X] Rechtschreibung korrigiert
  - [X] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [X] Der Autor ist bei CCO hinterlegt
  - [X] CCO wurde über neuen Artikel informiert
  - [X] Date-Angaben 
    - [X] stimmen im Header und im Dateinamen überein
    - [X] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-08-19 13:04 UTC, jo2 commented on _data/authors.yml
> +  bio: "Vincent Lipschinski arbeitet als Software Engineer bei adesso. Sein Fokus liegt auf den JavaScript-Technologien und entwickelt Anwendungen mit React und Angular."
```suggestion
  bio: "Vincent Lipschinski arbeitet als Software Engineer bei adesso. Sein Fokus liegt auf den JavaScript-Technologien und er entwickelt Anwendungen mit React und Angular."
```

2020-08-19 13:29 UTC, jo2 commented on _posts/2020-08-17-Mobile-Cross-Platform-Entwicklung.md
> +Im Gegensatz zum Paradigma der nativen App-Entwicklung verfolgen die Cross-Platform-Frameworks einen Ansatz, um die App-Entwicklung unabhängig vom Betriebssystem zumachen.
```suggestion
Im Gegensatz zum Paradigma der nativen App-Entwicklung verfolgen die Cross-Platform-Frameworks einen Ansatz, der die App-Entwicklung unabhängig vom Betriebssystem machen soll.
```

2020-08-19 13:29 UTC, jo2 commented on _posts/2020-08-17-Mobile-Cross-Platform-Entwicklung.md
> +Die unterschiedlichen Paradigmen werden im Folgenden im Kontext der unterschiedlichen Frameworks detaillierter erläutert.
```suggestion
Die unterschiedlichen Paradigmen werden im Folgenden im Kontext der unterschiedlichen Frameworks genauer erläutert.
```

2020-08-19 13:29 UTC, jo2 commented on _posts/2020-08-17-Mobile-Cross-Platform-Entwicklung.md
> +Dies ermöglicht es, aus dem JavaScript-Quellcode heraus nativen Quellcode aufzurufen. Cordova bietet dazu eine Auswahl von Core Plugins an wie beispielsweise Batterie Status, Kamera oder Kontakte.
```suggestion
Dies ermöglicht es, aus dem JavaScript-Quellcode heraus nativen Quellcode aufzurufen. Cordova bietet dazu eine Auswahl von Core Plugins an wie beispielsweise Batterie Status, Kamera oder Kontakte an.
```

2020-08-19 13:30 UTC, jo2 commented on _posts/2020-08-17-Mobile-Cross-Platform-Entwicklung.md
> +Diese wurden vom Flutter-Team nachgebaut, um das typische Android- bzw. iOS-Look-and-Feel zu erhalten.
```suggestion
Eine Auswahl von UI-Komponenten wurden vom Flutter-Team nachgebaut, um das typische Android- bzw. iOS-Look-and-Feel zu erhalten.
```

2020-08-19 13:31 UTC, jo2 commented on _posts/2020-08-17-Mobile-Cross-Platform-Entwicklung.md
> +Wer also mit React vertraut ist, für denjenigen/diejenige ist das Entwickeln mit React Native keine große Umstellung, denn das Grundprinzip bei React ist dasselbe, wie bei React Native.
```suggestion
Wer also mit React vertraut ist, für den ist das Entwickeln mit React Native keine große Umstellung, denn das Grundprinzip bei React ist dasselbe, wie bei React Native.
```
Bisher wird nirgendwo im Devblog gegendert, daher musst du nicht gendern, wenn du das nicht möchtest. Wenn du das in deinen Artikeln machen möchtest, solltest du das allerdings konsequent im ganzen Artikel machen.

2020-08-19 13:32 UTC, jo2 commented on _posts/2020-08-17-Mobile-Cross-Platform-Entwicklung.md
> +PWAs haben hingegen den Vorteil, die App nicht installieren zu müssen.
```suggestion
PWAs haben hingegen den Vorteil, dass die Nutzer die App nicht installieren zu müssen.
```

2020-08-19 13:43 UTC, jo2 requested changes
Der Post sieht schon sehr gut aus, ein paar Kleinigkeiten sind mir noch aufgefallen.

2020-08-19 16:29 UTC, jo2 approved these changes

2020-08-19 16:30 UTC, jo2 commented
@acetous Rechtschreibung passt soweit. Machst du noch eine inhaltliche Review?

2020-10-09 07:07 UTC, acetous approved these changes

2020-10-09 07:09 UTC, acetous approved these changes

2020-10-09 07:11 UTC, merged