Phishing Kampagne
adessoAG/devblog pull request #167
Opened 2020-08-21 06:16 UTC by VivienEmily

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ x] "title" vergeben
    - [ x] "author" angegeben
    - [ x] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [ x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [x ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-08-24 15:07 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Handelt das Opfer nicht korrekt, ist der Klick auf den Link oder Anhang das erste notwendige Ereignis des Opfers für einen erfolgreichen Phishing-Betrug.
```suggestion
Handelt das Opfer nicht korrekt, ist der Klick auf den Link oder Anhang die einzige notwendige Aktion des Opfers für einen erfolgreichen Phishing-Betrug. 
```

2020-08-24 15:09 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Von den gemeldeten Sicherheitsvorfällen wurde mehr als die Hälfte durch Malware injiziert, wobei 90 % als Anhang oder Link in einer E-Mail verbreitet wurden.
```suggestion
Von den gemeldeten Sicherheitsvorfällen wurde mehr als die Hälfte durch Malware verursacht, wobei 90 % als Anhang oder Link in einer E-Mail verbreitet wurden. 
```

2020-08-24 15:10 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Einmal mit der Brechstange eine Phishing Simulation durchführen, beschreiben die geplanten zwei Wochen Phishing Simulation recht gut.
```suggestion
"Einmal mit der Brechstange eine Phishing Simulation durchführen" beschreibt die geplante zwei Wochen dauernde Phishing Simulation recht gut.
```

2020-08-24 15:10 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Es war geplant, an jeden der 2495 adessi in Deutschland vier verschiedene Phishing E-Mails zu versenden, so dass insgesamt etwa 9980 E-Mails versendet werden sollten.
```suggestion
Es war geplant, an jeden der 2495 adessi in Deutschland vier verschiedene Phishing E-Mails zu versenden, sodass insgesamt etwa 9980 E-Mails versendet werden sollten. 
```

2020-08-24 15:11 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Die vier E-Mails waren unterteilt in eine CEO-Fraud, eine Kandidatenempfehlung über LinkedIn, eine Anwalts E-Mail bezüglich eines illegalen Datei Downloads und eine E-Mail von einem Voicemail Service
```suggestion
Die vier E-Mails waren unterteilt in eine CEO-Fraud, eine Kandidatenempfehlung über LinkedIn, eine Anwalts-E-Mail bezüglich eines illegalen Datei Downloads und eine E-Mail von einem Voicemail Service. 
```

2020-08-24 15:13 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Sobald jemand dem Link oder dem Anhang in der CEO Fraud, der Anwalts E-Mail oder dem Voicemail Service folgte, wurde er auf eine Online-Schulungsseite von SoSafe weitergeleitet, die zur besseren Iden
```suggestion
Sobald jemand dem Link oder dem Anhang in der CEO Fraud, der Anwalts-E-Mail oder dem Voicemail Service folgte, wurde er auf eine Online-Schulungsseite von SoSafe weitergeleitet, die zur besseren Identifizierung mit dem adesso Firmenlogo versehen wurde. 
```

2020-08-24 15:13 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Bei der LinkedIn E-Mail musste man nicht nur auf den Link klicken, sondern auch in das Passwortfeld der gefälschten Anmeldeseite, um auf die Schulungsseite zu gelangen.
```suggestion
Bei der LinkedIn-E-Mail musste man nicht nur auf den Link klicken, sondern auch in das Passwortfeld der gefälschten Anmeldeseite, um auf die Schulungsseite zu gelangen. 
```

2020-08-24 15:15 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Der Bericht über die Statistiken wurde elf Tage nach dem Ende der Kampagne gezogen. Das bedeutet, dass selbst diejenigen Klickraten noch registriert worden sind, die nach dem Ende der Simulation geöf
```suggestion
Der Bericht über die Statistiken wurde elf Tage nach dem Ende der Kampagne gezogen. Das bedeutet, dass selbst die Klickraten noch registriert worden sind, die nach dem Ende der Simulation geöffnet oder empfangen wurden. 
```

2020-08-24 15:24 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Die Phishing Kampagne umfasste nicht nur die vorbereiteten Phishing E-Mails, sondern auch eine kurze Online Schulung.
```suggestion
Die Phishing Kampagne umfasste nicht nur die vorbereiteten Phishing E-Mails, sondern auch eine kurze Online-Schulung. 
```

2020-08-24 15:28 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +![CEO Fraud](/assets/images/posts/Phishing-Kampagne-2019/CEOFraudKlickraten.png)
```suggestion
![CEO-Fraud](/assets/images/posts/Phishing-Kampagne-2019/CEOFraudKlickraten.png) 
```

2020-08-24 15:33 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Die zweite Umfrage wurde in dem Aufklärungsnewsflash von unserem Vorstand versendet, sodass alle adessi die Möglichkeit hatten ein Feedback zurückzuspielen.
```suggestion
Die zweite Umfrage wurde in dem Aufklärungsnewsflash von unserem Vorstand versendet, sodass alle adessi die Möglichkeit hatten, ein Feedback zurückzuspielen. 
```

2020-08-24 15:33 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Eine solche Schulungsmaßnahme schien mehr Aufmerksamkeit und Gespräche zu erzeugen, als eine übliche (Online) Schulung.
```suggestion
Eine solche Schulungsmaßnahme schien mehr Aufmerksamkeit und Gespräche zu erzeugen, als eine übliche (Online-) Schulung.
```

2020-08-24 15:35 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Wie immer zeigt sich: Je besser die Phishing E-Mails in den Kontext der empfangenden Person passt und je weniger Fehler die Phishing E-Mail aufweist, umso höher ist die Wahrscheinlichkeit, dass die P
```suggestion
Wie immer zeigt sich: Je besser die Phishing-E-Mail in den Kontext der empfangenden Person passt und je weniger Fehler sie aufweist, umso höher ist die Wahrscheinlichkeit, dass die Person auf die E-Mail eingeht und den Betrug nicht bemerkt. 
```

2020-08-24 15:37 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Um einen Schaden zu verhindern und präventiv vorzugehen sind Phishing Simulationen ein hilfreiches Werkzeug.
```suggestion
Um einen Schaden zu verhindern und präventiv vorzugehen, sind Phishing-Simulationen ein hilfreiches Werkzeug. 
```

2020-08-24 15:44 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Doch lasst uns nicht nur auf uns, als Nutzer von E-Mail Programmen schauen, sondern auch auf die Nutzer unserer Software.
Dieser Satz ergibt meiner Meinung nach keinen Sinn: "Last uns nicht auf uns als Nutzer, sondern auch auf die Nutzer [..] schauen." Kannst du das etwas eindeutiger formulieren?

2020-08-24 15:51 UTC, jo2 requested changes
Generell liest sich der Artikel schon sehr gut. Ein paar Änderungen habe ich noch angemerkt. Das meiste davon bezieht sich auf die einheitliche Schreibweise von zusammengesetzten Begriffen. Da habe ich nicht alle stellen angemerkt, achte bitte im gesamten Artikel darauf, dass du zusammengesetzte Begriffe einheitlich schreibst. Mal verwendest du eine Schreibweise mit und mal eine Schreibweise ohne Bindestrich. Beides ist in Ordnung, solange es konsequent durchgezogen wird. 

Außerdem genderst du in deinem Artikel an einigen Stellen. Bisher haben wir im Devblog nicht gegendert, wenn du das nicht machen willst, musst du also auch nicht. Wenn du gendern möchtest, müsstest du im Fazit noch "Nutzer" entsprechend ersetzen.

2020-08-26 06:04 UTC, VivienEmily reviewed
Ich würde es gerne gegendert lassen und noch die eine Stelle anpassen :)

2020-08-26 06:04 UTC, VivienEmily commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Doch lasst uns nicht nur auf uns, als Nutzer von E-Mail Programmen schauen, sondern auch auf die Nutzer unserer Software.
Wie wäre es mit: Bei dieser Maßnahme waren wir, als Nutzer (Plural) von E-Mail Programmen im Fokus. Lasst uns im nächsten Schritt die Nutzer unserer Software in den Fokus nehmen, um auch sie vor Phishing zu schützen.

2020-08-26 06:52 UTC, jo2 commented
Laut https://geschicktgendern.de/ heißt es "Nutzende". Du kannst meiner Meinung nach aber auch User schreiben, das Englische ist an der Stelle Geschlechterneutral.

2020-08-26 06:53 UTC, jo2 commented on _posts/2020-08-19-Phishining_Kampagne_ZDF.md
> +Doch lasst uns nicht nur auf uns, als Nutzer von E-Mail Programmen schauen, sondern auch auf die Nutzer unserer Software.
Klingt gut!

2020-10-19 07:39 UTC, acetous commented
Durch #177 abgelöst.

2020-10-19 07:39 UTC, closed without merging