Cloud native Migration mit der Rearchitecting Strategie
adessoAG/devblog pull request #168
Opened 2020-08-24 14:06 UTC by c-bachmann

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-08-24 14:45 UTC, jo2 commented
@c-bachmann kommen hier noch mehrere Änderungen bevor ein Review stattfinden kann? Wenn ja, markiere den PR bitte als Draft, bis du mit deinen Änderungen durch bist. Ansonsten kann es während der ersten Rechtschreibkorrektur zu Merge-Konflikten kommen.

2020-08-24 14:52 UTC, c-bachmann commented
Es kommen bestimmt noch ein Paar Korrekturen bis morgen. Ich markiere es als Draft.

2020-08-25 06:36 UTC, c-bachmann commented
Es kann jetzt gern gereviewed werden.

2020-08-26 13:27 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +In meinem vorhergehenden Blog-Beitrag habe ich die [Gründe und 6 Strategien für die Migration einer Applikation in die Cloud aufgezeigt](https://www.adesso.de/de/news/blog/gruende-und-strategien-fuer
```suggestion
In meinem vorangegangenen Blog-Beitrag habe ich [Gründe und Strategien für die Migration einer Applikation in die Cloud aufgezeigt](https://www.adesso.de/de/news/blog/gruende-und-strategien-fuer-die-migration-einer-applikation-in-die-cloud.jsp) aufgezeigt.
```
oder 
```suggestion
In meinem vorangegangenen Blog-Beitrag, [Gründe und Strategien für die Migration einer Applikation in die Cloud aufgezeigt](https://www.adesso.de/de/news/blog/gruende-und-strategien-fuer-die-migration-einer-applikation-in-die-cloud.jsp), habe ich die Gründe und 6 Strategien für die Migration in die Cloud aufgezeigt.
```

2020-08-26 13:28 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Die Anwendung wird auf virtuellen Maschinen betrieben oder in einer Container Umgebung wie Kubernetes.
```suggestion
Außerdem wird die Anwendung auf virtuellen Maschinen oder in einer Container Umgebung wie Kubernetes betrieben.
```

2020-08-26 13:28 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Die Rearchitecting Strategie sollte inkrementell und iterativ nach den Grundprinzipien der agilen Softwareentwicklung angewendet werden.
```suggestion
Die Rearchitecting Strategie sollte inkrementell nach den Grundprinzipien der agilen Softwareentwicklung angewendet werden. 
```

2020-08-26 13:28 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Im folgenden Abschnitt erläutere ich die Schritte bei der Anwendung der Rearchitecting Strategie.
```suggestion
Im folgenden Abschnitt erläutere ich die Schritte, aus denen die Rearchitecting Strategie besteht.
```

2020-08-26 13:30 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Bei diesen höherwertigen Diensten liegt das Autoscaling, Scale-to-Zero und das regelmäßige Einspielen von Sicherheitspatches im Verantwortungsbereich des Cloud Anbieters.
Meinst du hier höherwertige Laufzeitumgebungen? Wenn nicht, erläutere bitte, was du hier mit Diensten meinst.

2020-08-26 13:32 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Alle großen Cloud Anbieter bieten dafür eine Container Registry als Service an.
```suggestion
Die Softwareartefakte werden als Docker Images in eine Container Registry ausgeliefert, die von jedem großen Cloud Anbietern zur Verfügung gestellt wird.
```

2020-08-26 13:32 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Folgende Liste bietet eine Übersicht über die Container Laufzeitumgebungen der großen Cloudanbieter, aufsteigend sortiert nach der Wertigkeit:
Was meinst du hier mit Wertigkeit? Bitte erläutere das genauer.

2020-08-26 13:33 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Um die schnellere und zuverlässige Auslieferung der Software zu garantieren, wird Continuous Integration und Continuous Delivery eingesetzt.
```suggestion
Um die schnellere und zuverlässigere Auslieferung der Software zu garantieren, wird Continuous Integration und Continuous Delivery eingesetzt.
```

2020-08-26 13:33 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Voraussetzung dafür ist eine gute Testabdeckung.
Wieso ist eine gute Testabdeckung Vorraussetzung für CD?

2020-08-26 13:34 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +In letzterem Fall sollte die Umstellung auf FaaS mit der Umstellung der Programmiersprache einhergehen.
```suggestion
Bei Letzterem sollte die Umstellung auf FaaS mit einer Umstellung der Programmiersprache einhergehen.
```

2020-08-26 13:34 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Mit der Umstellung auf Cloud native Services wurde ein großer Teil der Infrastruktur Verantwortung an den Cloud Anbieter ausgelagert, wodurch mehr Fokus auf die Weiterentwicklung der Anwendung gelegt
```suggestion
Mit der Umstellung auf Cloud native Services wurde ein großer Teil der infrastrukturellen Verantwortung an den Cloud Anbieter ausgelagert, wodurch mehr Fokus auf die Weiterentwicklung der Anwendung gelegt werden kann. 
```

2020-08-26 13:34 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Der aufwändige Aufbau, die Wartung und das Patchen der Infrastruktur wurden drastisch reduziert.
```suggestion
Der Aufwand für den Aufbau, die Wartung und das Patchen der Infrastruktur wurden drastisch reduziert.
```

2020-08-26 13:35 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Die Erweiterung der Anwendung wird vereinfacht, da die Services der Cloud Anbieter einfach miteinander integrierbar sind.
```suggestion
Die Erweiterung der Anwendung wird vereinfacht, da die Services der Cloud Anbieter einfach untereinander verbunden werden können.
```

2020-08-26 13:35 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Die Auslagerung der statischen Webseiten in Kombination mit dem CDN sorgt für niedrigste Latenzen.
```suggestion
Die Auslagerung der statischen Webseiten in Kombination mit dem CDN sorgt für niedrige Latenzen.
```

2020-08-26 13:36 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Dazu zählen Web Application Firewalls auch Werkzeuge zur statischen Codeprüfung und Sicherheitsratgeber.
```suggestion
Dazu zählen Web Application Firewalls, aber auch Werkzeuge zur statischen Codeprüfung oder Sicherheitsratgeber.
```

2020-08-26 13:37 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +AWS bietet mit dem Well [Architected Tool](https://aws.amazon.com/de/well-architected-tool/) ein Werkzeug an, das die Architektur analysiert und Verbesserungempfehlungen ausgibt.
Ist das Well zu viel oder gehört es zum Tool-Namen? Wenn es zu viel ist, bitte entferne es, wenn es zum Tool-Namen gehört, schreibe es bitte auch in die eckige Klammer

2020-08-26 13:37 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Somit garantiert die Rearchitecting Strategie zu jederzeit funktionierende und erweiterbare Software.
```suggestion
Die Rearchitecting Strategie garantiert dabei zu jederzeit funktionierende und erweiterbare Software.
```

2020-08-26 13:41 UTC, jo2 requested changes
An sich liest sich der Artikel schon ganz gut. Ein paar Sachen habe ich noch angemerkt. Außerdem:
* Verwende bitte " statt „ und “
* Dadurch, dass du Begriffe, die aus mehreren Teilen bestehen, ohne Bindestrich schreibst (z.B. Cloud Dienst) besteht die Gefahr, beim Lesen darüber zu stolpern und an manchen Stellen wirkt es Inkonsistent  (z.B. Z. 119 "Konfigurations- und Secrets Management"). Von mir aus kannst du es aber so lassen, weil du es konsequent durchgezogen hast.

2020-08-27 11:17 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +In meinem vorangegangenen Blog-Beitrag habe ich [Gründe und Strategien für die Migration einer Applikation in die Cloud aufgezeigt](https://www.adesso.de/de/news/blog/gruende-und-strategien-fuer-die-
Hier ist noch ein aufgezeigt zu viel

2020-08-27 11:29 UTC, jo2 commented on _posts/2020-08-24-cloud-native-migration-mit-der-rearchitecting-strategie.md
> +Google nennt das Vorgehen „move-and-improve".
```suggestion
Google nennt das Vorgehen "move-and-improve".
```

2020-08-27 11:32 UTC, jo2 approved these changes

2020-08-27 11:32 UTC, jo2 commented
@acetous rechtschreibtechnisch sieht der Post soweit gut aus. Machst du noch eine inhaltliche Review?

2020-09-16 08:29 UTC, c-bachmann commented
@acetous Kannst du das Review machen?

2020-10-19 07:36 UTC, acetous approved these changes

2020-10-19 07:38 UTC, merged