Neuer Blogpost: Electron testen mit Spectron
adessoAG/devblog pull request #170
Opened 2020-09-02 06:45 UTC by Segvr

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-09-02 13:30 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Mit dem Electron Framework ist es möglich durch Web-Technologien, Anwendungen desktoptauglich zu entwickeln.
Mit dem Electron Framework ist es durch Web-Technologien möglich, Anwendungen desktoptauglich zu entwickeln.

2020-09-02 13:30 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Ein großer Vorteil gegenüber Webapplikationen ist der, dass die Anwendung offlinefähig ist.
Ein großer Vorteil gegenüber Webapplikationen ist, dass die Anwendung offlinefähig ist.

2020-09-02 13:32 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Denn unser Kunde wird mit der Anwendung arbeiten, auch wenn er keine Verbindung zum Internet hat, und kann später seinen Arbeitsstand synchronisieren, wenn er mit dem Internet verbunden ist.
```suggestion
Unser Kunde wird nämlich auch mit der Anwendung arbeiten, wenn er keine Verbindung zum Internet hat, und später seinen Arbeitsstand synchronisieren, wenn er mit dem Internet verbunden ist.
```

2020-09-02 13:33 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Im Jahr 2013 ist das Projekt (Electron) initial unter dem Namen Atom Shell gestartet worden und diente als Fundament für den hauseigenen Editor ‚Atom‘ für GitHub.
```suggestion
Im Jahr 2013 ist Electron initial unter dem Namen Atom Shell gestartet worden und diente als Fundament für den hauseigenen Editor 'Atom' für GitHub.
```

2020-09-02 13:33 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Spectron ist die hauseigene Testbibliothek für Electron Anwendungen, welches ein Open Source Framework ist, das sich wiederum in Electron befindet.
```suggestion
Spectron ist die hauseigene Testbibliothek für Electron Anwendungen.
Es wird dabei als Teil von Electron ausgeliefert und ist somit auch ein Open Source Framework.
```

2020-09-02 13:34 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Da die Anwendung für unseren Kunden noch in der Entwicklung ist und diese noch nicht veröffentlicht werden darf, habe ich eine eigene kleine Beispielanwendung in Electron erstellt.
```suggestion
Da die Anwendung für unseren Kunden noch in der Entwicklung ist und noch nicht veröffentlicht werden darf, habe ich eine eigene kleine Beispielanwendung in Electron erstellt.
```

2020-09-02 13:34 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Im Folgenden werden wir einen kleinen Test zusammen entwickeln, um Euch einen kurzen Einblick in das Framework zu liefern.
```suggestion
Im Folgenden werden wir zusammen einen kleinen Test entwickeln, um Euch einen kurzen Einblick in das Framework zu liefern.
```

2020-09-02 13:35 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Nachdem wir unsere nötigen Packages hinzugefügt haben, sollte unsere package.json folgendermaßen aussehen:
Ist die package.json hier so interessant? Der Inhalt sollte ja eigentlich aus den ausgeführten npm-Befehlen hervorgehen.

2020-09-02 13:36 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Als nächstes bearbeiten wir unser package.json.
```suggestion
Als nächstes bearbeiten wir unsere package.json. 
```

2020-09-02 13:37 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +    console.log(ueberschrift);
Bitte entferne hier das console.log, es hat für den Test keine Relevanz und sollte daher nicht in einem entsprechenden Tutorial vorkommen.

2020-09-02 13:37 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Also Starten wir vor jedem Testfall den Client neu.
```suggestion
Die 'beforeEach()' Methode wird vor jedem Testfall ausgeführt und startet die Anwendung. 
```

2020-09-02 13:37 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Damit wird die Anwendung also nach jedem Testfall geschlossen.
```suggestion
In der 'afterEach()' Methode, die nach jedem Testfall ausgeführt wird, wird die Anwendung beendet.
```

2020-09-02 13:37 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Um mit Spectron automatisierte Tests zu entwickeln, wäre es von Vorteil, wenn man fundierte Kenntnisse in Programmiersprachen besitzt wie TypeScript.
```suggestion
Um mit Spectron automatisierte Tests zu entwickeln, wäre es von Vorteil, wenn man fundierte Kenntnisse in TypeScript besitzt.
```

2020-09-02 13:38 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Diejenigen, die gar keine oder nur wenig Erfahrung in Programmiersprachen haben, können auf die Tools wie Tricentis Tosca, Ranorex oder eggPlant ausweichen.
```suggestion
Diejenigen, die nur wenig oder gar keine Erfahrung in Programmiersprachen haben, können auf Tools wie Tricentis Tosca, Ranorex oder eggPlant ausweichen.
```

2020-09-02 13:53 UTC, jo2 requested changes
Ein paar Sachen habe ich angemerkt. Außerdem:
* verwende bitte " und ' als Anführungszeichen
* In den Zeilen 128 - 134 gehst du auf den Code ein. Mal erwähnst du den Code in Klammern, mal in Anführungszeichen und mal direkt. Bitte mache das einheitlich.

Darüber hinaus kommt mir der Inhalt etwas wenig für einen Blogpost vor. Folgende Aspekte würden mich zu dem Thema noch interessieren:
* Welche Unterschiede gibt es zwischen den aufgenommenen Skripten der anderen Frameworks und den Befehlen in Spectron?
* Das auslesen von Inhalten wirkt einfach, wie sieht es mit Texten aus, die nicht so einfach zu finden sind, beispielsweise Tooltips an Inputs?
* Ist es auch möglich, Button-Klicks und Texteingaben zu simulieren? Hier könntest du eventuell das Befüllen eines kleinen Formulars, das Login-Formular zum Beispiel, verwenden.

2020-09-04 10:10 UTC, Segvr commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Nachdem wir unsere nötigen Packages hinzugefügt haben, sollte unsere package.json folgendermaßen aussehen:
Ja ich glaube dann wäre an dieser Stelle überflüssig.

2020-09-04 11:33 UTC, Segvr commented
> Ein paar Sachen habe ich angemerkt. Außerdem:
> 
> * verwende bitte " und ' als Anführungszeichen
> * In den Zeilen 128 - 134 gehst du auf den Code ein. Mal erwähnst du den Code in Klammern, mal in Anführungszeichen und mal direkt. Bitte mache das einheitlich.
> 
> Darüber hinaus kommt mir der Inhalt etwas wenig für einen Blogpost vor. Folgende Aspekte würden mich zu dem Thema noch interessieren:
> 
> * Welche Unterschiede gibt es zwischen den aufgenommenen Skripten der anderen Frameworks und den Befehlen in Spectron?
Das wäre noch eine gute Ergänzung. 

> * Das auslesen von Inhalten wirkt einfach, wie sieht es mit Texten aus, die nicht so einfach zu finden sind, beispielsweise Tooltips an Inputs?

Wäre das nicht ein wenig zu viel Detail? Ich könnte das beschreiben aber ich finde das ich dann eins zwei Methoden näher beschreibe und andere nicht. Dann müsste man ja auf sehr viele andere "Problemstellen" auch eingehen oder? Wenn es aber in Ordnung ist  auf 1-2 Top Problemstellen einzugehen dann würde ich das natürlich noch ergänzen.

> * Ist es auch möglich, Button-Klicks und Texteingaben zu simulieren? Hier könntest du eventuell das Befüllen eines kleinen Formulars, das Login-Formular zum Beispiel, verwenden.
Ich kann ja den Testcode erweitern, sodass ich noch das Befüllen der 2 Inputfelder mitbeschreiben kann. Reicht das an der Stelle?

2020-09-07 06:50 UTC, jo2 commented
Auf alle Punkte musst du nicht eingehen, das würde wahrscheinlich den Rahmen sprengen. Zumindest einen der Punkte fände ich aber schon interessant, damit der Blogpost nicht nur wie ein "Hello World"-Beispiel wirkt. @acetous was meinst du denn dazu? Rechtschreibtechnisch ist der Post ansonsten soweit korrigiert.

2020-09-14 09:50 UTC, Segvr commented
@jo2:
Ich habe die vorgeschlagenen Punkte versucht so weit wie Möglich einzubinden.

2020-09-24 06:04 UTC, jo2 commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Ein Paramenter um das Element zu finden über die ID, welches Inputfeld angesprochen werden soll und dem zweiten Paramenter geben wir den Inhalt selbst mit.
```suggestion
Der erste Paramenter dient dazu, das entsprechende Inputelement über die ID zu finden, der zweite weist dem Feld den angegebenen Wert zu.
```

2020-09-24 06:07 UTC, jo2 requested changes
Eine Sache ist mir noch aufgefallen. Ist es in dem Test dann auch möglich, zu überprüfen. dass die Attribute der Komponente gesetzt wurden? Also sowas wie: 
```
expect(component.username).toBe('username');
expect(component.password).toBe('password');
```
als Erfolgskriterien für den Test? Danach sollte der Post mMn. fertig sein, über den Merge entscheidet Sebastian dann.

2020-09-30 11:02 UTC, jo2 approved these changes

2020-10-14 13:54 UTC, jo2 commented
Mit deinem merge ist etwas kaputt gegangen. Du hast Änderungen in Posts committed, die nicht von dir sin. Bitte überprüfe das nochmal und verwende rebase statt merge, da treten Erfahrungsgemäß weniger Probleme auf

2020-10-16 08:50 UTC, jo2 commented
In der authors.yml entfernst du auch noch Autoren, das müsstest du auch noch korrigieren.

2020-10-19 09:14 UTC, jo2 commented
In deinem PR entfernst und veränderst du immernoch Einträge anderer Autoren in der authors.yml. Das musst du noch beheben.

2020-10-23 12:10 UTC, Segvr commented
> In deinem PR entfernst und veränderst du immernoch Einträge anderer Autoren in der authors.yml. Das musst du noch beheben.

Könntest du mir mal genau zeigen wo die Stellen sind?
ich sehe keine Stelle wo ich Einträge  geändert habe in der authors.yml

2020-10-26 12:44 UTC, jo2 commented
Unter Files Changed sind die Änderungen in deinem PR aufgelistet. Dort sind einige Änderungen in der authors.yml aufgeführt. Es kann sein, dass die beim mergen entstanden sind. 
![image](https://user-images.githubusercontent.com/7516893/97173738-5513f480-1791-11eb-80c2-a516ff02a9f8.png)

2020-10-26 14:50 UTC, Segvr commented
> Unter Files Changed sind die Änderungen in deinem PR aufgelistet. Dort sind einige Änderungen in der authors.yml aufgeführt. Es kann sein, dass die beim mergen entstanden sind.
> ![image](https://user-images.githubusercontent.com/7516893/97173738-5513f480-1791-11eb-80c2-a516ff02a9f8.png)

Ja die Änderungen siehst du weil ich ja die authors.yml wieder zurückgesetzt habe.
https://github.com/Segvr/devblog/blob/2195e96055a08f0e6957b6c2ace7fac8676a0729/_data/authors.yml

Ich hab die gleichen Daten wie vor 2 Monaten wieder drin. 
Das müsste doch jetzt so passen.

2020-10-27 16:04 UTC, jo2 commented
Das Problem ist, dass in den letzten 2 Monaten einige Posts dazugekommen sind. mit den Änderungen entfernst du die Änderungen aus den letzten 2 Monaten

2020-10-27 17:29 UTC, acetous requested changes

2020-10-27 17:29 UTC, acetous commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Die Anwendung wird jeden Sprint komplexer und natürlich brauchen wir mit jeder neuen Funktion, die dazu kommt, neue Tests.
```suggestion
Die Anwendung wird jeden Sprint um weitere Features erweitert und natürlich brauchen wir mit jeder neuen Funktion, die dazu kommt, neue Tests. 
```

2020-10-27 17:29 UTC, acetous commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Diese Tools benötigen aber Lizenzen und somit muss man entscheiden, ob das Projektbudget für eines dieser Tools ausreicht.
```suggestion
Diese Tools sind kostenpflichtig und somit muss man entscheiden, ob das Projektbudget für eines dieser Tools ausreicht. 
```
Eine Lizenz sollte jeder Software haben, im Zweifel sogar sowas wie Open Source. ;)

2020-10-27 17:29 UTC, acetous commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Im Folgenden werden wir zusammen einen kleinen Test entwickeln, um Euch einen kurzen Einblick in das Framework zu liefern.
```suggestion
Im Folgenden werden wir zusammen einen Test entwickeln, um Euch einen kurzen Einblick in das Framework zu liefern.
```
Deine Ergebnisse musst Du nicht verniedlichen.

2020-10-27 17:29 UTC, acetous commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Sobald wir das Kommando „npm run test“ ausführen, schaut Mocha nach ausführbaren Tests und führt diese dann aus.
```suggestion
Sobald wir das Kommando `npm run test` ausführen, schaut Mocha nach ausführbaren Tests und führt diese dann aus. 
```
Code oder Befehle kannst Du entsprechend formatiert anzeigen lassen. Verwende das bitte auch für die weiteren Stellen, an denen Du inline Code schreibst.

2020-10-27 17:29 UTC, acetous commented on _posts/2020-09-01-electron-testen-mit-spectron.md
> +Da die Anwendung für unseren Kunden noch in der Entwicklung ist und noch nicht veröffentlicht werden darf, habe ich eine eigene kleine Beispielanwendung in Electron erstellt.
Die "Kundenprojekt"-Story wirkt ein bisschen aufgesetzt. Ab hier finde diese sogar gar keine Erwähnung mehr.
Ich würde das entweder ganz streichen und nur das Framework vorstellen oder nur in der Einleitung das Szenario aus dem Projekt skizzieren.

2020-11-13 13:42 UTC, Segvr commented
Könnte ich mir nicht einfach die aktuellste version der authors.yml aus dem Master kopieren und meine Daten am Ende hinzufügen?

2020-11-13 13:50 UTC, jo2 commented
Du kannst, wenn du auf deinem master einen Stand committed hast, mit `git pull https://github.com/adessoAG/devblog` den Stand vom adesso devblog in deinen lokalen Stand ziehen. Dann hast du den akteullen Stand in deinem Stand. Anschließend pusht du das auf deinen remote Branch. Dadurch aktualisiert sich dann auch der PR.

2020-11-18 10:55 UTC, Segvr commented
@jo2 Jetzt müsste es passen.

2020-11-18 13:46 UTC, jo2 commented
Die Probleme sind in #184 behoben, dieser PR wird entsprechend geschlossen.

2020-11-18 13:46 UTC, closed without merging