Blog post "Produktiver mit Firebase"
adessoAG/devblog pull request #171
Opened 2020-09-08 05:44 UTC by daklassen

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [ x [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-09-08 06:51 UTC, jo2 commented on _data/authors.yml
>    email: daviddd.kl@gmail.com
Bitte nutze hier deine adess-E-Malil

2020-09-08 08:31 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +In diesem Beitrag möchte ich von meinen Erfahrungen mit der Plattform berichten, indem ich von meiner Migration auf Firebase im Rahmen eines Hobbyprojektes berichte.
In diesem Satz hast du zwei mal "berichten" drin, kannst du eins von beiden durch ein anderes Wort ersetzen?

2020-09-08 08:32 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Außerdem wollte ich die Anwendung in Zukunft auch gerne irgendwann öffentlich schalten, was nochmal zusätzlichen Aufwand bedeutet hätte, weil ich mir verstärkt Gedanken um Sicherheit, Verfügbarkeit o
```suggestion
Außerdem wollte ich die Anwendung in Zukunft auch gerne irgendwann öffentlich schalten, was nochmal zusätzlichen Aufwand bedeutet hätte, weil ich mir verstärkt Gedanken um Sicherheit, Verfügbarkeit oder Skalierbarkeit hätte machen müssen.
```

2020-09-08 08:32 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Im Folgenden möchte ich grob auf diese Anpassungen eingehen, um so den Unterschied zwischen einer klassischen Java Enterprise Lösung und Firebase exemplarisch klar zu machen und einige Produkte von F
```suggestion
Im Folgenden möchte ich grob auf diese Anpassungen eingehen, um so den Unterschied zwischen einer klassischen Java Enterprise Lösung und Firebase exemplarisch darzustellen und um einige Produkte von Firebase vorzustellen.
```

2020-09-08 08:33 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Auch nach der Migration sollte dies zunächst der einzige Weg für einen Login sein. Als Vorbereitung habe ich in der Firebase Konsole Google als möglichen Anbieter aktiviert.
```suggestion
Auch nach der Migration sollte dies zunächst der einzige Weg für einen Login sein.
Als Vorbereitung habe ich in der Firebase Konsole Google als möglichen Authentication Provider aktiviert.
```

2020-09-08 08:33 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Beispielsweise die Möglichkeit, die Benutzer über einen eigenen Identity Provider zu authentifizieren oder eine eigene Zwei-Faktor-Authentisierung zu erstellen.
```suggestion
Dazu gehören beispielsweise die Möglichkeit, die Benutzer über einen eigenen Identity Provider zu authentifizieren oder eine eigene Zwei-Faktor-Authentisierung zu erstellen.
```

2020-09-08 08:33 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Falls jedoch, wie in meinem Fall, auf diese Dinge verzichtet werden kann, spart man Aufwand ein ohne Risiken bzgl. Sicherheit eingehen zu müssen.
```suggestion
Falls jedoch, wie in meinem Fall, auf diese Dinge verzichtet werden kann, spart man sich die potentiell mit Sicherheitsrisiken behaftete Implementierung dieser Funktionen.
```

2020-09-08 08:34 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Da mein Backend hauptsächlich CRUD-Operationen durchgeführt hat und zusätzlich mithilfe von Keycloak Autorisierungs-Fragen prüfte, ließ es sich sehr einfach Migrieren.
```suggestion
Da mein Backend hauptsächlich CRUD-Operationen durchgeführt hat und zusätzlich mithilfe von Keycloak Autorisierungen prüfte, ließ es sich sehr einfach Migrieren.
```

2020-09-08 08:35 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Eine sog. Echtzeitdatenbank und den Cloud Firestore.
Bitte formuliere das so um, dass es einen ganzen Satz ergibt.

2020-09-08 08:35 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Der Unterschied liegt im Datenmodel;
Bitte formuliere das so um, dass es einen ganzen Satz ergibt.

2020-09-08 08:35 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +
Fehlt hier eine Angular-Klassendefinition? Du Kannst mMn. auch alles über dem Konstruktor bzw. der Klassendefinition weglassen.

2020-09-08 08:36 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +        actions.map(a => {
Verwende in Beispielcode bitte sprechende Variablen, das erleichtert das Lesen und hilft, den Code zu verstehen.

2020-09-08 08:36 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Das bedeutet, dass selbst wenn ich über die Google Konsole Daten in der Datenbank verändere, diese in Echtzeit direkt an alle Benutzer propagiert werden, die sich in diesem Fall gerade das Rezept ans
Aus persönlichem Interesse, du muss im Blogpost nicht drauf eingehen: Wird die Verbindung aufrecht erhalten solange die Session gültig ist, sodass darüber immer wieder neue Nachrichten verteilt werden können ähnlich wie bei einer Message-Queue?

2020-09-08 08:37 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Insgesamt bekommt man als Entwickler auch was die Datenbank angeht komplexe und teure Funktionen geboten.
```suggestion
Auch auf Seiten der Datenbank werden komplexe und teure Funktionen angeboten.
```

2020-09-08 08:37 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Darüber hinaus stellt Firebase auch eine ganze Reihe an Produkten zur Qualitätssicherung und Analyse bereit.
Kannst du hier noch Material zum Weiterlesen verlinken? Oder folgen da noch weitere Blog-Posts?

2020-09-08 08:37 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Insgesamt also ein valider Kandidat für euer nächstes Projekt - auch wenn es "nur" ein Hobbyprojekt ist.
```suggestion
Insgesamt ist Firebase also ein valider Kandidat für euer nächstes Projekt - auch wenn es "nur" ein Hobbyprojekt ist.
```

2020-09-08 08:38 UTC, jo2 requested changes
Der Post liest sich schon sehr gut, ein paar Sachen habe ich noch angemerkt.

2020-09-10 17:25 UTC, daklassen commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +
Ich wollte damit eigentlich klar machen, dass der "injectete" Service hier aus der firestore lib kommt. Werde die Klassendefinition hinzufügen

2020-09-10 17:43 UTC, daklassen commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Das bedeutet, dass selbst wenn ich über die Google Konsole Daten in der Datenbank verändere, diese in Echtzeit direkt an alle Benutzer propagiert werden, die sich in diesem Fall gerade das Rezept ans
Bei der Echtzeitdatenbank ganz klassisch über WebSockets und bei der neueren Firestore Datenbank über gRPC

2020-09-10 17:44 UTC, daklassen commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Darüber hinaus stellt Firebase auch eine ganze Reihe an Produkten zur Qualitätssicherung und Analyse bereit.
Könnte auf https://firebase.google.com/?hl=de als Doku verlinken. Ein weitere Blog Artikel ist erstmal nicht geplant zu diesem Thema

2020-09-10 17:45 UTC, daklassen commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +In diesem Beitrag möchte ich von meinen Erfahrungen mit der Plattform berichten, indem ich von meiner Migration auf Firebase im Rahmen eines Hobbyprojektes berichte.
Guter Hinweis. Ist angepasst.

2020-09-10 17:47 UTC, daklassen commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Eine sog. Echtzeitdatenbank und den Cloud Firestore.
Du meinst den letzten Satz oder? Habe es angepasst

2020-09-10 17:48 UTC, daklassen commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Der Unterschied liegt im Datenmodel;
Du meinst den letzten Satz oder? Habe es ebenfalls angepasst.

2020-09-10 17:50 UTC, daklassen commented
> Der Post liest sich schon sehr gut, ein paar Sachen habe ich noch angemerkt.

Danke fürs ausführliche Review

2020-09-11 08:40 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +
Durch diese weitere Leerzeile leitest du einen neuen Absatz ein, sodass Z. 57 alleine in einem Absatz steht. Ist das so beabsichtigt?

2020-09-11 08:45 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Zum einen die sogenannte Echtzeitdatenbank und zum anderen den Cloud Firestore.
Das ist so immernoch kein ganzer Satz. Vielleicht:
```suggestion
Es gibt da zum einen die sogenannte Echtzeitdatenbank und zum anderen den Cloud Firestore.
```

2020-09-11 08:46 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +      .collection<RecipeDTO>('recipes', ref => ref.where('author.id', '==', user.id))
Das habe ich jetzt grade erst gesehen, reicht hier in JS ein `==` oder brauch man hier ein `===`?

2020-09-11 08:51 UTC, jo2 commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +Darüber hinaus stellt Firebase auch eine ganze Reihe an Produkten zur Qualitätssicherung und Analyse bereit.
Verlinke hier doch die Leistungsüberwachung, das siehr mMn. am interessantesten aus. Vielleicht könntest du das wie folgt formulieren.
```suggestion
Interessant wäre da besonders die Betrachtung der Cloud Functions, die quasi das klassische Backend ablösen.
Darüber hinaus stellt Firebase auch eine ganze Reihe an Produkten zur Qualitätssicherung und Analyse bereit.
Als Beispiel ist hier die [Leistungsüberwachung](https://firebase.google.com/products/performance?hl=de) zu nennen, die einen guten Einblick in die Performance Details der App liefert.
```

2020-09-11 08:53 UTC, jo2 requested changes
Drei Sachen sind mir noch aufgefallen, danach ist der Post mMn. ready for merge.

2020-09-11 17:28 UTC, daklassen commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +
Stimmt. Nein das war keine Absicht.

2020-09-11 17:30 UTC, daklassen commented on _posts/2020-09-05-Produktiver-mit-Firebase.md
> +      .collection<RecipeDTO>('recipes', ref => ref.where('author.id', '==', user.id))
Nein das ist kein JS an dieser Stelle. Das ist eine eigene Query "Sprache"/Syntax von Firestore. Aber danke für den Hinweis.

2020-09-11 17:35 UTC, daklassen commented
Danke nochmal für die Anmerkungen und Korrekturen. Jetzt sollte alles angepasst sein.

2020-09-24 06:11 UTC, jo2 approved these changes

2020-10-27 18:32 UTC, acetous approved these changes

2020-10-30 11:19 UTC, acetous approved these changes

2020-10-30 13:52 UTC, merged