E2E-Tests Artikel
adessoAG/devblog pull request #173
Opened 2020-09-30 14:38 UTC by thorbolo

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-10-12 06:57 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +In diesem Artikel geht es um automatisierte, in der CI-Pipeline integrierbare, Tests, die die gesamte Geschäftslogik eines Monolithen von der obersten Schicht (einem Webservice) bis zur untersten Sch
```suggestion
In diesem Artikel geht es um automatisierte, in die CI-Pipeline integrierbare, Tests, die die gesamte Geschäftslogik eines Monolithen von der obersten Schicht (einem Webservice) bis zur untersten Schicht (der Datenbank) abdecken können.
```

2020-10-12 06:58 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +Dieser Artikel richtet sich an Projektleiter, Architekten oder interessierte Entwickler, die sich bei der Entwicklung eines Webservices (oder danach) fragen, wie man diesen dauerhaft testet und quali
```suggestion
Dieser Artikel richtet sich an Projektleiter, Architekten oder interessierte Entwickler, die sich bei der Entwicklung eines Webservice (oder danach) fragen, wie man diesen dauerhaft testen und qualitätssichern kann.
```

2020-10-12 07:23 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +Beide Möglichkeiten erfordern allerdings einen relativ großen Pflege Aufwand und vor allem erodieren sie schnell, wenn die Schnittstelle sich mit der Zeit ändert.
```suggestion
Beide Möglichkeiten erfordern allerdings einen relativ großen Pflegeaufwand und vor allem erodieren sie schnell, wenn die Schnittstelle sich mit der Zeit ändert.
```

2020-10-12 07:25 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +Aus dem "As-Code" Gedanken, entsprang die Idee, ob das nicht in leicht ausführbaren Tests wie Unit-Tests zu lösen sei.
```suggestion
Aus dem "As-Code" Gedanken entsprang die Idee, ob das nicht in leicht ausführbaren Tests wie Unit-Tests zu lösen sei.
```

2020-10-12 07:27 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +Dieser Schritt wird zu jeder Laufzeit neu erledigt und ist recht zeitintensiv.
```suggestion
Dieser Schritt wird für jeden Testdurchlauf neu erledigt und ist recht zeitintensiv.
```

2020-10-12 07:28 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +Mithilfe des *rest-assured*-Frameworks wird schließlich ein Rest-Client erzeugt, der die Restendpoints des Webservices anspricht und direkt Assertions für die Responses mitbringt.
```suggestion
Mithilfe des *rest-assured*-Frameworks wird schließlich ein Rest-Client erzeugt, der die Restendpoints des Webservice anspricht und direkt Assertions für die Responses mitbringt.
```

2020-10-12 07:31 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +Zahlreiche weitere anwendungsspezifische Konfigurationen werden mit den Hausmitteln von JUnit eingerichtet, sodass am Anfang eines jeden JUnit-Tests eine fertige Laufzeit des Monolithen und ein Rest-
```suggestion
Zahlreiche weitere anwendungsspezifische Konfigurationen werden mit den Hausmitteln von JUnit eingerichtet, sodass am Anfang eines jeden JUnit-Tests eine fertige Laufzeitumgebung des Monolithen und ein Rest-Client zur Verfügung stehen.
```

2020-10-12 07:32 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +- Ausführung der Tests in CI-Pipeline und damit frühzeitige Erkennung von Fehlern in der Geschäftslogik des Monolithen
```suggestion
- Ausführung der Tests in der CI-Pipeline und damit frühzeitige Erkennung von Fehlern in der Geschäftslogik des Monolithen
```

2020-10-12 07:33 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +- "As-Code" erleichtert Entwicklern das Schreiben fachlicher Testszenarios.
```suggestion
- "As-Code" erleichtert Entwicklern das Schreiben fachlicher Testszenarien
```

2020-10-12 07:34 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +- Once-Written-Never-Forgotten; Testszenarios müssen nur einmalig als Test implementiert werden und werden bei jeder zukünftigen Ausführung abgetestet.
```suggestion
- Once-Written-Never-Forgotten; Testszenarien müssen nur einmalig als Test implementiert werden und werden bei jeder zukünftigen Ausführung abgetestet.
```

2020-10-12 07:39 UTC, jo2 requested changes
Ein paar Sachen sind mir noch aufgefallen. Außerdem hast du mit der aktuellen Formatierung (eine Leerzeile zwischen jedem Satz) einen Satz pro Absatz, etwas längere Absätze verbessern da den Lesefluss, überprüfe bitte mal, ob du wirklich überall einen neuen Absatz benötigst.

2020-10-19 07:12 UTC, thorbolo commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +- "As-Code" erleichtert Entwicklern das Schreiben fachlicher Testszenarios.
Ist hier der Punkt verloren gegangen?

2020-10-19 09:10 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +- Once-Written-Never-Forgotten; Testszenarien müssen nur einmalig als Test implementiert werden und werden bei jeder zukünftigen Ausführung abgetestet.
```suggestion
- Once-Written-Never-Forgotten; Testszenarien müssen nur einmalig als Test implementiert werden und werden bei jeder zukünftigen Ausführung abgetestet
```
Du hast bei Aufzählungen sonst nie einen Punkt am Satzende.

2020-10-19 09:11 UTC, jo2 requested changes
Eine Kleinigkeit habe ich noch gefunden.

2020-10-26 12:41 UTC, jo2 commented on _posts/2020-09-30-E2E-Tests-vom-Webservice-bis-zur-DB-eines-Monolithen-mit-JUnit.md
> +# Die Sclaimer ("Disclaimer" wäre ein Kombobreaker gewesen:)
Hier fehlt noch eine Klammer zu, das sieht dann aber mit dem Smiley vielleicht etwas komisch aus. Vielleicht kannst du den Smiley weglassen oder so.

2020-10-26 12:42 UTC, jo2 requested changes
Das hatte ich mir noch aufgeschrieben, aber wohl vergessen anzumerken. Sorry.

2020-10-27 16:01 UTC, jo2 approved these changes

2020-11-09 15:31 UTC, jo2 submitted a review, later dismissed

2020-12-18 15:54 UTC, acetous reviewed
Sehr schöner Artikel! Rückfragen via Mail. :)

2020-12-23 08:31 UTC, jo2 commented
@acetous ist das ein Apporve? Wenn ja, bitte als solchen markeieren, dann können wir mergen.

2021-03-19 14:23 UTC, acetous approved these changes

2021-03-19 14:24 UTC, merged