Erste Version von meinem BLog
adessoAG/devblog pull request #175
Opened 2020-10-09 13:16 UTC by mschulz-adesso

Noch nicht freigeben, möchte mir die Online Version anschauen

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x ] "title" vergeben
    - [ x] "author" angegeben
    - [x ] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [x ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ x] Rechtschreibung korrigiert
  - [ x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-10-09 13:28 UTC, mschulz-adesso commented
Erster versuch

2020-10-11 17:00 UTC, mschulz-adesso commented
Test Preview

2020-10-12 06:47 UTC, jo2 commented
Kommen hier noch mehr Korrekturen deinerseits? Wenn ja, markiere den Post bitte als "Draft", bis du fertig bist. Ansonsten geb mir bitte eben kurz bescheid, dann fange ich mit dem Review an.

2020-10-12 12:15 UTC, mschulz-adesso commented
Ready für Review

2020-10-12 13:36 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Jeder kennt es, bestimmte IT-Arbeitsschritte, die sich von den Eingaben unterscheiden, jedoch nicht von den Klicks - Hier gibt es ein enormes Optimierungspotential, wenn diese Tätigkeiten automatisie
```suggestion
Jeder kennt es, bestimmte IT-Arbeitsschritte, die sich von den Eingaben, aber nicht von den Klicks unterscheiden.
Hier gibt es für jeden durch Automatisierung dieser Tätigkeiten ein enormes Optimierungspotential.
```

2020-10-12 13:36 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Speziell „Robotic Process Automation“ (RPA) kann uns hier unterstützen und ermöglicht die automatisierte Ausführung von manuellen Eingaben.
```suggestion
"Robotic Process Automation" (RPA) kann uns hier unterstützen und ermöglicht die automatisierte Ausführung von manuellen Eingaben.

```

2020-10-12 13:37 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +* FK liest Rechnung, gibt Rechnung frei als Prosatext in der Email und sendet Email zurück -> 5 Min
```suggestion
* FK liest Rechnung, gibt Rechnung in der Email als Prosatext frei und sendet E-Mail zurück -> 5 Min

```

2020-10-12 13:37 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +**Switching-Zeit / Verlust des Fokus:** Viel niedriger, da u.a. wichtige Informationen hervorgehen werden
```suggestion
**Switching-Zeit / Verlust des Fokus:** Viel niedriger, da u.a. wichtige Informationen hervorgehoben werden

```

2020-10-12 13:38 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Hierbei wird Outlook und Microsoft Teams ein Kommunikationsplattform genutzt.
```suggestion
Hierbei wird Outlook und Microsoft Teams als Kommunikationsplattform genutzt.
```

2020-10-12 13:41 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Ich nutze die Workflow-Engine PowerAutomate aka Flows, um die ganzen Prozessschritte auszuführen. Dabei wird die RPA Funktion über die Benutzeroberflächen Flows ausgeführt.
```suggestion
Ich nutze die Workflow-Engine PowerAutomate aka Flows, um die Prozessschritte auszuführen.
Dabei wird die RPA Funktion über Benutzeroberflächen Flows ausgeführt.
```

2020-10-12 13:41 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Die Entscheidung, was passieren soll, enthält jetzt spannenden Themen:
```suggestion
Die Entscheidung, was passieren soll, enthält die eigentlich spannende Logik:
```

2020-10-12 13:42 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +* Nimmt die Daten und erstellt eine Optionsauswahl-Post in einem ausgewählten Bot-Teams-Chat
```suggestion
* PowerAutomate benutzt die Anlage der empfangenen Email - in diesem Fall eine PDF
* Weitergabe des PDF an die KI-KI-Komponente
* Automatische Extraktion relevanter Rechnungsdaten aus der PDF
* Erstellen eines Optionsauswahl-Post in einem ausgewählten Bot-Teams-Chat
```

2020-10-12 13:42 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +### Extrahiert automatisiert relevante Rechnungsdaten aus der PDF
```suggestion
### Automatisierte Extraktion relevanter Rechnungsdaten aus der PDF
```

2020-10-12 13:43 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Hierbei habe ich mindestens fünf Beispiel-Rechnungen erstellt und hochgeladen damit der AI Builder die relevanten Informationen wie Datum, Betrag etc. automatisch "erlernt".
Wieso schreibst du hier mindestens? kannst du hier die genaue zahl nennen? Wenn nicht, umschreibe es bitte mit so etwas wie einige.

2020-10-12 13:44 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Mit dem AI Builder kann ich dem Modell sagen, welche Felder relevant sind auf den Rechnungen, damit es selbständig "trainieren" kann.
```suggestion
Mit dem AI Builder kann ich dem Modell sagen, welche Felder einer Rechnung relevant sind, damit es selbständig "trainieren" kann.
```

2020-10-12 13:44 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Um Eingaben zu automatisieren, muss ich vorab die Eingabe "recorden", damit der Benutzeroberflächen Flow diese Schritte automatisieren kann. Hierbei werden ein paar kostenlose Tools von Microsoft und
```suggestion
Um Eingaben zu automatisieren, muss ich vorab die Eingabe "recorden", damit der Benutzeroberflächen Flow diese Schritte automatisieren kann.
Hierfür werden ein paar kostenlose Tools von Microsoft und Selenium benötigt.
```

2020-10-12 13:44 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +PowerAutomate Desktop bietet mir eine Vielzahl von Operationen, u.a. das Recorden von Webseiten oder von Desktop-Applikationen.
```suggestion
PowerAutomate Desktop bietet mir eine Vielzahl von Operationen, u.a. das Recorden von Webseiten oder Desktop-Applikationen. 
```

2020-10-12 13:47 UTC, jo2 requested changes
Der Beitrag liest sich schon recht gut, ein paar Sachen habe ich noch angemerkt. Außerdem:
* Z. 037, 049: Kannst du hier eine geordnete Aufzählung verwenden?
* Schreibe Einführungen von Abkürzungen bitte einheitlich (vgl.  "FK (Führungskraft)" und "Mitarbeiter (MA)")
* Bitte Email durch E-Mail ersetzen
*  Benutzeroberflächen Flow ist recht missverständlich, auch wenn es sich dabei um die korrekte Übersetzung handelt. Kannst du das etwas umformulieren, sodass klar ist, dass es sich um eine bestimmte Art von Workflow von PowerAutomate handelt?
* du hast mit der aktuellen Formatierung (eine Leerzeile zwischen jedem Satz) einen Satz pro Absatz, etwas längere Absätze verbessern da den Lesefluss, überprüfe bitte mal, ob du wirklich überall einen neuen Absatz benötigst.
* Du hast teilweise mehrere Sätze pro Zeile, das erschwert den Review-Prozess. Achte bitte darauf, nur einen Satz pro Zeile zu schreiben

2020-10-12 13:49 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +Vorher
```suggestion
Vorher:
```

2020-10-12 16:36 UTC, mschulz-adesso commented
Fertig, ready for Review die 2. ;)

2020-10-12 17:08 UTC, jo2 commented
In Zeile 117 ist noch ein Kommentar von mir,  dort schreibst du, du hast mindestens 5 Beispiele für das Training der KI hochgeladen. Kannst du da die genaue zahl nennen? Wenn nicht, umschreibe es bitte mit so etwas wie einige.

2020-10-12 17:13 UTC, jo2 reviewed
In Zeile 117 ist noch ein Kommentar von mir, dort schreibst du, du hast mindestens 5 Beispiele für das Training der KI hochgeladen. Kannst du da die genaue zahl nennen? Wenn nicht, umschreibe es bitte mit so etwas wie einige. Danach ist der Post aus meiner Sicht fertig.

2020-10-12 17:25 UTC, jo2 commented
Irgendwas ist mit der Formatierung des Teasers noch nicht ganz richtig, da kümmer ich mich aber drum.

2020-10-13 15:04 UTC, jo2 commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +
Diese Leerzeile ist, denke ich, nicht notwendig, da du wahrscheinlich keinen neuen Absatz anfangen möchtest.

2020-10-13 15:31 UTC, mschulz-adesso commented on _posts/2020-10-06-Zeitersparnis-durch-RPA-und-Microsoft-PowerPlatform.md
> +
Passt

2020-10-13 15:42 UTC, jo2 requested changes
Du hast noch eine Datei Thumbs.db in dem pull request, die du nicht verwendest. Kannst du die bitte noch entfernen?

2020-10-14 13:55 UTC, jo2 approved these changes

2020-10-14 13:56 UTC, jo2 commented
@acetous Rechtschreibtechnisch ist soweit alles in Ordnung. Machst du noch eine inhaltliche Review?

2020-10-23 10:28 UTC, acetous approved these changes

2020-10-23 10:28 UTC, merged