Phishing Kampagne
adessoAG/devblog pull request #177
Opened 2020-10-19 06:28 UTC by VivienEmily

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Business & People)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-10-19 06:30 UTC, VivienEmily commented
Es gab ein paar Komplikationen mit den Rechten der verschiedenen E-Mail Adressen. Leider kann ich den anderen PR nicht annehmen, da mir die Rechte fehlen und löschen kann ich ihn Leder auch nicht. Daher hier ein neuer Versuch. Alle vorherigen Änderungen habe ich eingepflegt.

2020-10-19 06:56 UTC, jo2 commented on _data/authors.yml
> +  vschiller:
```suggestion
vschiller:
```

2020-10-19 07:08 UTC, jo2 commented on _posts/2020-10-19-Phishining_Kampagne_ZDF.md
> +categories: [Business & People]
```suggestion
categories: [People]       
```

2020-10-19 07:19 UTC, jo2 commented on _posts/2020-10-19-Phishining_Kampagne_ZDF.md
> +Wird eine Phishing E-Mail nicht durch technische Maßnahmen daran gehindert, vom Empfangenden aufgerufen zu werden, liegt es am diesem, richtig zu handeln.
```suggestion
Wird eine Phishing E-Mail nicht durch technische Maßnahmen daran gehindert, vom Empfangenden aufgerufen zu werden, liegt es an diesem, richtig zu handeln. 
```

2020-10-19 07:28 UTC, jo2 commented on _posts/2020-10-19-Phishining_Kampagne_ZDF.md
> +"Einmal mit der Brechstange eine Phishing Simulation durchführen", beschreibt die geplanten zwei Wochen dauernde Phishing Simulation recht gut.
```suggestion
"Einmal mit der Brechstange eine Phishing Simulation durchführen", beschreibt die geplante zwei Wochen dauernde Phishing Simulation recht gut. 
```

2020-10-19 07:40 UTC, jo2 approved these changes

2020-10-19 07:41 UTC, jo2 requested changes
Eine Sache hatte ich noch übersehen. Zusammengesetzte Begriffe (bspw. Phishing-Schulungen und Phishing Simulationen) solltest du entweder einheitlich mit oder ohne Bindestrich schreiben

2020-10-19 08:09 UTC, VivienEmily commented
Habe die Bindestriche rausgenommen.

2020-10-19 15:40 UTC, jo2 commented
Das Bezog sich nicht nur auf Phishing-Simulation sondern auf alle zusammengesetzten Wörter. Bspw. 
* LinkedIn-Anmeldeseite
* Passwort-Feld
* CEO-Fraud

2020-10-20 07:01 UTC, VivienEmily commented
Ich hoffe ich habe jetzt alles erwischt.

2020-10-20 13:17 UTC, jo2 approved these changes

2020-10-20 13:17 UTC, jo2 commented
@acetous machst du noch eine inhaltliche Review?

2020-11-13 08:01 UTC, acetous approved these changes

2020-11-13 08:03 UTC, merged