Wartbarkeit 1
adessoAG/devblog pull request #183
Opened 2020-11-16 09:35 UTC by anbeth

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, People, Inside adesso)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-11-16 14:32 UTC, jo2 commented
@anbeth ist der Artikel soweit fertig? Wenn nicht, markiere den PR bitte als Draft, bis er fertig ist.

2020-11-16 14:44 UTC, anbeth commented
@jo2 Hallo Johannes, ja der Artikel ist bereit zum Review.

2020-11-16 15:12 UTC, jo2 commented on _data/authors.yml
> +  bio: "Thilo Lange ist Software Architect am Standort Stralsund"
Ihr verwendet einmal die englische Schreibweise Software Architect und einmal die deutsche Schreibweise Software Architektin, bitte einigt euch hier auf eine Schreibweise.

2020-11-16 15:13 UTC, jo2 commented on _data/authors.yml
> +  bio: "Anja Bethge ist Software Architektin am Standort Stralsund. Seit über fünf Jahren ist sie im Bereich Wartung und Applikation Management tätig und hat schon viele gute und auch nicht so gute B
```suggestion
  bio: "Anja Bethge ist Software Architektin am Standort Stralsund. Seit über fünf Jahren ist sie im Bereich Wartung und Application Management tätig und hat schon viele gute und auch nicht so gute Beispiele für wartbare Software gesehen."
```
oder 
```suggestion
  bio: "Anja Bethge ist Software Architektin am Standort Stralsund. Seit über fünf Jahren ist sie im Bereich Wartung und Applikationsmanagement tätig und hat schon viele gute und auch nicht so gute Beispiele für wartbare Software gesehen."
```

2020-11-16 15:14 UTC, jo2 commented on _data/authors.yml
> +  bio: "Anja Bethge und Thilo Lange sind Software Architekten am Standort Stralsund. Seit über fünf Jahren sind beide im Bereich Wartung und Applikation Management tätig und haben schon viele gute un
```suggestion
  bio: "Anja Bethge und Thilo Lange sind Software Architekten am Standort Stralsund. Seit über fünf Jahren sind beide im Bereich Wartung und Application Management tätig und haben schon viele gute und auch nicht so gute Beispiele für wartbare Software gesehen."
```
oder
```suggestion
  bio: "Anja Bethge und Thilo Lange sind Software Architekten am Standort Stralsund. Seit über fünf Jahren sind beide im Bereich Wartung und Applikationsmanagement tätig und haben schon viele gute und auch nicht so gute Beispiele für wartbare Software gesehen."
```

2020-11-16 15:15 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Die meisten Dokumente, die dem Wartungsteam bei der Transition und in der Wartung helfen, sind heutzutage „state-of-the-art“ in der professionellen Softwareentwicklung, so dass entweder gar kein oder
Könnt ihr hier etwas näher darauf eingehen, was mit State of the Art gemeint ist?

2020-11-16 15:15 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Falls während der Entwicklung die Anforderungen in einem Ticketsystem gepflegt wurden, ist es hilfreich, wenn diese zur Übergabe an das Wartungsteam in einem zentralen Dokument als Überblick zusammen
```suggestion
Falls während der Entwicklung die Anforderungen in einem Ticketsystem gepflegt wurden, ist es hilfreich, wenn diese Tickets zur Übergabe an das Wartungsteam in einem zentralen Dokument als Überblick zusammengefasst werden. 
```

2020-11-16 15:21 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +* Ein **Kontextdiagramm**, zur Darstellung der Schnittstellen bzw. Grenzen zu den Nutzer(gruppen) und externen Systemen.
```suggestion
* Ein **Kontextdiagramm**, zur Darstellung der Schnittstellen bzw. Grenzen zu den Personen(gruppen) und externen Systemen.
```

2020-11-16 15:22 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +# Entwicklerdokumentation
```suggestion
# Entwicklungsdokumentation
```

2020-11-16 15:22 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Zu den folgenden Themen sollte entsprechende Dokumentation vorhanden.
```suggestion
Zu den folgenden Themen sollte entsprechende Dokumentation vorhanden sein.
```

2020-11-16 15:24 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Im einfachsten Fall ist diese bereits fertig vorkonfiguriert als Docker-Image oder Virtuelle Maschine vorhanden, die die Entwickler nur noch kopieren und starten müssen.
```suggestion
Im einfachsten Fall ist diese bereits fertig vorkonfiguriert als Docker-Image oder Virtuelle Maschine vorhanden, die die Entwickelnden nur noch kopieren und starten müssen. 
```

2020-11-16 15:24 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Dazu gehören z.B. Coding Conventions, Guidelines, Styleguides, Umsetzungsrichtlinien für einzuhaltende Standards oder ähnliches.
Das ist so kein ganzer Satz, bitte formuliert das entsprechend um.

2020-11-16 15:25 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Unabhängig davon, wie viele Entwickler an der Software arbeiten, muss eine Versionsverwaltung wie z.B. Git eingesetzt werden.
```suggestion
Unabhängig davon, wie viele Entwickelnden an der Software arbeiten, muss eine Versionsverwaltung wie z.B. Git eingesetzt werden. 
```

2020-11-16 15:25 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Um sicherzustellen, dass alle entwickelten Features den gleichen Qualitätskriterien genügen, muss im Entwicklungsprojekt eine „Definition of Done“ definiert sein, die von allen Entwicklern eingehalte
```suggestion
Um sicherzustellen, dass alle entwickelten Features den gleichen Qualitätskriterien genügen, muss im Entwicklungsprojekt eine „Definition of Done“ definiert sein, die von allen Entwickelnden eingehalten wird. 
```

2020-11-16 15:26 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Der Reviewprozess sollte in diesem Fall zentral für alle Entwickler und Reviewer dokumentiert sein.
```suggestion
Der Reviewprozess sollte in diesem Fall zentral für alle Entwickelnden und Reviewenden dokumentiert sein. 
```

2020-11-16 15:26 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Durch die Verwendung einer Checkliste kann sichergestellt werden, dass jeder Reviewer ein Mindestsatz an Prüfungen durchführt.
```suggestion
Durch die Verwendung einer Checkliste kann sichergestellt werden, dass alle Reviewenden ein Mindestsatz an Prüfungen durchführt. 
```

2020-11-16 15:27 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Dort können die Entwickler den aktuellen Stand der Software einsehen und ihre Features außerhalb ihrer lokalen Entwicklungsumgebung testen.
```suggestion
Dort können die Entwickelnden den aktuellen Stand der Software einsehen und ihre Features außerhalb ihrer lokalen Entwicklungsumgebung testen.
```

2020-11-16 15:27 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Dazu gehören der Zweck der Umgebung, die Konfiguration, die zugehörigen URL(s) und ggf. die Zugänge.
Das ist so kein ganzer Satz, bitte formuliert das entsprechend um.

2020-11-16 15:27 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Dazu gehört z.B. die Liste der zu pflegenden Dokumente oder an wen und auf welchem Weg die Auslieferung auf Kundenseite zu erfolgen hat.
Das ist so kein ganzer Satz, bitte formuliert das entsprechend um.

2020-11-16 15:28 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Im nächsten Teil dieser Serien werfen wir einen Blick auf den Test von Softwareprojekten.
```suggestion
Im nächsten Teil dieser Serien werfen wir einen Blick auf das Testen von Softwareprojekten. 
```

2020-11-16 15:55 UTC, jo2 requested changes
Der Artikel liest sich schon sehr gut, ein paar Sachen habe ich noch angemerkt. Außerdem verwendet bitte " statt „ und “, da es sonst zu Encoding-Problemen kommen kann.

2020-11-17 09:33 UTC, anbeth commented
@jo2 Hallo Johannes, 
vielen Dank für Deine Rückmeldung. 
Ich habe Deine Anmerkungen umgesetzt und hoffe es passt so.
Viele Grüße
Anja

2020-11-17 09:34 UTC, anbeth commented on _data/authors.yml
> +  bio: "Thilo Lange ist Software Architect am Standort Stralsund"
Die Schreibweise wurde vereinheitlicht (deutsch).

2020-11-17 09:35 UTC, anbeth commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Die meisten Dokumente, die dem Wartungsteam bei der Transition und in der Wartung helfen, sind heutzutage „state-of-the-art“ in der professionellen Softwareentwicklung, so dass entweder gar kein oder
Ich habe den Satz umformuliert und hoffe es passt so besser.

2020-11-17 09:35 UTC, anbeth commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Dazu gehören z.B. Coding Conventions, Guidelines, Styleguides, Umsetzungsrichtlinien für einzuhaltende Standards oder ähnliches.
Ich habe den Satz umformuliert und hoffe es passt so besser.

2020-11-17 09:35 UTC, anbeth commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Dazu gehören der Zweck der Umgebung, die Konfiguration, die zugehörigen URL(s) und ggf. die Zugänge.
Ich habe den Satz umformuliert und hoffe es passt so besser.

2020-11-17 09:35 UTC, anbeth commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Dazu gehört z.B. die Liste der zu pflegenden Dokumente oder an wen und auf welchem Weg die Auslieferung auf Kundenseite zu erfolgen hat.
Ich habe den Satz umformuliert und hoffe es passt so besser.

2020-11-17 11:13 UTC, jo2 commented on _posts/2020-10-26-wartbarkeit-von-software-teil-1-dokumentation.md
> +Neben den technischen Aspekten muss die Anleitung auch die organisatorischen Aufgaben beinhalten, wie z.B. die Liste der zu pflegenden Dokumente oder an wen und auf welchem Weg die Auslieferung auf K
```suggestion
Neben den technischen Aspekten muss die Anleitung auch die organisatorischen Aufgaben wie z.B. die Liste der zu pflegenden Dokumente oder an wen und auf welchem Weg die Auslieferung auf Kundenseite zu erfolgen hat beinhalten.
```

2020-11-17 11:14 UTC, jo2 requested changes
Eine Sache ist noch drin, danach bin ich soweit durch.

2020-11-17 11:22 UTC, anbeth commented
Der Änderungsvorschlag wurde übernommen.

2020-11-17 11:51 UTC, jo2 submitted a review, later dismissed

2020-11-17 11:52 UTC, jo2 commented
@acetous rechtschreibtechnisch ist der Post soweit in Ordnung, machst du noch eine inhaltliche Review?

2020-12-14 10:57 UTC, anbeth commented
@acetous Hallo Sebastian, 
wie ist denn der Status vom inhaltlichen Review? Kannst Du abschätzen, bis wann Du uns eine Rückmeldung zum Artikel geben kannst?

2021-01-07 12:59 UTC, acetous approved these changes

2021-01-07 13:00 UTC, merged