commit des Blogeintrags Testautomatisierung in der Praxis
adessoAG/devblog pull request #185
Opened 2020-11-23 10:50 UTC by axelSchirmer

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, People, Inside adesso)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-11-23 11:17 UTC, jo2 commented on _data/authors.yml
> +  bio: "Axel Schirmer ist Software Engineer und seit dem 01.07.2019 bei adesso SE im öffentlichen Bereich (Public) tätig. Als Java Entwickler hat er bereits in der Versicherungsbranche, Telekommunika
```suggestion
  bio: "Axel Schirmer ist Software Engineer und seit dem 01.07.2019 bei adesso SE im öffentlichen Bereich (Public) tätig. Als Java Entwickler hat er bereits in der Versicherungsbranche, der Telekommunikation und im Bankenumfeld als Business Analyst gearbeitet, bevor er im öffentlichen Umfeld in einem von Cobol nach Java transformierten Projekt als Java Entwickler gearbeitet hat." 
```

2020-11-23 11:18 UTC, jo2 commented on _data/authors.yml
> +  bio: "Peter Urbanik ist Associate Consultant und im Juni 2018 bei der adesso SE als Trainee im Bereich Digitalisierung gestartet. Fachlich liegen seine Schwerpunkte in der Erhebung und Dokumentatio
```suggestion
  bio: "Peter Urbanik ist Associate Consultant und hat im Juni 2018 bei der adesso SE als Trainee im Bereich Digitalisierung gestartet. Fachlich liegen seine Schwerpunkte in der Erhebung und Dokumentation von komplexen Softwareanforderungen im Rahmen des agilen Requirements Engineerings und im Bereich des Projekt- und Testmanagements, das er in diversen Projekten und Workshops unterstützend einsetzen konnte."
```

2020-11-23 11:22 UTC, jo2 commented on _data/authors.yml
> +  bio: "Tony Eggert ist Senior Consultant (DvD) und seit Mai 2019 bei adesso tätig. Im Umfeld der Beratung ist er bereits in verschiedenen Rollen (Requirement Engineering, Business Analyst, Product O
```suggestion
  bio: "Tony Eggert ist Senior Consultant (DvD) und seit Mai 2019 bei adesso tätig. Im Umfeld der Beratung ist er bereits in verschiedenen Rollen u.a. als Folge seines Studiums im Bereich der Volkswirtschaftslehre bei namhaften Finanzdienstleistern tätig gewesen. Er war dort beispielsweise als Requirements Engineer, Business Analyst, Product Owner, Testanalyst oder Projektkoordinator tätig . Darüber hinaus beschäftigt er sich intensiv mit den Aspekten des Team-Coaching und agilen Leadership. "
```

2020-11-23 12:30 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +categories: [Branchen]
```suggestion
categories: [Inside adesso]             
```
Die Kategorie Branchen existiert nicht mehr, sie wurde umbenannt in Inside adesso

2020-11-23 12:31 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Wie bereits in unserem **letzten Blogbeitrag [LINK](https://www.adesso.de/de/news/blog/testautomatisierung-in-der-praxis-erfahrungen-mit-soapui-im-public-umfeld.jsp)** **ANGETEASERT**, handelt es sic
```suggestion
Wie bereits in unserem [letzten Blogbeitrag](https://www.adesso.de/de/news/blog/testautomatisierung-in-der-praxis-erfahrungen-mit-soapui-im-public-umfeld.jsp) angeteasert, handelt es sich hierbei um die Fortsetzung des gleichnamigen Blogbeitrages. Die beiden Blogbeiträge bilden eine zusammenhängende Serie, jedoch sind die Themeninhalte voneinander abgetrennt. Daher ist auch eine Einzelbetrachtung der angesprochenen Themenbereiche durchaus sinnvoll.   
```

2020-11-23 12:32 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Im **ZWEITEN TEIL** des Blogs über Testautomatisierung widmen wir uns der Automation von Oberflächentests, den sogenannten GUI- bzw. UI-Tests. Wie bereits in **Teil 1** dargelegt, bietet die Testauto
Der Satz, der mit "Trotz des hohen..." anfängt ist sehr lang, unterteilt ihn bitte in mehrere Sätze. Außerdem gehört er mMn. eher ins Fazit als in die Einleitung.

2020-11-23 12:36 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Die Anwendungen zur GUI-Automatisierung basieren primär auf Internet-/Webtechnologien und sind die Grundlage für zahlreiche Testautomatisierungstechnologien wie Webdriver IO, Python, Tosca, Selenium
```suggestion
Die Anwendungen zur GUI-Automatisierung basieren primär auf Internet-/Webtechnologien und sind die Grundlage für zahlreiche Testautomatisierungstechnologien wie Webdriver IO, Python, Tosca, Selenium oder Ranorex. Diese können bei Bedarf mit anderen Tools zur (Schnittstellen-)Testautomatisierung, in unserem Fall SOAP UI Pro, kombiniert werden, indem bspw. zwischen den Schnittstellen speziell angepasste Skripte ausgetauscht werden. Die Einbindung und Ausführung der Testskripte wurde entsprechend übergreifend durch SOAP gesteuert/orchestriert und bietet somit u. a. die Möglichkeit, den Testablauf an einem beliebigen Punkt der automatisierten GUI-Ausführung zu starten. Wir haben uns an dieser Stelle für das Open Source Framework Webdriver IO entschieden, welches ausschließlich den Oberflächenanteil abdeckt und ein Node.JS basiertes Testframework abbildet. Somit ist er als Nachfolger von Selenium zu sehen. Doch was kann **Webdriver IO** eigentlich sonst noch? 
```

"und ein Node.JS basiertes Testframework abbildet" -> Abbildet passt hier nicht als Verb, vielleicht ist?

Warum ist Webdriver IO erst im letzten Absatz hervorgehoben? Es sollte entweder bei der ersten Erwähnung oder garnicht hervorgehoben werden. Wenn eine Hervorhebung erfolgt, macht das bitte in Form eines Links auf die Seite von Webdriver.

2020-11-23 12:38 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Mit Hilfe von Webdriver IO lassen sich während des Testbetriebes bspw. eingelesene Testdaten in die zu testende Weboberfläche übertragen. Dahinter verbirgt sich der Sinn, dass die Oberfläche automati
```suggestion
Mit Hilfe von Webdriver IO lassen sich während des Testbetriebes bspw. eingelesene Testdaten in die zu testende Weboberfläche übertragen. Dahinter verbirgt sich der Sinn, dass die Oberfläche automatisch mit Daten befüllt wird, die zum einen an das Backend gesendet und von ggf. Web-/MicroServices verarbeitet werden können, oder Feldvalidierungen getestet werden können. Zudem gilt seine Adaptierbarkeit als ein weiterer großer Vorteil, da so die Möglichkeiten geschaffen werden, andere Werkzeuge in den Testbetrieb einzugliedern. In diesem Zusammenhang sei hier einmal, für tiefer Interessierte, auf die ausführliche und sehr hilfreiche [Installationsbeschreibung der Webdriver IO](https://webdriver.io/docs/gettingstarted.html) Projektseite hingewiesen.
```

"zum einen" im zweiten Satz erfordert ein "zum anderen". Passt diesen Satz bitte entsrechend an.

2020-11-23 12:43 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Insofern konnten die automatisierten GUI-Tests, die in unserem Falle mit Webdriver IO entwickelt wurden, als zusätzliche Komponente unseres Regressionstestportfolios betrachtet werden. Die dafür benö
```suggestion
Insofern konnten die automatisierten GUI-Tests, die in unserem Falle mit Webdriver IO entwickelt wurden, als zusätzliche Komponente unseres Regressionstestportfolios betrachtet werden. Die dafür benötigten Testdaten sind dabei bspw. entweder in einer Datenbank gespeichert oder, wie in unserem Fall, innerhalb einer organisierten und umfangreichen Excelliste hinterlegt. Diese klassische Liste enthält alle Daten und Reglements, die für die zahlreichen fachlichen und technischen Anforderungen bzw. Testszenarien relevant sind. Die Zusammenstellung der Daten und die Festlegung der Regelparameter hat mit Abstand die meisten Implementierungsaufwände mit sich gebracht. Die nutzerfreundliche Aufbereitung/Verwaltung der hinterlegten Regressionstestszenarien ist ein weiteres Problem, das mit der Kombination so vieler Testszenarien einhergeht. In unserem Fall sind dies gerade noch überschaubare 354 Testszenarien, jedoch kann die Anzahl an Tests je nach Komplexitätsgrad der zu testenden Anwendungen/Systeme exponentiell ansteigen. Um die Flut an Regeln und geforderten Testabdeckungen bedienen zu können, bieten speziell angepasste (VBA-)Makros eine wertvolle Hilfestellung. Dies haben wir bereits umfassend nutzen dürfen, mit dem Ergebnis, dass Endanwendende bzw. Sachbearbeitende eigenständig innerhalb eines vorgegebenen Testframeworks individuelle Szenarien erstellen können, die innerhalb der eingefassten Regelsysteme agieren. 
```

2020-11-23 12:50 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Insofern konnte hier zwar ein Teil der elementar benötigten Testaufwände verschoben werden, sodass sich die Testautomatisierer weiteren spezielleren Testszenarien widmen konnten. In diesem Zuge stieg
Das "zwar" impliziert, dass noch ein "aber" kommt, ihr müsstet den Satz umformulieren, am besten streicht ihr das "zwar".

Sind Testautomatisierer die Leute die automatisierte Tests schreiben? Bitte formuliert das entweder um oder gebt eine kurze Erklärung zu dem Begriff an. Außerdem müsstet ihr hier gendern.

Streicht bitte das "immer weiter" im zweiten Satz oder schreibt es ans Satzende.

Ihr geht hier auf den Komplexitätsgrad ein, ist das der Komplexitätsgrad der Anwendung, den ihr oben angesprochen habt? Wenn ja, in wie weit beeinflussen die Tests die Komplexität der Anwendung? Die Anwendungslogik sollte doch unabhängig von den Tests sein, oder nicht?

2020-11-23 12:51 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Cucumber ist natürlich keine Gurke, sondern ein Behavior-Driven-Development-Werkzeug zur textuellen Spezifikation von Anforderungen. Bezogen auf unsere Projektsituation bietet es somit die Option, de
```suggestion
Cucumber ist natürlich keine Gurke, sondern ein Behavior-Driven-Development-Werkzeug zur textuellen Spezifikation von Anforderungen. Bezogen auf unsere Projektsituation bietet es somit die Option, den Fachbereich des Kunden um eine textuelle Testanforderungsunterstützung in natürlicher Sprache zu erweitern. Komplexe Testfälle können nach diesem Prinzip in natürlicher Sprache präzise beschrieben werden - „Wenn Fall x eintritt dann erwarte y“. 
```

2020-11-23 12:52 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Die so formulierten Testfälle können fortan im Hintergrund mit JavaScript ausprogrammiert werden. Mit diesem Bestreben entsteht – im besten Fall – eine Symbiose zwischen Fachbereich und der IT, die u
```suggestion
Die so formulierten Testfälle können fortan im Hintergrund mit JavaScript ausprogrammiert werden. Mit diesem Bestreben entsteht – im besten Fall – eine Symbiose zwischen Fachbereich und der IT, die unterschiedlich formulierte Abstraktionen (Entwicklungs-/ Schnittstellen-/ Oberflächentests) zusammenführt und erfahrbar macht. Somit entfällt das Problem, dass auf der Entwicklungsseite Tests granular, auf einzelne Werte fokussiert geschrieben werden, die für nicht-Entwickelnde kryptisch erscheinen mögen und für diese Gruppe folglich nicht transparent und ohne Weiteres editierbar sind.
```

Ihr schreibt, dass Abstraktionen (Tests) erfahrbar gemacht werden. Was genau soll das bedeuten?

2020-11-23 12:53 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Aus unserer Sicht erscheint es ratsam, diese Abwägung projektspezifisch zu treffen, da eine Übergabe eine enorme Einarbeitung auch abseits der projektspezifischen Charakteristika bedeutet (bspw. beim
Ihr schreibt hier von einer Abwägung und einer Übergabe, bisher fanden keine Entscheidungen statt und von etwas, das zu übergeben sein könnte, war auch noch nicht die Rede. Dieser Satz passt vom Zusammenhang her nicht an diese Stelle, bitte entfernt ihn oder formuliert die Sätze davor so um, dass es einen inhaltlichen Zusammenhang gibt.

2020-11-23 12:54 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Für die zukünftige Weiterentwicklung unserer Testautomatisierungsbestrebungen schwebt uns die Integration von **Chai** vor, denn dies würde es uns erlauben unsere 354 Testszenarien in Reports auswert
Entweder muss der letzte Satz zu einer Frage umformuliert werden, oder das "?" muss durch einen "." ersetzt werden.

2020-11-23 12:54 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Chai bietet die Möglichkeit, eine Auswertung zu den durchgelaufenen Tests zu erstellen. Daher können nach allen Testläufen oder selbst innerhalb einzelner Läufe entsprechend aussagekräftige Reports e
```suggestion
Chai bietet die Möglichkeit, eine Auswertung zu den durchgelaufenen Tests zu erstellen. Daher können nach allen Testläufen oder selbst innerhalb einzelner Läufe entsprechend aussagekräftige Reports erstellt werden, die im Hinblick auf diverse Parameter, bspw. der Gesamtanzahl von durchgeführten Tests und der Teilmenge von positiven und negativen Testergebnissen, Basis-Informationen generieren.
```

2020-11-23 12:55 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Insgesamt erscheint (in einer konservativen Schätzung) eine **Zeitersparnis von 35%** durch den Einsatz unserer Automatisierungstätigkeiten als Durchschnittswert in unseren Projekten als realistisch:
```suggestion
Insgesamt erscheint nach einer konservativen Schätzung eine **Zeitersparnis von 35%** durch den Einsatz unserer Automatisierungstätigkeiten als Durchschnittswert in unseren Projekten als realistisch. Darin sind bereits der Aufwand zur intensiven Einarbeitung in SoapUI, in die anderen angesprochenen Tools und die Gespräche im Zusammenhang mit der “Überzeugungsarbeit” enthalten. Nebenbei führten die bereitgestellten Testdatenskripte zu einer wichtigen Verkürzung des Testzyklus und unterstützen agile Methoden, da einzelne zeitkritisch geforderte Testergebnisse fokussiert gewonnen und bereitgestellt werden können. Als Kunden-Feedback häuften sich die Wertschätzungen der einheitlichen und nachvollziehbaren Dokumentationen. 
```

2020-11-23 13:01 UTC, jo2 requested changes
Einige Änderungen sind noch erforderlich, die entsprechenden Stellen habe ich markiert. Außerdem:
* Bitte schreibt nur einen Satz pro Zeile, das vereinfacht den Reviewprozess erheblich. Ihr habt zudem momentan sehr lange Absätze. Ein Absatz entsteht dadurch, dass zwei Leerzeilen hintereinander stehen. Bitte macht mehr Absätze, das erleichtert das Lesen deutlich.
* Bitte formuliert einen Teaser für euren Blogpost.
* Bitte verwendet " statt „ und “, sonst kann es zu Formatierungsproblemen kommen.
* Alles nach Z. 43 muss gelöscht werden, der Blogpost entspricht sonst nicht dem gültigen Markdown-Format, das der adesso-Devblog verarbeiten kann.
* Überdenkt bitte einmal die Struktur eurer Überschriften. Ihr habt moemntan ein Kapitel mit einem Unterkapitel. Darin ist ein Unterunterkapitel. Das Fazit ist mit vier "#" markiert, eine solche Überschrift gibt es nicht.
* Bitte achtet auf eine einheitliche Schreibweise von Soap UI.
* Dem Artikel fehlt ein erkennbarer roter Faden. Es scheint ja grundlegend ein Problem mit GUI-Tests gegeben zu haben. Nutzt das doch als Motivation im Teaser und in der Einleitung. Danach könntet ihr dann darauf eingehen, was eure Herangehensweise war und warum ihr euch dafür entschieden habt. Danach könntet ihr beschreiben, was ihr in dem Zusammenhang umsetzen/implementieren musstet. Den Artikel abschließen könntet ihr dann mit einem Fazit, in dem ihr über die tatsächlich erreichte Zeitersparnis und die Akzeptanz der Entwicklungsteammitglieder berichtet, und einem Ausblick, bspw. auf die Last- und Performance-Tests.

2020-11-27 09:31 UTC, jo2 commented on _data/authors.yml
> +  bio: "Tony Eggert ist Senior Consultant und seit Mai 2019 bei adesso tätig. Im Umfeld der Beratung ist er bereits in verschiedenen Rollen u.a. als Folge seines Studiums im Bereich der Volkswirtscha
```suggestion
  bio: "Tony Eggert ist Senior Consultant und seit Mai 2019 bei adesso tätig. Im Umfeld der Beratung ist er bereits in verschiedenen Rollen, u.a. als Folge seines Studiums im Bereich der Volkswirtschaftslehre, bei namhaften Finanzdienstleistern tätig gewesen. Er war dort beispielsweise als Requirements Engineer, Business Analyst, Product Owner, Testanalyst oder Projektkoordinator tätig . Darüber hinaus beschäftigt er sich intensiv mit den Aspekten im Bereich Team-Coaching und agilen Leadership."
```

2020-11-27 09:39 UTC, jo2 commented
@axelSchirmer bitte ändert den Blogpost ab, sodass ein Satz in einer eigenen Zeile steht. Es ist ansonsten sehr anstrengend, Verbesserungsvorschläge anzumerken und die Änderungshistorie nachzuverfolgen.

2020-12-01 09:00 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Wie bereits in **Teil 1** dargelegt, bietet die Testautomatisierung im Kontext der Qualitätssicherung einen deutlichen Mehrwert zur Steigerung der Softwarequalität.
```suggestion
Wie bereits in **Teil 1** dargelegt, bietet die Testautomatisierung im Kontext der Qualitätssicherung großes Potential zur Steigerung der Softwarequalität. 
```

2020-12-01 09:01 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Trotz des hohen initialen Ressourcenaufwandes, den hohen Anforderungen an einen sensiblen Hochsicherheitsbereich und der Erstellung der technischen Infrastruktur, überwiegt die im Betrieb enorm hohe
```suggestion
Trotz des hohen initialen Ressourcenaufwandes, den hohen Anforderungen an einen sensiblen Hochsicherheitsbereich und der Erstellung der technischen Infrastruktur überwiegt die im Betrieb enorm hohe Zeitersparnis und Motivation (durch Auflösung von sich wiederholenden und monotonen Tätigkeiten), sodass sich ein Return-of-Investment (ROI) eingestellt hat. 
```

2020-12-01 09:02 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Aufgrund der ersten Erfolge der automatisierten Schnittstellen-Regressionstests mit Hilfe von SoapUI Pro, wollen wir das Wissen nutzen, um diesen Ansatz bei GUI-Regressionstests weiter zu verfolgen.
```suggestion
Aufgrund der ersten Erfolge der automatisierten Schnittstellen-Regressionstests mit Hilfe von SoapUI Pro, wollen wir das dort gewonnene Wissen nutzen, um diesen Ansatz bei GUI-Regressionstests weiter zu verfolgen. 
```

2020-12-01 09:05 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Die Anwendungen zur GUI-Automatisierung basieren primär auf Internet-/Webtechnologien und sind die Grundlage für zahlreiche Testautomatisierungstechnologien wie *Webdriver IO*, Python, Tosca, Seleniu
Gibt es einen bestimmten Grund, das sonst zur Hervorhebung fett gedruckt (\*\*Text**) wird und hier kursiv gedruckt (\*Text*) wird?

2020-12-01 09:12 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Die Anwendungen zur GUI-Automatisierung basieren primär auf Internet-/Webtechnologien und sind die Grundlage für zahlreiche Testautomatisierungstechnologien wie *Webdriver IO*, Python, Tosca, Seleniu
```suggestion
Die Anwendungen zur GUI-Automatisierung basieren primär auf Internet-/Webtechnologien und sind die Grundlage für zahlreiche Testautomatisierungstechnologien wie **Webdriver IO**, Python, Tosca, Selenium oder Ranorex. 
```

2020-12-01 09:16 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Dahinter verbirgt sich der Sinn, dass die Oberfläche automatisch mit Daten befüllt wird, die an das Backend gesendet und von ggf. Web-/MicroServices verarbeitet werden können, oder Feldvalidierungen
```suggestion
Dahinter verbirgt sich der Sinn, dass die Oberfläche automatisch mit Daten befüllt wird, die an das Backend gesendet und von Web-/MicroServices verarbeitet werden können, oder dass Feldvalidierungen getestet werden kann. 
```

2020-12-01 09:16 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Zudem gilt seine Adaptierbarkeit als ein weiterer großer Vorteil, da so die Möglichkeiten geschaffen werden, andere Werkzeuge in den Testbetrieb einzugliedern.
```suggestion
Zudem gilt seine Adaptierbarkeit als ein weiterer großer Vorteil, da so Möglichkeiten geschaffen werden, andere Werkzeuge in den Testbetrieb einzugliedern. 
```

2020-12-01 09:18 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Hier liegt auch ein weiteres Problem, das mit der Kombination so vieler Testszenarien einhergeht, die nutzerfreundliche Aufbereitung/Verwaltung der hinterlegten Regressionstestszenarien.
```suggestion
Hier liegt auch ein weiteres Problem, das mit der Kombination vieler Testszenarien einhergeht, die nutzerfreundliche Aufbereitung/Verwaltung der hinterlegten Regressionstestszenarien. 
```

2020-12-01 09:19 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +In unserem Fall sind dies gerade noch überschaubare 354 Testszenarien, jedoch kann die Anzahl (je nach Komplexitätsgrad der zu testenden Anwendungen/Systeme) exponentiell ansteigen.
```suggestion
In unserem Fall sind dies gerade noch überschaubare 354 Testszenarien, jedoch kann die Anzahl, je nach Komplexitätsgrad der zu testenden Anwendungen/Systeme, exponentiell ansteigen. 
```

2020-12-01 09:21 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Dies haben wir bereits umfassend nutzen dürfen, mit dem Ergebnis, dass es den Endanwendern bzw. Sachbearbeitern eigenständig ermöglicht, innerhalb eines vorgegebenen Testframeworks individuelle Szena
```suggestion
Dies haben wir bereits umfassend nutzen dürfen, mit dem Ergebnis, dass diese Makros es den Endusern bzw. Sachbearbeitenden möglich machen, innerhalb eines vorgegebenen Testframeworks eigenständig individuelle Szenarien zu erstellen, die innerhalb der eingefassten Regelsysteme agieren. 
```

2020-12-01 09:22 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Insofern konnte hier ein Teil der elementar benötigten Testaufwände verschoben werden, sodass sich die Testautomatisierer weiteren spezielleren Testszenarien widmen konnten.
```suggestion
Insofern konnte hier ein Teil der elementar benötigten Testaufwände verschoben werden, sodass sich die Tetentwicklung weiteren spezielleren Testszenarien widmen konnten. 
```

2020-12-01 09:24 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Komplexe Testfälle können nach diesem Prinzip in natürlicher Sprache präzise beschrieben werden - „Wenn Fall x eintritt dann erwarte y“.
```suggestion
Komplexe Testfälle können nach diesem Prinzip in natürlicher Sprache präzise beschrieben werden - "Wenn Fall x eintritt dann erwarte y". 
```

2020-12-01 09:24 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Mit diesem Bestreben entsteht – im besten Fall – eine Symbiose zwischen Fachbereich und der IT, die unterschiedlich formulierte Abstraktionen (Entwicklungs-/ Schnittstellen-/ Oberflächentests) zusamm
```suggestion
Mit diesem Bestreben entsteht – im besten Fall – eine Symbiose zwischen dem Fachbereich und der IT, die unterschiedlich formulierte Abstraktionen (Entwicklungs-/ Schnittstellen-/ Oberflächentests) zusammenführt und erfahrbar macht. 
```

2020-12-01 09:26 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Somit entfällt das Problem, dass auf der Entwicklungsseite Tests granular, auf einzelne Werte fokussiert geschrieben werden, die für nicht-Entwickelnde kryptisch erscheinen mögen und für diese Gruppe
```suggestion
Somit entfällt das Problem, dass auf der Entwicklungsseite Tests granular, auf einzelne Werte fokussiert geschrieben werden, die für nicht-Entwickelnde kryptisch erscheinen mögen und für diese Gruppe folglich nicht transparent und somit nicht ohne Weiteres editierbar sind.
```

2020-12-01 09:30 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Für die zukünftige Weiterentwicklung unserer Testautomatisierungsbestrebungen schwebt uns die Integration von **Chai** vor, denn dies würde es uns erlauben unsere 354 Testszenarien in Reports auswert
```suggestion
Für die zukünftige Weiterentwicklung unserer Testautomatisierungsbestrebungen schwebt uns die Integration von **Chai** vor, denn dies würde es uns erlauben, unsere 354 Testszenarien in Reports auswerten zu lassen. 
```

2020-12-01 09:31 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Daher kommt hier die Frage auf, ob ein möglicher Implementierungsaufwand im Verhältnis zum Nutzen steht?
```suggestion
Daher kommt hier die Frage auf, ob ein möglicher Implementierungsaufwand im Verhältnis zum Nutzen steht.
```

2020-12-01 09:33 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Aus unserer Sicht erscheint es ratsam, diese Abwägung projektspezifisch zu treffen, da eine mögliche Übergabe des Projektes eine enorme Einarbeitung auch abseits der projektspezifischen Charakteristi
```suggestion
Aus unserer Sicht erscheint es ratsam, die Entscheidung, wie tiefgehend GUI-Testautomatisierung erfolgen soll, projektspezifisch zu treffen, da eine mögliche Übergabe des Projektes eine enorme Einarbeitung auch abseits der projektspezifischen Charakteristika bedeutet (bspw. beim Umgang mit den verschiedenen Tools) und die Tools auf eine teils nicht zu unterschätzende, stetige Wartungsleistung angewiesen sind.
```

2020-12-01 09:35 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Daher können nach allen Testläufen oder selbst innerhalb einzelner Läufe entsprechend aussagekräftige Reports erstellt werden, die im Hinblick auf diverse Parameter, bspw. der Gesamtanzahl von durchg
```suggestion
Es können also nach allen Testläufen oder selbst innerhalb einzelner Läufe entsprechend aussagekräftige Reports erstellt werden, die im Hinblick auf diverse Parameter, bspw. der Gesamtanzahl von durchgeführten Tests und der Teilmenge von positiven und negativen Testergebnissen, Basis-Informationen generieren.
```

2020-12-01 09:35 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Im **ZWEITEN TEIL** des Blogs über Testautomatisierung widmen wir uns der Automation von Oberflächentests, den sogenannten GUI- bzw. UI-Tests.
```suggestion
Im **Teil 2** des Blogs über Testautomatisierung widmen wir uns der Automation von Oberflächentests, den sogenannten GUI- bzw. UI-Tests. 
```

2020-12-01 09:38 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Dies führte zu enormen manuellen Aufwänden und einer hohen Frustration, da sich monotone Tätigkeiten häuften.
```suggestion
Dies verursachte enormen manuellen Aufwand und eine hohen Frustration, da sich monotone Tätigkeiten häuften. 
```

2020-12-01 09:39 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Nach ersten Erfolgen mit Teilautomatisierungen innerhalb der GUI, stellte sich eine erwartete Zeitersparnis anfangs jedoch nicht ein, da ständige Zertifikats- und Credentialwechsel mit begrenzter Gül
```suggestion
Nach ersten Erfolgen mit Teilautomatisierungen innerhalb der GUI stellte sich eine erwartete Zeitersparnis anfangs jedoch nicht ein, da ständige Zertifikats- und Credentialswechsel mit begrenzter Gültigkeitsdauer auf den unterschiedlichen Testumgebungen auch für "stresserprobte" Consultants eine ambitionierte Aufgabe darstellten. 
```

2020-12-01 09:41 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Darin sind bereits der Aufwand zur intensiven Einarbeitung in SoapUI, in die anderen angesprochenen Tools und die Gespräche im Zusammenhang mit der “Überzeugungsarbeit” enthalten.
```suggestion
Darin sind bereits der Aufwand zur intensiven Einarbeitung in SoapUI, in die anderen angesprochenen Tools und die Gespräche im Zusammenhang mit der "Überzeugungsarbeit" enthalten. 
```

2020-12-01 09:42 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +Als Kunden-Feedback häuften sich die Wertschätzungen der einheitlichen und nachvollziehbaren Dokumentationen.
```suggestion
Als Kunden-Feedback häufte sich die Wertschätzungen der einheitlichen und nachvollziehbaren Dokumentationen. 
```

2020-12-01 09:57 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +
```suggestion

Als Berater für den Aufbau eines geeigneten Testumfeldes im Public Umfeld, wollen wir Euch in unserem mehrteiligen Erfahrungsbericht einladen, die verschiedenen Höhen und Tiefen in der Umsetzung zu begleiten.
In diesem Teil geht es weiter mit der Testautomatisierung, speziell im Bereich des GUI-Tests.

```

2020-12-01 09:59 UTC, jo2 submitted a review, later dismissed

2020-12-01 10:00 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +date:   2020-11-71 15:00
```suggestion
date:   2020-11-30 15:00                    
```

2020-12-01 10:03 UTC, jo2 commented
@acetous rechtschreibtechnisch passt es soweit. Guckst du dir das noch an.

2020-12-01 10:07 UTC, jo2 submitted a review, later dismissed

2020-12-01 10:26 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +#Testautomatisierung in der Praxis
```suggestion
# Testautomatisierung in der Praxis
```

2020-12-01 10:26 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +##Erfahrungen mit GUI-Oberflächentests im Public Umfeld
```suggestion
## Erfahrungen mit GUI-Oberflächentests im Public Umfeld
```

2020-12-01 10:27 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +###Testautomatisierung der GUI bzw. UI
```suggestion
### Testautomatisierung der GUI bzw. UI
```

2020-12-01 10:27 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +##Unser Fazit
```suggestion
## Unser Fazit
```

2020-12-01 10:30 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +## Erfahrungen mit GUI-Oberflächentests im Public Umfeld
```suggestion
# Erfahrungen mit GUI-Oberflächentests im Public Umfeld
```

2020-12-01 10:30 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +### Testautomatisierung der GUI bzw. UI
```suggestion
## Testautomatisierung der GUI bzw. UI
```

2020-12-01 10:30 UTC, jo2 commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +## Unser Fazit
```suggestion
# Unser Fazit
```

2020-12-03 09:33 UTC, acetous commented on _posts/2020-11-17-Testautomatisierung-in-der-Praxis.md
> +categories: [Branchen]
Branchen ist korrekt.

2020-12-03 09:36 UTC, acetous approved these changes

2020-12-03 09:36 UTC, merged