Blog-Beitrag: Authentifizierung über öffentliche Schlüssel mit Apache MINA
adessoAG/devblog pull request #186
Opened 2020-11-23 12:37 UTC by IvanKablar

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [X] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [X] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [X] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [X] "title" vergeben
    - [X] "author" angegeben
    - [X] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, People, Inside adesso)
    - [X] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [X] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [X] Rechtschreibung korrigiert
  - [X] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [X] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [X] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [X] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [X] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-11-24 09:51 UTC, jo2 commented
@IvanKablar kommen hier noch mehrere Änderungen? Dann markiere den PR bitte als Draft. Ansonsten gib mir bitte kurz Bescheid, dann kann ich mit der Review anfangen.

2020-11-24 10:59 UTC, IvanKablar commented
Hallo Johannes,

danke für Deine Nachricht.

Das war die letzte Änderung. 

Viele Grüße

Ivan

2020-11-27 08:26 UTC, jo2 commented
@IvanKablar danke, guck ich mir an

2020-11-27 09:23 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +In der Fortsetzung meines Blogs-Beitrags werden wir die Authentifizierung über öffentliche Schlüssel mit dem Apache MINA Framework untersuchen.
Kannst du deinen Blog-Beitrag hier verlinken?

2020-11-27 09:24 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Die asymmetrische Verschlüsselung verwendet zwei sich ergänzende Schlüssel: den öffentlichen Schlüssel für das Verschlüsseln der Nachricht und den privaten Schlüssel für das Entschlüsselnd der Nachri
```suggestion
Die asymmetrische Verschlüsselung verwendet zwei sich ergänzende Schlüssel: den öffentlichen Schlüssel für das Verschlüsseln und den privaten Schlüssel für das Entschlüsseln der Nachricht. 
```

2020-11-27 09:24 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Wie die Bezeichnung bereits darauf hindeutet, kann der öffentliche Schlüssel öffentlich zugänglich gemacht werden.
```suggestion
Wie der Name schon sagt, kann der öffentliche Schlüssel öffentlich zugänglich gemacht werden. 
```

2020-11-27 09:25 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Ihr könnt ihn unter [MINA-sftp-pub-auth](https://github.com/IvanKablar/MINA-sftp-pub-auth) herunterladen.
Der Link funktioniert nicht, bitte überprüfe das mal.

2020-11-27 09:25 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Mit dem öffentlichen Schlüssel der Datei wird der sogenannte „Fingerprint“, ein MD5-Hash Wert, berechnet und dem Client beim Anmeldeversuch zugesendet.
Warum MD5, das ist doch schon kompromittiert?

2020-11-27 09:29 UTC, jo2 requested changes
Der Artikel liest sich schon recht gut. Ein paar Sachen habe ich aber noch:
* verwende bitte " statt „ und “
* achte beim Code bitte auf korrekte Einrückung
* zum Verständnis: Der gespeicherte öffentliche Schlüssel des Clients wird mit dem erhaltenen verglichen. Letzerer kann doch von jedem gekommen sein, da der Schlüssel öffentlich ist. In wie weit wird im Verfahren sichergestellt, dass der Absender des Public Key auch besitzer des Private Key ist? Kannst du in deinem Artikel das noch näher erläutern?

2020-11-27 11:32 UTC, IvanKablar commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Mit dem öffentlichen Schlüssel der Datei wird der sogenannte „Fingerprint“, ein MD5-Hash Wert, berechnet und dem Client beim Anmeldeversuch zugesendet.
Der Fingerprint wird als MD5-Hash gezeigt. Was meinst Du mit kompromiettiert?

2020-11-27 11:33 UTC, IvanKablar commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Ihr könnt ihn unter [MINA-sftp-pub-auth](https://github.com/IvanKablar/MINA-sftp-pub-auth) herunterladen.
Der Link sollte jetzt funktionieren.

2020-11-29 13:43 UTC, IvanKablar commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +In der Fortsetzung meines Blogs-Beitrags werden wir die Authentifizierung über öffentliche Schlüssel mit dem Apache MINA Framework untersuchen.
@jo2 Ich habe den Beitrag verlinkt, aber das ist dann nicht mehr in Einklang mit den "Best-Practices".

2020-11-29 13:44 UTC, IvanKablar commented
@jo2 Ich habe den Text korrigiert und die Beschreibung ergänzt. Kannst Du bitte nochmal drüber schauen?

2020-11-29 22:44 UTC, IvanKablar commented
@jo2 Ich habe ein neues Kapitel "Digitale Signatur" erstellt.

2020-11-30 12:21 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Die asymmetrische Verschlüsselung verwendet zwei sich ergänzende Schlüssel: den öffentlichen Schlüssel für das Verschlüsseln der Nachricht und den privaten Schlüssel für das Entschlüsseln der Nachric
```suggestion
Die asymmetrische Verschlüsselung verwendet zwei sich ergänzende Schlüssel: den öffentlichen Schlüssel für das Verschlüsseln und den privaten Schlüssel für das Entschlüsseln der Nachricht. 
```

2020-11-30 12:23 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Während der Prozedur generieren der Client und der Server Schlüssel, die für die Verschlüsselung der Kommunikation verwendet werden.
```suggestion
Während der Prozedur generieren der Client und der Server Schlüsselteile, die, zusammengesetzt, einen symmetrischen Schlüssel für die Verschlüssellung der Kommunikation ergeben. 
```

2020-11-30 12:29 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +In der Anwendung wird die zu signierende Nachricht zunächst zu einem eindeutigen nicht umkehrbarer Hashwert kodiert und anschließend mit dem privaten Schlüssel verschlüsselt.
```suggestion
In der Anwendung wird aus der zu signierenden Nachricht zunächst zu ein gehasht und anschließend mit dem privaten Schlüssel verschlüsselt.
Das Hashen macht aus einer Nachricht flexibeler Länge eine Nachricht fester Länge und es ist nicht möglich, aus dem Hashwert die ursprüngliche Nachricht zu berechnen.
```

2020-11-30 12:31 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Der Prüfer erstellt einen Hashwert aus der zu signierenenden Nachricht.
```suggestion
Der Server erstellt einen Hashwert aus der zu signierenenden Nachricht. 
```

2020-11-30 12:32 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Stimmen beide Hashwerte überein, ist die Signatur und damit die Identität des Unterzeichners und die Integrität der Nachricht bestätigt.
```suggestion
Stimmen beide Hashwerte überein, ist die Signatur und damit die Identität des Clients und die Integrität der Nachricht bestätigt.
```

2020-11-30 12:34 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Nach einer erfolgreichen Authentifizierung ermöglicht die Klasse "SftpSubsystemFactory” den Zugriff auf das Dateisystem des Servers.
```suggestion
Nach einer erfolgreichen Authentifizierung ermöglicht die Klasse "SftpSubsystemFactory" den Zugriff auf das Dateisystem des Servers. 
```

2020-11-30 12:43 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Als Nächstes versuchen wir, uns mit dem privaten Schlüssel am Server zu authentifizieren:
Für den folgenden Absatz: eigentlich authentifiziert sich der Client ja, indem er seinen öffentlichen Schlüssel signiert und Schlüssel und Signatur an den Server schickt. Der Server vergleicht dann den ankommenden öffentlichen Schlüssel mit dem hinterlegten öffentlichen Schlüssel. Stimmen beide überein, überprüft der Server die Signatur (mit privatem Schlüssel des Clients verschlüsselter Hashwert des öffentlichen Schlüssels), indem er den Hashwert bildet, die Signatur mit dem öffentlichen Schlüssel des Clients entschlüsselt und den Hashwert mit dem entschlüsselten vergleicht. Richtig?

Dann müssten in diesem Absatz ein paar Änderungen vorgenommen werden:
* Z. 116: privaten Schlüssel -> öffentlichen Schlüssel
* Z. 124: Außerdem überprüft das Framework die mit Hilfe des privaten Schlüssels erstellte Signatur.

Vielleicht wäre auch noch eine kleine Grafik, bspw. ein Ablaufdiagramm, hilfreich.

2020-11-30 12:44 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Mit der Bereitstellung von Interfaces für die Authentifizierung durch das Framwork wird dem Entwickler die Überprüfung von zusätzlichen Authentifizierungskriterien ermöglicht, darunter auch der Vergl
```suggestion
Mit der Bereitstellung von Interfaces für die Authentifizierung durch das Framwork wird bei der Entwicklung die Überprüfung von zusätzlichen Authentifizierungskriterien ermöglicht, darunter auch der Vergleich der öffentlichen Schlüssel.
```

2020-11-30 12:44 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +In unserem Beispiel implementiert die Klasse “SftpPublickeyAuthenticator” eine solche Schnittstelle.
```suggestion
In unserem Beispiel implementiert die Klasse "SftpPublickeyAuthenticator" eine solche Schnittstelle. 
```

2020-11-30 12:45 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Die Methode "isPublicKeyValid“ der Klasse "PublicKeyService“ enthält die Logik für die Validierung und den Vergleich der öffentlichen Schlüssel.
```suggestion
Die Methode "isPublicKeyValid" der Klasse "PublicKeyService" enthält die Logik für die Validierung und den Vergleich der öffentlichen Schlüssel. 
```

2020-11-30 12:46 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Konnten beide öffentliche Schlüssel in der Methode "generatePublicKey“ fehlerfrei analysiert werden, prüft die Methode "compareKeys“, ob der auf dem Server konfigurierte öffentliche Schlüssel mit dem
```suggestion
Konnten beide öffentlichen Schlüssel in der Methode "generatePublicKey" fehlerfrei eingelesen werden, prüft die Methode "compareKeys", ob der auf dem Server konfigurierte öffentliche Schlüssel mit dem öffentlichen Schlüssel des Clients übereinstimmt. 
```

2020-11-30 12:50 UTC, jo2 requested changes
Ein paar Sachen habe ich noch angemerkt, das meiste auf Grund von Anführungszeichen und gendergerechter Formulierung. Es ist auf jeden Fall schon deutlich leichter zu verstehen!

2020-12-02 21:40 UTC, IvanKablar commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +In der Anwendung wird die zu signierende Nachricht zunächst zu einem eindeutigen nicht umkehrbarer Hashwert kodiert und anschließend mit dem privaten Schlüssel verschlüsselt.
@jo2 Die Änderung sieht gut aus. Kannst Du bitte noch den ersten Satz Deines Vorschlags korrigieren?

2020-12-03 10:20 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +In der Anwendung wird die zu signierende Nachricht zunächst zu einem eindeutigen nicht umkehrbarer Hashwert kodiert und anschließend mit dem privaten Schlüssel verschlüsselt.
Oh, danke, der Satz passte ja mal so garnicht. Habs korrigiert.

2020-12-03 10:37 UTC, jo2 commented
@IvanKablar aus irgendwelchen Gründen wird dein Blogpost in der Preview nicht angezeigt. Ich gucke mir das grade mal an und mache ein paar Commits. Wenn du lokal noch etwas ändern möchtest, müsstest due einmal pullen bevor du pushst.

2020-12-03 11:27 UTC, jo2 commented
@IvanKablar Das Problem mit der Darstellung ist behoben, kannst du dein Bild vielleicht noch etwas quadratischer machen, das ist sehr gestaucht. Deinen Fix in meinem Kommentar habe ich eingearbeitet.

2020-12-08 21:14 UTC, IvanKablar commented
@jo2 Hallo Johannes, 
ist das Diagramm soweit verständlich?
VG
Ivan

2020-12-15 09:52 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Die digitale Signatur kann verwendet werden, um Dokumente digital und rechtssicher zu unterzeichnen, die Identität des Unterzeichners und die Integrität von Nachrichten zu bestätigen.
```suggestion
Die digitale Signatur kann verwendet werden, um Dokumente digital und rechtssicher zu unterzeichnen und die Identität des Unterzeichners und die Integrität von Nachrichten zu bestätigen.
```

2020-12-15 10:01 UTC, jo2 commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Außerdem überprüft das Framwork die Signatur des privaten Schlüssels.
```suggestion
Außerdem überprüft das Framwork die Signatur mit Hilfe des privaten Schlüssels erstellte Signatur. 
```

2020-12-15 10:06 UTC, jo2 requested changes
Zwei Kleinigkeiten habe ich noch angemerkt, danach ist der Beitrag von meiner Seite aus fertig.

2020-12-16 21:10 UTC, IvanKablar commented on _posts/2020-11-20-Authentifizierung-ueber-oeffentliche-Schluessel-mit-Apache-MINA.md
> +Außerdem überprüft das Framwork die Signatur des privaten Schlüssels.
@jo2 Das Framwork überprüft die Signatur mit Hilfe des öffentlichen Schlüssels. Ich würde den Absatz gerne nochmal etwas ändern. 

"Außerdem überprüft das Framwork die Signatur des privaten Schlüssels mittels des öffentlichen Schlüssels. Erst, wenn der Vergleich der öffentlichen Schlüssel gelingt und die Signatur korrekt ist, hat sich der Client erfolgreich authentifiziert."

2020-12-17 09:55 UTC, jo2 submitted a review, later dismissed

2020-12-17 09:55 UTC, jo2 commented
@acetous rechtschreibtechnisch ist der Artikel soweit in Ordnung. Machst du noch eine inhaltliche Review?

2020-12-17 23:05 UTC, IvanKablar commented
@jo2 @acetous Ich habe vorab eine inhaltliche Review und einige Änderungen gemacht. Der Artikel liest sich jetzt runder.

2020-12-17 23:06 UTC, IvanKablar commented
@jo2 @acetous Ich bin soweit fertig. Falls ihr keine Vorschläge mehr habt, kann der Artikel von meiner Seite so raus.

2020-12-23 08:43 UTC, jo2 submitted a review, later dismissed

2021-01-13 08:14 UTC, acetous approved these changes

2021-01-13 08:21 UTC, merged