Passworthashing - Aber sicher!
adessoAG/devblog pull request #187
Opened 2020-12-01 19:58 UTC by html04

Blogpost hinzugefügt

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x]  "title" vergeben
    - [x] "author" angegeben
    - [x ] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, People, Inside adesso)
    - [x ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ x] Rechtschreibung korrigiert
  - [x ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2020-12-07 09:43 UTC, jo2 commented on _data/authors.yml
> +  bio: "Torsten ist Software Engineer bei adesso und im IT-Security Umfeld unterwegs. Besonders interessiert ist er dabei an der Kryptographie, sowie Deep-Learning gestützten Cyber Angriffen."
```suggestion
  bio: "Torsten ist Software Engineer bei adesso und im IT-Security Umfeld unterwegs. Besonders interessiert ist er dabei an der Kryptographie sowie Deep-Learning gestützten Cyber Angriffen."
```

2020-12-07 09:49 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Die Gefahr, dass der Datenbankinhalt abgegriffen wird und so an Passwörter, die evtl. auch in anderen Onlinediensten Verwendung finden, gekommen wird, ist einfach zu groß.
```suggestion
Die Gefahr, dass der Datenbankinhalt und somit auch Passwörter, die evtl. auch anderswo Verwendung finden, abgegriffen werden, ist einfach zu groß.
```

2020-12-07 09:49 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Trotzdem finden sich bei konkreten Umsetzungen häufig Fehler, sodass immer wieder Passwort Leaks öffentlich werden, die auf eine unsachgemäße Speicherung von besagten Passwörtern zurückzuführen ist.
```suggestion
Trotzdem finden sich bei konkreten Umsetzungen häufig Fehler, sodass immer wieder Passwort Leaks öffentlich werden, die auf eine unsachgemäße Speicherung von besagten Passwörtern zurückzuführen sind. 
```

2020-12-07 09:53 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Um nicht selbst ein Eintrag in dieser Liste zu werden, soll dieser Blogartikel bei der Wahl des sicheren Verfahrens unterstützen, sowie Hinweise für die richtige Parametrisierung geben.
```suggestion
Um nicht selbst ein Eintrag in dieser Liste zu werden, soll dieser Blogartikel bei der Wahl des sicheren Speicherverfahrens unterstützen sowie Hinweise für die richtige Parametrisierung geben.
```

Kannst du hier näher auf "diese Liste" eingehen? Bisher wird sie nicht erwähnt, du nimmst aber dennoch Bezug darauf.

2020-12-07 09:54 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Illustriert werden die Beispiele in Java mithilfe von Spring-Security.
```suggestion
Illustriert werden die Beispiele in Java und Spring-Security.
```

2020-12-07 09:55 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Um Passwörter in der Datenbank sicher abzuspeichern brauchen wir eine Lösung, die einen Wert erzeugt, über den immer noch die Korrektheit des Passworts überprüft, aber aus dem das Klartextpasswort ni
```suggestion
Um Passwörter in der Datenbank sicher abzuspeichern, brauchen wir eine Lösung, die einen Wert erzeugt, über den immer noch die Korrektheit des Passworts überprüft, aber aus dem das Klartextpasswort nicht zurückgewonnen werden kann. 
```

2020-12-07 09:58 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Die Angabe, welche Hashfunktionen als sicher gelten, muss ständig überprüft werden, da mögliche AngreiferInnen und Sicherheitsforschende regelmäßig Angriffe auf bekannte Verfahren untersuchen.
```suggestion
Die Angabe, welche Hashfunktionen als sicher gelten, muss ständig überprüft werden, da mögliche angreifende Personen und Sicherheitsforschende regelmäßig Angriffe auf bekannte Verfahren untersuchen. 
```

2020-12-07 09:59 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Angriff heißt in diesem Zusammenhang vor allem, dass effizient Kollisionen berechnet werden können oder aus der Ausgabe die assoziierte Eingabe berechnet werden können.
```suggestion
Angriff heißt in diesem Zusammenhang vor allem, dass effizient Kollisionen berechnet werden können oder aus der Ausgabe die assoziierte Eingabe berechnet werden kann. 
```

2020-12-07 10:00 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Der erste Angriff ist die Wörterbuchattacke oder auch der sogenannte Rainbow-Table Angriff.
```suggestion
Der erste Angriff ist die Wörterbuchattacke oder auch Rainbow-Table Angriff genannt. 
```

2020-12-07 10:09 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Möglich macht das die angesprochene Effizienz der klassischen Hashfunktionen und die geringe Entropie, also die Verteilung, von nutzergenerierten Passwörtern.
Meinst du mit geringer Verteilung hier die große Ähnlichkeit der Nutzerpasswörter untereinander?

Eigentlich sind Wörterbuch- bzw. Rainbow-Table-Angriffe doch auch nur spezielle Formen von Brute-Force-Angriffen, oder?

2020-12-07 10:11 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Mit Unterstützung von spezialisierter Hardware wie GPUs gibt es z.B. Hashcat-Implementierungen, die 23 Mrd. SHA-256 Hashes pro Sekunde (!) durchprobieren können.
```suggestion
Da bspw. GPUs sehr viele Berechnungen parallel ausführen können, können mit einer Hashcat-Implementierungen bis zu 23 Mrd. SHA-256 Hashes pro Sekunde (!) durchprobiert werden.
```

2020-12-07 10:13 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Um das Erstellen von Wörterbüchern für AngreiferInnen unpraktikabel zu machen, wird das Passwort mit einem öffentlichen Zufallswert, dem _Salt_, kombiniert.
```suggestion
Um das Erstellen von Wörterbüchern für Angreifende unpraktikabel zu machen, wird das Passwort mit einem öffentlichen Zufallswert, dem _Salt_, kombiniert.
```

2020-12-07 10:14 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Üblich ist es z.B. den Wert an den Passwort-String anzuhängen.
```suggestion
Üblich ist es z.B., den Wert an den Passwort-String anzuhängen.
```

2020-12-07 10:14 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Um einen Wörterbuchangriff durchzuführen, müsste es nun für jedes mögliche _Salt_ ein Wörterbuch mit allen möglichen Passwörtern erstellt werden.
```suggestion
Um einen Wörterbuchangriff durchzuführen, müsste nun für jedes mögliche _Salt_ ein Wörterbuch mit allen möglichen Passwörtern erstellt werden. 
```

2020-12-07 10:15 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Bei Verwendung eines Salts mit _n_-Bit Länge würden so 2 hoch _n_ mal mehr Wörterbücher benötigt, als ohne Verwendung eines Salts.
```suggestion
Bei Verwendung eines Salts mit _n_ Bit Länge würden so 2 hoch _n_ mal mehr Wörterbücher benötigt, als ohne Verwendung eines Salts.
```

2020-12-07 10:16 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Dadurch wird ein Ausprobieren sehr viel länger dauern aund seinerseits nicht mehr effizient durchführbar sein.
```suggestion
Dadurch wird ein Ausprobieren sehr viel länger dauern und somit nicht mehr effizient durchführbar sein.
```

2020-12-07 10:17 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Als Richtwert wie lange das Verfahren dauern soll und darf, gilt dabei, dass eine Anmeldung an einem Backend Server 0,5 - 1 Sekunde benötigen darf.
```suggestion
Als Richtwert, wie lange das Verfahren dauern soll und darf, gilt dabei, dass eine Anmeldung an einem Backend Server 0,5 - 1 Sekunde benötigen darf.
```

2020-12-07 10:17 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +In den folgenden Abschnitten stelle ich nun drei verschiedene Verfahren vor, die diese Gegenmaßnahmen mitbringen und veranschauliche sie anhand eines Java-Code-Schnipsels mit dem auf Bouncy-Castle ba
```suggestion
In den folgenden Abschnitten stelle ich nun drei verschiedene Verfahren vor, die diese Gegenmaßnahmen mitbringen, und veranschauliche sie anhand eines Java-Code-Schnipsels mit dem auf Bouncy-Castle basierenden Spring-Security.
```

2020-12-07 10:20 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Um die obengenannten Angriffe zu vereiteln wird zunächst ein zufälliger Salt generiert und auf einen Zähler wird zusammen mit dem Salt ein HMAC (Keyed-Hash Message Authentication Code) mehrfach angew
```suggestion
Um die obengenannten Angriffe zu vereiteln, wird zunächst ein zufälliger Salt generiert und auf einem Zähler wird zusammen mit dem Salt ein HMAC (Keyed-Hash Message Authentication Code) mehrfach angewendet. 
```

Der zweite Teil des Satzes passt grammatikalisch noch nicht, guck da bitte nochmal drüber.

2020-12-07 10:24 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Die Parametrisierung macht es möglich diesen Wert je nach Anwendungsfall bei einer Weiterentwicklung der verfügbaren Rechenleistung diesen Wert anzupassen.
```suggestion
Die Parametrisierung macht es möglich, diesen Wert je nach Anwendungsfall bei einer Weiterentwicklung der verfügbaren Rechenleistung diesen Wert anzupassen. 
```

Der zweite Teil des Satzes passt grammatikalisch nicht, guck da bitte nochmal drüber.

2020-12-07 10:25 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Der Original-RFC 2898 aus dem Jahre 2000 empfahl noch mindestens einen _Iteration Count_ von 1.000 während aktuell das Minimum laut einer NIST Guideline von 2016 bei 10.000 liegt.
```suggestion
Der Original-RFC 2898 aus dem Jahre 2000 empfahl noch mindestens einen Iteration Count von 1.000 während aktuell das Minimum laut einer NIST Guideline von 2016 bei 10.000 liegt. 
```

2020-12-07 10:27 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Dabei erzeugt es mit deim encode() im Default einen einen Hex-String in der Form
```suggestion
Mit encode() wird im Default ein Hex-String in folgender Form erstellt:
```

2020-12-07 10:29 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Dieser enthält einen 64-Bit Salt, der automatisch jedes Mal generiert wird, sowie den eigentlichen Hashwert.
```suggestion
Dieser enthält ein 64-Bit Salt, das jedes Mal automatisch generiert wird, sowie den eigentlichen Hashwert.
```

Meinst du hier, dass der Hex-String das Salt und den Hash enthält? Der Hex-String ist doch der Hash und enthält das Salt und das Passwort, oder nicht?

2020-12-07 10:30 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Auf einem Entwicklerlaptop mit einem Intel i9 benötigt die einmalige Ausführung ca. 700 ms, was gut zu unseren Vorbedingen von 0,5 - 1 Sekunde Ausführungszeit passt.
```suggestion
Auf einem Entwicklerlaptop mit einem Intel i9 benötigt die einmalige Ausführung ca. 700 ms, was gut zu unserer Vorbedingung von 0,5 - 1 Sekunde Ausführungszeit passt. 
```

2020-12-07 10:32 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Das National Institute of Standards and Technology empfiehlt PBKDF2 trotzdem bei Nutzung eines hohen Iteration Counts.
Du schribst hier National Institute of Standards and Technology aus und oben verwendest du die Abkürzung. Bitte schreibe es oben in einer der Formen National Institute of Standards and Technology (NIST) oder NIST (National Institute of Standards and Technology) und verwende folgend die Abkürzung.

2020-12-07 10:36 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Diesen höheren Speicherbedarf hat z.B. Bcrypt.
Warum ist höherer speicherbedarf an der Stelle im Bereich Speichernutzung besser? Gehe da doch bitte noch drauf ein, bspw.:
"Verfahren mit höherem Speicherbedarf und Konfigurierbarkeit sind an der Stelle besser, da ..."
"Ein Beispiel für höheren Speichrbedarf ist Bcrypt."

2020-12-07 10:38 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Es verschlüsselt den festen Plaintext „OrpheanBeholderScryDoubt“ mit Rundenschlüsseln, die aus dem zu hashenden Passwort und dem _Salt_ abgeleitet werden.
```suggestion
Es verschlüsselt den festen Plaintext "OrpheanBeholderScryDoubt" mit Rundenschlüsseln, die aus dem zu hashenden Passwort und dem Salt abgeleitet werden. 
```

2020-12-07 10:38 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Das zu hashende Passwort wird dafür vorher mit einem Salt von 128-Bit Länge konkateniert.
```suggestion
Das zu hashende Passwort wird dafür vorher mit einem Salt von 128 Bit Länge konkateniert. 
```

2020-12-07 10:40 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Diese einfache Parametrisierbarkeit mit klaren Empfehlungen macht Bcrypt zu einem empfehlenswerten und einfach anwendbaren Verfahren.
```suggestion
Diese einfache Parametrisierbarkeit mit klaren Empfehlungen macht Bcrypt zu einem empfehlenswerten und einfach anwendbarem Verfahren. 
```

2020-12-07 10:42 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +String encoded = encoder.encode(secret);
Sollte hier nich, analog zum oberen Beispiel, der String "geheim" stehen?

2020-12-07 10:42 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Der String den das Bcrypt erzeugt hat allerdings eine etwas andere Form als von PBKDF2 bekannt und sieht so aus:
```suggestion
Der String, den das Bcrypt erzeugt, hat allerdings eine etwas andere Form als von PBKDF2 bekannt und sieht so aus:
```

2020-12-07 10:44 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Er enthält also alles, um ein Passwort auf anhand des Hashes verifizieren zu können und kann auch so in der Datenbank abgelegt werden.
```suggestion
Er enthält also alles, um ein Passwort anhand des Hashes verifizieren zu können, und kann auch so in der Datenbank abgelegt werden.
```

2020-12-07 10:45 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Die Speichernutzung ist wichtig, um vor allem optimierten Brute-Force Angriffen auf spezialiesierter Hardware, wie FPGAs und GPUs standhalten zu können.
```suggestion
Die Speichernutzung ist wichtig, um optimierten Brute-Force Angriffen auf spezialiesierter Hardware standhalten zu können.
```

2020-12-07 10:48 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Ein Nachfolger von bcrypt nahm an der Password Hashing Competion teil.
```suggestion
Ein Nachfolger von Bcrypt nahm an der Password Hashing Competion teil.
```

2020-12-07 10:49 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Als Sieger der Password Hashing Competition aus dem Jahre 2015 ging Argon2 hervor.
```suggestion
Der Sieger der Password Hashing Competition aus dem Jahre 2015 war Argon2.
```

2020-12-07 10:50 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Das Verfahren sorgt mit einer größeren Speichernutzung durch die Bildung eines großen internen Vektors dafür, dass durch spezialisierte Hardware getriebene Brute-Force Angriffe die Optimierungspotenz
```suggestion
Das Verfahren sorgt mit einer größeren Speichernutzung durch die Bildung eines großen internen Vektors dafür, dass Brute-Force Angriffe mit spezialisierter Hardware ein geringeres Optimierungspotenzial haben. 
```

2020-12-07 10:51 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +* Argon2d: Der Indexzugriff auf den internen Vektor erfolgt abhängig vom Passwort und Salt und so anfällig für Cache-Timing Side-Channel Angriffe.
```suggestion
* Argon2d: Der Indexzugriff auf den internen Vektor erfolgt abhängig vom Passwort und Salt und ist somit anfällig für Cache-Timing Side-Channel Angriffe. 
```

Gehe bitte in einem Satz näher darauf ein, was Cache-Timing Side-Channel Angriffe sind.

2020-12-07 10:54 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +* Argon2id: Hybride Version aus dem Jahr 2017, die weniger anfällig für Side-Channel Leakage als Argon2d ist und besser geschützt gegen Optimierung durch spezialisierte Hardware ist als Argon2i.
```suggestion
* Argon2id: Hybride Version aus dem Jahr 2017, die weniger anfällig für Side-Channel Leakage als Argon2d und besser gegen Optimierung durch spezialisierte Hardware geschützt ist als Argon2i.
```

2020-12-07 10:55 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Parametrisieren lassen sich alle Varianten in drei verschiedene Ausprägungen.
```suggestion
Alle Varianten bieten drei verschiedene Möglichkeiten zur Parameterisierung: 
```

2020-12-07 10:57 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Daher habe ich den Paramter _t_ so stark erhöht, dass ca. 0,5 Sekunden Laufzeit erreicht wird (gewählte Parametrisierung: _m_ = 4096, _p_ = 2, _t_=90).
```suggestion
Daher habe ich den Paramter _t_ so stark erhöht, dass ca. 0,5 Sekunden Laufzeit erreicht werden (gewählte Parametrisierung: _m_ = 4096, _p_ = 2, _t_=90).
```

2020-12-07 10:58 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Argon2PasswordEncoder encoder = new Argon2PasswordEncoder(16, 32, 1, 4_096, 90);
Hier wird kein Parameter auf 2 gesetzt, obwohl du sagst, du hättest 2 als Wert für p gewählt. Vielleicht kannst du einmal kurz auf die Bedeutung der Parameter eingehen?

2020-12-07 10:59 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +String encoded = encoder.encode(secret);
Sollte hier nich, analog zum oberen Beispiel, der String "geheim" stehen?

2020-12-07 11:00 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Der Hash des Passwort beinhaltet wie bei Bcrypt die Parameter, sowie den Salt, die Argon2-Version und den Hash an sich:
```suggestion
Der Hash des Passworts beinhaltet, wie bei Bcrypt, die Parameter, das Salt, die Argon2-Version und den Hash an sich:
```

2020-12-07 11:04 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Mit einfach mal hashen ist es bei der Persistierung von Passwörtern nicht getan.
```suggestion
Mit "einfach mal hashen" ist es bei der Persistierung von Passwörtern nicht getan. 
```

2020-12-07 11:04 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Durch den Einsatz eines _Salts_ zusammen mit einer künstlichen Verlangsamung des verwendeten Hashverfahrens lassen sich diese Angriffe vereiteln.
```suggestion
Durch den Einsatz eines Salts zusammen mit einer künstlichen Verlangsamung des verwendeten Hashverfahrens lassen sich diese Angriffe vereiteln.
```

2020-12-07 11:05 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Die Implementierungen lösen dabei meistens auch schon die Frage nach der _Salt_- und die Parameterspeicherung.
```suggestion
Die Implementierungen lösen dabei meistens auch schon die Frage nach der Salt- und Parameterspeicherung. 
```

2020-12-07 11:05 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Eine zusätzliche Versionierung, z.B. in einer extra Spalte, in der der Datenbank ist allerdings sinnvoll, um veraltete Hashes schneller zu finden.
```suggestion
Eine zusätzliche Versionierung, z.B. in einer extra Spalte in der der Datenbank, ist allerdings sinnvoll, um veraltete Hashes schneller zu finden.
```

2020-12-07 11:06 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +* PBKDF2 wird aktuell noch vom NIST als sicher genug empfohlen, hat allerdings eine sehr geringe Speichernutzung, die es anfällig für Brute-force Angriffe macht.
```suggestion
* PBKDF2 wird aktuell noch vom NIST als sicher genug eingestuft, hat allerdings eine sehr geringe Speichernutzung, die es anfällig für Brute-force Angriffe macht. 
```

2020-12-07 11:07 UTC, jo2 requested changes
Der Artikel liest sich schon gut, ein paar Sachen habe ich noch angemerkt.

2020-12-08 18:02 UTC, html04 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Möglich macht das die angesprochene Effizienz der klassischen Hashfunktionen und die geringe Entropie, also die Verteilung, von nutzergenerierten Passwörtern.
Zu 1, ja,

Zu 2, hier ist meint Brute-Force allerdings, dass man für jeden Wert alles neu ausprobieren muss.

2020-12-08 18:58 UTC, html04 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Die Speichernutzung ist wichtig, um vor allem optimierten Brute-Force Angriffen auf spezialiesierter Hardware, wie FPGAs und GPUs standhalten zu können.
habs gestrichen, da ich jetzt die Speichernutzung oben erkläre

2020-12-08 19:10 UTC, html04 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Daher habe ich den Paramter _t_ so stark erhöht, dass ca. 0,5 Sekunden Laufzeit erreicht wird (gewählte Parametrisierung: _m_ = 4096, _p_ = 2, _t_=90).
Eine Laufzeit _wird_ erreicht oder?

2020-12-09 07:01 UTC, html04 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Argon2PasswordEncoder encoder = new Argon2PasswordEncoder(16, 32, 1, 4_096, 90);
Hab die Parallelität präzisiert. Ansonsten sind alle Parameter aus meiner Sicht beschrieben.

2020-12-15 10:17 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Diese Funktion ermöglicht es uns aus benutzergenerierten Passwörtern z.B. Schlüssel zu generieren, die für eine symmetrische Verschlüsselung dienen können.
```suggestion
Diese Funktion ermöglicht es uns, aus benutzergenerierten Passwörtern z.B. Schlüssel zu generieren, die für eine symmetrische Verschlüsselung dienen können. 
```

2020-12-15 10:17 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Um die obengenannten Angriffe zu vereiteln, wird zunächst ein zufälliger Salt generiert.
```suggestion
Um die oben genannten Angriffe zu vereiteln, wird zunächst ein zufälliger Salt generiert.
```

2020-12-15 10:19 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Auf einen Zähler konkateniert mit diesem Salt wird dann ein HMAC (Keyed-Hash Message Authentication Code) mehrfach angewendet.
```suggestion
Dieses Salt wird mit einem Zähler konkateniert, anschließend wird ein HMAC (Keyed-Hash Message Authentication Code) mehrfach auf diesen String angewendet.
```

2020-12-15 10:27 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Dabei wird anhand der mithilfe der Laufzeit gemessen, welche Einträge des Vektors gecacht werden konnten.
```suggestion
Dabei wird anhand der Laufzeit gemessen, welche Einträge des Vektors gecacht werden konnten.
```

2020-12-15 10:28 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Das Originalpaper stellt keine konkrete Empfehlung für Parameter vor.
```suggestion
Das Originalpaper stellt keine konkrete Empfehlung für diese Parameter vor. 
```

2020-12-15 10:28 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Daher habe ich den Parameter _t_ so stark erhöht, dass ca. 0,5 Sekunden Laufzeit erreicht wird (gewählte Parametrisierung: _m_ = 4096, _p_ = 1, _t_ = 90).
```suggestion
Daher habe ich den Parameter _t_ so stark erhöht, dass ca. 0,5 Sekunden Laufzeit erreicht werden (gewählte Parametrisierung: _m_ = 4096, _p_ = 1, _t_ = 90).
```

2020-12-15 10:29 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Da die Bouncy-Castle Implementierung die Parallelisierung aktuell nicht ausnutzt, lohnt es sich nicht diesen Parameter bei Spring-Security hochzusetzen.
```suggestion
Da die Bouncy-Castle Implementierung die Parallelisierung aktuell nicht ausnutzt, lohnt es sich nicht, diesen Parameter bei Spring-Security hochzusetzen.
```

2020-12-15 10:34 UTC, jo2 requested changes
Ein paar Sachen habe ich noch angemerkt, achte bitte außerdem darauf, dass wenn du eine Abkürzung einführst, du einheitlich entweder erst den Begriff ausschreibst und danach die Abkürzung in die Klammern schreibst oder anders herum.

2020-12-15 20:00 UTC, html04 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Daher habe ich den Parameter _t_ so stark erhöht, dass ca. 0,5 Sekunden Laufzeit erreicht wird (gewählte Parametrisierung: _m_ = 4096, _p_ = 1, _t_ = 90).
Aus meiner sicht bezieht sich das werden auf die Laufzeit und dann ist "wird" richtig

2020-12-16 13:06 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Daher habe ich den Parameter _t_ so stark erhöht, dass ca. 0,5 Sekunden Laufzeit erreicht wird (gewählte Parametrisierung: _m_ = 4096, _p_ = 1, _t_ = 90).
In dieser Formulierung mit den 0,5 Sekunden Laufzeit ist 0,5 Sekunden der Nominativ und steht im Plural, sodass auch das Verb im Plural stehen muss. Laufzeit steht im Nominativ, wenn du die Formulierung wie folgt abänderst, dann ist das Verb im Singular korrekt: ".., dass eine Laufzeit von 0,5 Sekunden erreicht wird..."

2020-12-16 13:07 UTC, jo2 commented on _posts/2020-12-01-Passworthashing_Aber_Sicher.md
> +Daher habe ich den Parameter _t_ so stark erhöht, dass ca. 0,5 Sekunden Laufzeit erreicht wird (gewählte Parametrisierung: _m_ = 4096, _p_ = 1, _t_ = 90).
Sehe grade, du hast es im zweiten Commit umformuliert, passt so.

2020-12-16 13:08 UTC, jo2 approved these changes

2020-12-16 13:10 UTC, jo2 commented
@acetous rechtschreibtechnisch passt der Artikel so weit. Guckst du dir das noch inhaltlich an?

2021-03-01 10:27 UTC, acetous submitted a review, later dismissed

2021-03-01 10:27 UTC, acetous approved these changes

2021-03-01 10:29 UTC, merged