Initial commit for Post "Why you should not use WebAssembly to build your SPA"
adessoAG/devblog pull request #189
Opened 2021-01-19 15:48 UTC by xXanth0s

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-01-20 07:59 UTC, jo2 commented
Do you need to have the review in english or is german ok as well? Is this only the initial commit with more coming so that the pr is stil a draft or is this your final commit?

2021-01-20 09:18 UTC, xXanth0s commented
Review kann gerne auch auf Deutsch gemacht werden. 
Habe jetzt die fehlenden GitHub Links eingefügt und der PR wäre jetzt ready for review

2021-01-25 18:23 UTC, xXanth0s commented
Öh ja, der PR wäre immer noch ready for review und nicht "Waiting for Author"

2021-01-26 10:48 UTC, jo2 commented on _data/authors.yml
> +  email: maximilian.lang@adesso.de, maxi.schore@gmail.com
Bitte verwende hier nur deine adesso-E-Mail-Adresse

2021-01-26 10:49 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +
Bitte füge hier einen Teaser ein, der einen kleinen Einblick in deinen Artikel gibt.

2021-01-26 10:50 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +But what exactly is WebAssembly, how does it work and how does it compare to JavaScript in terms of Singe Page Applications?
```suggestion
But what exactly is WebAssembly, how does it work and how does it compare to JavaScript in terms of Single Page Applications?
```

2021-01-26 10:53 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +Implementing logic with this is a rather inefficient and frustrating way of wasting its time.
```suggestion
Implementing logic with this is a rather inefficient and frustrating way of wasting ones time. 
```

2021-01-26 10:58 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +So we have an immediate response for the user This concept of interpretation can only be applied to a few other programming language and also has many disadvantages, which is why JavaScript quickly r
```suggestion
This results in an immediate response for the user.
The concept of interpretation can only be applied to a few other programming languages and also has many disadvantages, which is why JavaScript quickly reaches its limits.
```

2021-01-26 11:01 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +Since WebAssembly saves us the unnecessary compilation of JavaScript in the browser and also Low Level Languages has a higher performance than JavaScript, it would be ideal to implement single page a
```suggestion
Since WebAssembly saves us the unnecessary compilation of JavaScript in the browser and also low level languages have a higher performance than JavaScript, it would be ideal to implement single page applications in WebAssembly.
```

2021-01-26 11:03 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +It is developed in C# and is like all UI frameworks components based. In addition, it offers important functionalities such as routing, templating and dependency injection.
```suggestion
It is developed in C# and is like all UI frameworks component based.
In addition, it offers important functionalities such as routing, templating and dependency injection.
```

2021-01-26 11:04 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +- Pictures list for rendering images
```suggestion
- Picture list for rendering images
```

2021-01-26 11:07 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +However, in its current version, it cannot be used for Singe Plage Applications.
```suggestion
However, in its current version, it cannot be used for Single Page Applications.
```

2021-01-26 11:11 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +At 13,557 KB, the total volume of the WebAssembly application is 23 times that of Vue.js.
```suggestion
At 13557 KB, the total volume of the WebAssembly application is 23 times that of Vue.js. 
```
Es sind 13557,1 KB, das Komma an der Stelle als Tausender-Trennzeichen ist im Context eines hauptsächlich deutschsprachigen Blogs sehr verwirrend und sollte daher weggelassen werden.

2021-01-26 11:15 UTC, jo2 requested changes
Der Artikel liest sich schon recht gut, ein paar Sachen habe ich noch angemerkt. Außerdem ein paar generelle Sachen:
* Verwende bitte die richtigen Zeichen anstelle der Encodings
* Einige Bilder fehlen, zum Beispiel auch dein Profilbild, andere werden nicht verwendet, bitte überprüfe das einmal
* du hast in der authors.yml einige Änderungen, die nichts mit deinem Eintrag zu tun haben, entferne diese Änderungen bitte.

2021-01-26 19:04 UTC, xXanth0s commented
Danke für das Review. 
Hab es entsprechend angepasst

2021-02-02 07:52 UTC, jo2 commented on _posts/2021-01-19-Why-you-should-use-WebAssembly-to-build-your.md
> +
Der Teaser darf keine Überschrift haben. Schau dir mal  [dieses Beispiel](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md) an.

2021-02-02 07:58 UTC, jo2 requested changes
Eine Kleinigkeit ist noch mit dem Teaser, danach ist der Artikel. Außerdem:
* Verwende bitte die richtigen Zeichen anstelle der Encodings
* Einige Bilder fehlen, zum Beispiel auch dein Profilbild, andere werden nicht verwendet, bitte überprüfe das einmal
* Du hast in der authors.yml einige Änderungen, die nichts mit deinem Eintrag zu tun haben, entferne diese Änderungen bitte.

2021-02-05 10:17 UTC, xXanth0s commented
Hab jetzt die Encodings geupdated und mein Avatar Bild hinzugefügt. 
Die Bilder wurden jedoch alle verwendet. Außer ich habe eins übersehen, dann gib mir bitte bescheid.

2021-02-15 17:11 UTC, xXanth0s commented
Gibts hierzu ein Update?

2021-02-16 08:47 UTC, jo2 approved these changes

2021-02-16 08:48 UTC, jo2 commented
@xXanth0s hatte leider die letzten Wochen wenig Zeit, von meiner Seite aus is der Artikel soweit fertig. @acetous machst du noch eine inhaltliche Review?

2021-03-01 15:37 UTC, xXanth0s commented
Was ist denn jetzt schon wieder? 
Kann man den Blogartikel nicht endlich mal veröffentlichen?

2021-03-01 16:14 UTC, jo2 commented
Der Veröffentlichungsprozess im devblog ist so aufgebaut, dass 2 Reviews stattfinden. Die erste Review bezieht sich hauptsächlich rechtschreibtechnische und grobe inhaltliche Korrekturen. Danach schaut Sebastian als Projektverantwortlicher für den Devblog nochmal grob drüber. @acetous wie sieht es hier aus?

2021-03-03 13:00 UTC, acetous commented
Der Artikel ist für die Veröffentlichung eingeplant, daher auch das entsprechende Label am PR. ;)
@xXanth0s Du brauchst hier nichts weiter zu tun.

2021-03-04 08:11 UTC, merged