Wartbarkeit von Software 2
adessoAG/devblog pull request #190
Opened 2021-01-22 08:51 UTC by ThiloLange

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-01-26 10:38 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Der Quelltext der Unit Tests sollte in Bezug auf Lesbarkeit und Robustheit von gleicher Qualität wie der Anwendungs-Code selbst sein.
```suggestion
Der Quell-Code der Unit Tests sollte in Bezug auf Lesbarkeit und Robustheit von gleicher Qualität wie der Anwendungs-Code selbst sein.
```

2021-01-26 10:38 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Der Unit Test sollte so geschrieben sein, dass der in der Komponente umgesetzte fachliche Anwendungsfall nicht nur technisch geprüft wird, sondern auch das gewünschte Verhalten der Komponente aus dem
```suggestion
Der Unit Test sollte so geschrieben sein, dass der in der Komponente umgesetzte fachliche Anwendungsfall nicht nur technisch geprüft wird, sondern auch das gewünschte Verhalten der Komponente aus dem Quell-Code abgelesen werden kann.
```

2021-01-26 10:39 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Das bedeutet, dass ein Werkzeug zur Code Analyse (z.B. SonarQube) bereitgestellt und konfiguriert wird, das die Metriken zur Testabdeckung direkt nach einem Push erhebt, diese durch ein für das Proje
Kannst du diesen Satz aufteilen, das erleichtert das lesen. Außerdem ein Vorschlag zum Gendern: Entwicklungsteam statt Entwicklerinnen und Entwickler

2021-01-26 10:39 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Jedoch zeigt die Erfahrung aus Projekten, die bereits erfolgreich in Wartung übernommenen wurden, dass mit einer guten Planung, einem hohen Stellenwert für die Tests und entsprechender Konfiguration
```suggestion
Jedoch zeigt die Erfahrung aus Projekten, die bereits erfolgreich in Wartung übernommenen wurden, dass mit einer guten Planung, einem hohen Stellenwert für die Tests und entsprechender Konfiguration des Code Analyse Werkzeugs (z.B. Ignorieren von automatisch generiertem Code) eine hohe Testabdeckung jenseits der 80% mit vertretbarem Aufwand durchaus erreichbar ist.
```

2021-01-26 10:39 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Die folgende Grafik zeigt beispielhaft die mit dem Werkzeug EclEmma in der Entwicklungsumgebung eclipse ermittelte Code-Coverage (Abdeckung) eines Unit-Tests:
Kannst du einen Link zu dem Tool angeben?

2021-01-26 10:40 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Bei all den hier beschriebenen Tätigkeiten, sollte jedoch nie vergessen werden, was einen guten Unit Test eigentlich auszeichnet.
```suggestion
Bei all den hier beschriebenen Tätigkeiten sollte jedoch nie vergessen werden, was einen guten Unit Test eigentlich auszeichnet.
```

2021-01-26 10:40 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Während Unit Tests die korrekte Funktionalität der kleinsten Einheiten, nämlich einzelner, in sich geschlossener Komponenten der Software sicherstellen, prüfen Integrationstests die Funktionalität, w
```suggestion
Während Unit Tests die korrekte Funktionalität der kleinsten Einheiten, nämlich einzelner, in sich geschlossener Komponenten der Software, sicherstellen, prüfen Integrationstests die Funktionalität, wenn mehrere solcher Komponenten zusammenarbeiten.
```

2021-01-26 10:40 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Für einen Integrationstest werden einige, bereits durch Unit Tests getestete Einzel-Komponenten zu einer neuen Komponente zusammengefügt und deren Zusammenwirken getestet.
```suggestion
Für einen Integrationstest werden einige, bereits durch Unit Tests getestete Einzelkomponenten zu einer neuen Komponente zusammengefügt und das Zusammenwirken der Einzelkomponenten getestet.
```

2021-01-26 10:41 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Es ist zu dokumentieren, wie die Testdaten aufgebaut sind und welche Schritte notwendig sind, sie zum Zeitpunkt eines Testlaufs korrekt in der Datenbank einzuspielen.
```suggestion
Es ist zu dokumentieren, wie die Testdaten aufgebaut sind und welche Schritte notwendig sind, um sie zum Zeitpunkt eines Testlaufs korrekt in die Datenbank einzuspielen.
```

2021-01-26 10:41 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Um eine Veränderung der Performance frühzeitig erkennen zu können, sind die Last- und Performance-Tests während der Entwicklungs-Phase in regelmäßigen Abständen (z.B. 1-mal pro Sprint oder 1-mal im M
```suggestion
Um eine Veränderung der Performance frühzeitig erkennen zu können, sind die Last- und Performance-Tests während der Entwicklungs-Phase in regelmäßigen Abständen (z.B. ein mal pro Sprint oder ein mal im Monat) auszuführen.
```

2021-01-26 10:41 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Aufgrund der regelmäßig durchzuführenden Tätigkeiten rund um die Last- und Performance-Tests, bietet es sich an, diese ebenfalls zu automatisieren und in eine Continuous Integration Pipeline zu integ
```suggestion
Aufgrund der regelmäßig durchzuführenden Tätigkeiten rund um die Last- und Performance-Tests bietet es sich an, diese ebenfalls zu automatisieren und in eine Continuous Integration Pipeline zu integrieren.
```

2021-01-26 10:42 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Dafür sind meist mehrere passende Testumgebungen (Test-Stage) bereitzustellen, die im besten Fall so konfiguriert sind, dass sie der späteren produktiven Umgebung in jedem Aspekt so nahe wie möglich
```suggestion
Dafür sind meist mehrere passende Testumgebungen (Test-Stages) bereitzustellen, die im besten Fall so konfiguriert sind, dass sie der späteren produktiven Umgebung in jedem Aspekt so nahe wie möglich kommen.
```

2021-01-26 10:42 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Wir haben dazu Kriterien vorgestellt, die als Grundlage für die spätere Übergabe einer Software in das Application Management, in die Wartung, zu beachten sind.
```suggestion
Wir haben dazu Kriterien vorgestellt, die als Grundlage für die spätere Übergabe einer Software in das Application Management (die Wartung) zu beachten sind.
```

2021-01-26 10:42 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Wichtig ist, dass zur Erfüllung dieser Kriterien Tätigkeiten notwendig sind, die bereits in den ersten Phasen eines Software Entwicklungs-Projektes einzuplanen sind!
```suggestion
Wichtig ist, dass zur Erfüllung dieser Kriterien Tätigkeiten notwendig sind, die bereits in den ersten Phasen eines Softwareentwicklungsprojektes einzuplanen sind!
```

2021-01-26 10:43 UTC, jo2 commented on _data/authors.yml
> -ivankablar:
Bitte füge diesen Eintrag wieder hinzu, die Daten des Autors werden noch in anderen Beiträgen benötigt.

2021-01-26 10:46 UTC, jo2 requested changes
Der Artikel liest sich schon sehr gut, ein paar Sachen habe ich noch angemerkt. Außerdem:
* Verwende bitte " statt „ und “
* Eclipse wird groß geschrieben

2021-01-26 15:04 UTC, ThiloLange commented
Vielen Dank für Dein Review... ich habe alle Deine Anmerkungen umgesetzt. Den Link zu EclEmma schaue ich mir in der Preview noch einmal an.

2021-02-02 08:01 UTC, jo2 commented on _posts/2021-01-18-wartbarkeit-von-software-teil-2-tests.md
> +Sollte die Prüfung fehlschlagen kann das Entwicklungsteam automatisch und zeitnah durch eine E-Mail informiert werden.
```suggestion
Sollte die Prüfung fehlschlagen, kann das Entwicklungsteam automatisch und zeitnah durch eine E-Mail informiert werden.
```

2021-02-02 08:05 UTC, jo2 requested changes
An einer Stelle fehlt noch ein Komma, danach ist der Artikel rechtschreibtechnisch durch.

2021-02-09 10:55 UTC, ThiloLange commented
Vielen Dank für Dein Review... ich habe Deine Anmerkung umgesetzt!

2021-02-11 08:53 UTC, ThiloLange commented
Hi Jo... ich habe das Komma bereits am 02.02. ergänzt. Gibt es noch ein weiteres Problem mit dem PR?

2021-02-16 12:31 UTC, jo2 commented
@ThiloLange ich bin bisher leider noch nicht dazu gekommen. @acetous machst du noch eine inhaltliche Review?

2021-02-16 12:31 UTC, jo2 submitted a review, later dismissed

2021-03-08 08:12 UTC, acetous approved these changes

2021-03-08 08:13 UTC, merged