Neuer Blogpost "Intelligenz vererben - Mit genetischen Algorithmen künstliche neuronale Netze trainieren" erstellt.
adessoAG/devblog pull request #192
Opened 2021-02-15 06:58 UTC by swindisch

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Java, Microsoft, Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-02-16 08:51 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Durch Hardware, beispielsweise Grafikkarten, die eigentlich für aufwändige 3D-Computerspiele genutzt werden, oder aber große Cloud-Rechenzentren, gibt es momentan unfassbar starke Rechenleistungen, u
```suggestion
Durch Hardware, beispielsweise Grafikkarten, die eigentlich für aufwändige 3D-Computerspiele genutzt werden, oder aber große Cloud-Rechenzentren, steht es momentan unfassbar viel Rechenleistung zur Verfügung, um die komplexe Mathematik hinter den Algorithmen in überschaubarer Zeit zu berechnen.
```

2021-02-16 08:53 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Starke künstliche Intelligenz hat das Ziel die intellektuellen Fähigkeiten von Mensch nachzuahmen oder sogar zu übertreffen.
```suggestion
Starke künstliche Intelligenz hat das Ziel, die intellektuellen Fähigkeiten von Mensch nachzuahmen oder sogar zu übertreffen.
```

2021-02-16 08:53 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Schwache künstliche Intelligenz hat das Ziel sich auf eine konkrete Lösung zu fokussieren und hier durch Rechenpower bessere Ergebnisse zu liefern als vergleichbare menschliche Leistung.
```suggestion
Schwache künstliche Intelligenz hat das Ziel, sich auf eine konkrete Lösung zu fokussieren und hier durch Rechenpower bessere Ergebnisse zu liefern als vergleichbare menschliche Leistung.
```

2021-02-16 08:54 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Beim maschinellen Lernen wird versucht Wissen aus Daten zu gewinnen.
```suggestion
Beim maschinellem Lernen wird versucht, Wissen aus Daten zu gewinnen.
```

2021-02-16 09:27 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +*Es gibt Trainings-Daten, die keine Ergebnisse mitliefern.
```suggestion
* Es gibt Trainings-Daten, die keine Ergebnisse mitliefern.
```

2021-02-16 09:29 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Beispielsweise Datensätze von Millionen von Bildern, die angeben, um was es sich handelt (Lebewesen, Dinge des Alltags, Zahlen oder Buchstaben).
```suggestion
Dazu gehören beispielsweise Datensätze von Millionen von Bildern, die angeben, was auf den Bildern zu sehen ist (Lebewesen, Dinge des Alltags, Zahlen oder Buchstaben).
```

2021-02-16 09:31 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Beispielsweise Kreditkarten-Transaktionen, bei denen nicht bekannt ist, ob Betrugsfälle vorhanden sind.
```suggestion
* Es gibt Trainings-Daten, die keine Ergebnisse mitliefern, wie Kreditkarten-Transaktionen, bei denen nicht bekannt ist, ob Betrugsfälle vorhanden sind.
Hier müssen andere Modelle genutzt werden.
```

2021-02-16 09:33 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Für das überwachte Lernen haben in den letzten Jahren, dank der Rechenpower aktueller Computer-Systeme, neuronale Netze verschiedenster Architekturen eine Renaissance erfahren. Sobald ein Netz aus ei
```suggestion
Für das überwachte Lernen haben in den letzten Jahren, dank der Rechenpower aktueller Computer-Systeme, neuronale Netze verschiedenster Architekturen eine Renaissance erfahren.
Sobald ein Netz aus einer komplexeren Architektur besteht, sprechen wir von **tiefem Lernen (Deep Learning)**.
```

2021-02-16 09:35 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Dazu gibt es noch einen Schwellwert (Bias) der die Berechnung des Ergebnisses noch anpassen kann.
```suggestion
Dazu gibt es noch einen Schwellwert (Bias), der die Berechnung des Ergebnisses noch anpassen kann.
```

2021-02-16 09:38 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Grundlegend bestehen neuronale Netze aus einer Eingabe-Schicht (Input-Layer), die die Daten entgegennimmt, einer oder vielen versteckter Schichten (Hidden-Layer), in denen die "Intelligenz" stattfind
```suggestion
Grundlegend bestehen neuronale Netze aus einer Eingabe-Schicht (Input-Layer), die die Daten entgegennimmt, einer oder vielen versteckten Schichten (Hidden-Layer), in denen die "Intelligenz" stattfindet und einer Ausgabeschicht (Output-Layer), die die Vorhersage liefert.
```

2021-02-16 09:39 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Beispielsweise "Hund oder Katze", "Betrugsfall ja/nein" oder aber auch der morgige Aktienkurs.
```suggestion
Diese Vorhersage ist dann beispielsweise "Hund oder Katze", "Betrugsfall ja/nein" oder aber auch der morgige Aktienkurs.
```

2021-02-16 09:46 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Nun wird das Netz mit tausenden, wenn nicht Millionen Daten, gefüttert und für jeden Datensatz die Abweichung von errechneter Vorhersage und Trainings-Ergebnis berechnet.
```suggestion
Nun wird das Netz mit tausenden, wenn nicht Millionen Daten gefüttert und für jeden Datensatz die Abweichung von errechneter Vorhersage und Trainings-Ergebnis berechnet.
```

2021-02-16 09:48 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Nun wird basierend auf komplexen verschiedenen mathematischen Verfahren versucht, die Abweichung zu minimieren, in dem rückwärts durch das Netz, vom Ende zum Anfang, gewandert wird und dabei jedes Ge
```suggestion
Nun wird basierend auf komplexen verschiedenen mathematischen Verfahren versucht, die Abweichung zu minimieren, indem rückwärts durch das Netz gewandert wird und dabei jedes Gewicht eines jeden Neurons minimal angepasst wird.
```

2021-02-16 09:49 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Das so trainierte neuronale Netz wird am Ende der Trainings-Phase als Model betitelt und für die spätere Nutzung gespeichert.
```suggestion
Das so trainierte neuronale Netz wird am Ende der Trainings-Phase als Modell betitelt und für die spätere Nutzung gespeichert.
```

2021-02-16 09:50 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Das Modell wird in einem Anwendungsfall in einer Produktionsumgebung eingebunden und für Vorhersagen unbekannter Eingabe-Daten genutzt.
```suggestion
Das Modell wird in einem Anwendungsfall in eine Produktionsumgebung eingebunden und für Vorhersagen unbekannter Eingabe-Daten genutzt.
```

2021-02-16 09:51 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Mit der Evolutionstheorie verstehen wir vereinfacht beschrieben, die Entstehung und Anpassung von Lebewesen an ihre Umgebung.
```suggestion
Mit der Evolutionstheorie verstehen wir, vereinfacht beschrieben, die Entstehung und Anpassung von Lebewesen an ihre Umgebung.
```

2021-02-16 09:51 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +* **Un-Überwachtes Training (Unsupervised Training)** – Hier liegen keine Ergebnisse vor, die Modelle können Daten gruppieren oder Ausnahmen erkennen.
```suggestion
* **Unüberwachtes Training (Unsupervised Training)** – Hier liegen keine Ergebnisse vor, die Modelle können Daten gruppieren oder Ausnahmen erkennen.
```

2021-02-16 09:52 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Dabei versuchen aktuelle Generation die "besten" oder auch "stärksten" Gene an ihre Nachfolger zu vererben, damit diese eine größtmögliche Überlebens-Chance erhalten.
```suggestion
Dabei versuchen aktuelle Generation die "besten" oder auch "stärksten" Gene an ihre Nachfolger zu vererben, damit diese eine größtmögliche Überlebenschance erhalten.
```

2021-02-16 09:57 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Das können Größe und Gewicht sein oder aber Eigenschaften sein, die das Verhalten definieren.
```suggestion
Das können Größe und Gewicht sein oder aber Eigenschaften, die das Verhalten definieren.
```

2021-02-16 09:58 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Ein Individuum stellt einen eigenständigen Teilnehmer dar, der durch seine Genetik und sein Handeln, seine Fähigkeit unter Beweis stellen muss.
```suggestion
Ein Individuum stellt einen eigenständigen Teilnehmer dar, der durch seine Genetik und sein Handeln seine Fähigkeit unter Beweis stellen muss.
```

2021-02-16 09:59 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Eine Generation stellt die aktuelle Population dar.
```suggestion
Eine Generation stellt die Population zu einem bestimmten Zeitpunk dar.
```

2021-02-16 10:21 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Dabei werden die einzelnen Gewichte eines Neurons einer jeden Schicht aneinander gereiht, wie eine langgezogene DNA-Kette.
```suggestion
Dabei werden die einzelnen Gewichte eines Neurons einer jeden Schicht wie eine langgezogene DNA-Kette aneinander gereiht.
```

2021-02-16 10:23 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Anstatt im Vorfeld tausende von Spiele aufzuzeichnen, und damit ein klassisches neuronales Netz zu trainieren, wird das neuronale Netz beim Spielen ununterbrochen mit Daten versorgt und kann sich dur
```suggestion
Anstatt im Vorfeld tausende Spiele aufzuzeichnen und damit ein klassisches neuronales Netz zu trainieren, wird das neuronale Netz beim Spielen ununterbrochen mit Daten versorgt und kann sich durch die Genetik langsam verbessern.
```

2021-02-16 10:25 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Ein Spieler kann nun die Schlange beispielsweise mit der Tastatur steuern, die Richtung bestimmten und Punkte sammeln.
```suggestion
Ein Spieler kann nun die Schlange beispielsweise mit der Tastatur steuern, die Richtung bestimmen und Punkte sammeln.
```

2021-02-16 10:25 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Frisst die Schlange einen Apfel erhält sie einen Punkt und neue Lebensenergie.
```suggestion
Nach und nach tauchen in der Welt Äpfel auf.
Frisst die Schlange einen dieser Äpfel, erhält sie einen Punkt und neue Lebensenergie.
```

2021-02-16 10:28 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Damit die Anwendung dennoch überschaubar bleibt und dem Leser für eigene Studien angeboten werden kann, wurde die Anwendung als native Java-Anwendung mit einer simplen Swing-Oberfläche (Fat-Client) e
```suggestion
Damit die Anwendung dennoch überschaubar und verständlich bleibt, wurde die Anwendung als native Java-Anwendung mit einer simplen Swing-Oberfläche (Fat-Client) entwickelt.
```

2021-02-16 10:29 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Sonst nichts, keine Spielregeln und Hinweise, was eine Sinnvolle Aktion wäre.
```suggestion
Sie erhalten keine Spielregeln und Hinweise, was eine Sinnvolle Aktion wäre.
```

2021-02-16 10:30 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Im Laufe der Evolutionen und Generation passen sich die Netze immer besser dem Spiel an und generalisieren ihr Handeln.
```suggestion
Im Laufe der Evolutionen und Generationen passen sich die Netze immer besser dem Spiel an und generalisieren ihr Handeln.
```

2021-02-16 10:31 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +In vielen KI-Projekten ist die Post-Modell Phase einer der längsten Phasen.
```suggestion
In vielen KI-Projekten ist die Post-Modell Phase eine der längsten Phasen.
```

2021-02-16 10:31 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Nach etlichen Versuchen und Rückschlägen wurde für GenticSnake eine Netz-Architektur samt passender genetischer Algorithmen gefunden, so dass Verbesserungen erkennbar waren. Nach einigen Minuten und
```suggestion
Nach etlichen Versuchen und Rückschlägen wurde für GeneticSnake eine Netz-Architektur samt passender genetischer Algorithmen gefunden, so dass Verbesserungen erkennbar waren. Nach einigen Minuten und ca. 3000 Generationen mit jeweils 100 Schlangen wurden bereits 60 und mehr Äpfel in einem Durchlauf gefressen!
```

2021-02-16 10:32 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Während beim "klassischen" Training neuronaler Netze ganze Bildschirm-Szenen als lange Eingabevektoren in komplexe Netze genutzt werden, und diese dann Stundenlang rechnen und trainieren, reichen hie
```suggestion
Während beim "klassischen" Training neuronaler Netze ganze Bildschirm-Szenen als lange Eingabevektoren in komplexe Netze genutzt werden, und diese dann stundenlang rechnen und trainieren, reichen hier 30 Eingabewerte aus.
```

2021-02-16 10:33 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Auf der anderen Seite muss aber im Vorfeld und bei der Entwicklung der Algorithmen und des Models genau überlegt werden, welche Informationen bereitgestellt werden müssen, damit sich die Gene und dam
```suggestion
Auf der anderen Seite muss aber im Vorfeld und bei der Entwicklung der Algorithmen und des Modells genau überlegt werden, welche Informationen bereitgestellt werden müssen, damit sich die Gene und damit das Neuronale Netz verbessert.
```

2021-02-16 10:34 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Dazu gehört auch die Fitness-Funktion, die angibt welche die "beste" Schlange der aktuellen Generation ist.
```suggestion
Dazu gehört auch die Fitness-Funktion, die angibt, welche die "beste" Schlange der aktuellen Generation ist.
```

2021-02-16 10:34 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Dies bedeutet, dass der grundlegende Algorithmus und das gewählte Model Erfolge erziehlen, aber durch die Optimierung des Sourcecode die Geschwindigkeit der Anwendung erhöht und beim sogenannten Hype
```suggestion
Dies bedeutet, dass der grundlegende Algorithmus und das gewählte Modell Erfolge erzielen, aber durch die Optimierung des Sourcecode die Geschwindigkeit der Anwendung erhöht und beim sogenannten Hyperparameter-Tuning die Lernerfolge des Models verbessert werden können.
```

2021-02-16 10:35 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Die KI-Plattform stellt Benutzern unterschiedliche Anwendungsfälle der KI in einer benutzerfreundlichen nicht technischen Web-Anwendung dar.
```suggestion
Die KI-Plattform stellt Benutzern unterschiedliche Anwendungsfälle der KI in einer benutzerfreundlichen, nicht technischen Web-Anwendung dar.
```

2021-02-16 10:36 UTC, jo2 commented on _posts/2021-02-15-Intelligenz-vererben.md
> +Bei adesso wird seit 2020 das Studentenprojekt "KI-Plattform" realisiert.
Hast du einen Link zu der Plattform oder ist die nicht von Extern erreichbar, sodass eine Erwähnung im Block nicht sinnvoll wäre?

2021-02-16 10:40 UTC, jo2 requested changes
Der Artikel liest sich schon sehr gut! Ein paar Kleinigkeiten habe ich noch angemerkt. Außerdem: 
* Bitte achte generell auf eine einheitliche Schreibweise von neuronalen Netzen und Neuronalen Netzen
* Bitte ändere den Ordnerpfad in Intelligenz_vererben (ohne Leerzeichen), bei uns in der Preview funktioniert das zwar, aber im richtigen Blog kann das zu Problemen führen.

2021-02-16 13:16 UTC, jo2 approved these changes

2021-02-16 13:16 UTC, jo2 commented
@acetous machst du noch eine inhaltliche Review?

2021-03-15 08:28 UTC, acetous approved these changes

2021-03-15 08:30 UTC, merged