Wartbarkeit von Software Teil 3 - Qualität und Automatisierung
adessoAG/devblog pull request #195
Opened 2021-03-23 09:56 UTC by ThiloLange

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-03-29 06:37 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Hierzu gibt es unterschiedliche Open-Source Werkzeuge (z.B. Sonarqube, ESLint) für verschiedene Programmiersprachen, die zu diesem Zweck eingesetzt werden können.
```suggestion
Hierzu gibt es unterschiedliche Open-Source Werkzeuge (z.B. Sonarqube, ESLint) für verschiedene Programmiersprachen.
```
oder
```suggestion
Es gibt unterschiedliche Open-Source Werkzeuge (z.B. Sonarqube, ESLint) für verschiedene Programmiersprachen, die zu diesem Zweck eingesetzt werden können.
```

2021-03-29 06:39 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Abweichungen von der Standardkonfiguration, wie z.B. der Ausschluss von bestimmten Prüfregeln, müssen dann mit einer kurzen Begründung dokumentiert werden.
```suggestion
Abweichungen von der Standardkonfiguration wie z.B. der Ausschluss von bestimmten Prüfregeln müssen dann mit einer kurzen Begründung dokumentiert werden.
```

2021-03-29 06:43 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Die Prüfung der Codequalität sollte in diesem Fall als separater Schritt in die Definition of Done und in die Review-Checkliste aufgenommen werden, um diese fest in den Entwicklungsprozess zu veranke
```suggestion
Die Prüfung der Codequalität sollte in diesem Fall als separater Schritt in die Definition of Done und in die Review-Checkliste aufgenommen werden, damit die Codequalität fest in den Entwicklungsprozess verankert wird.
```

2021-03-29 06:44 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +* Keine Code Smells vom Typ “Blocker”
```suggestion
* Keine Code Smells vom Typ "Blocker"
```

2021-03-29 06:44 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +* Keine Code Smells vom Typ “Critical“
```suggestion
* Keine Code Smells vom Typ "Critical"
```

2021-03-29 06:45 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +* Die Code Duplizierung liegt unter 5%
```suggestion
* Der Anteil von doppeltem Code liegt unter 5%
```

2021-03-29 06:48 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Der Aufwand, diese Prozesse zu Beginn eines Entwicklungsprojektes einmalig zu automatisieren und dann bei Konfigurationsänderungen anzupassen, ist meist geringer, als der Aufwand diese Prozesse immer
```suggestion
Der Aufwand, diese Prozesse zu Beginn eines Entwicklungsprojektes einmalig zu automatisieren und dann bei Konfigurationsänderungen anzupassen, ist meist geringer, als der Aufwand, diese Prozesse immer wieder manuell durchführen zu müssen.
Zusätzlich senkt eine Automatisierung das Risiko, Fehler bei der manuellen Durchführung der Prozesse zu begehen und stellt sicher, dass die Prozesse immer auf derselben Umgebung und Konfiguration durchgeführt werden.
```

2021-03-29 06:52 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Wie eingangs bereits erwähnt, bieten sich hierfür alle regelmäßig durchzuführenden, sich selten ändernden Prozesse an, die grundsätzlich auch automatisierbar sind.
Das automatisiertbar ist hier doppelt, bitte formuliere das anders. Bisher steht hier "für die AUtomatisierung eignen sich Proesse die automatisierbar sind".

2021-03-29 06:53 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Nach jedem Push eines Entwicklers muss der Quelltext des zugehörigen Branches von einem Build-Job automatisch kompiliert werden.
```suggestion
Nach jedem Push in der Entwicklung muss der Quelltext des zugehörigen Branches von einem Build-Job automatisch kompiliert werden.
```

2021-03-29 06:55 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Die Konfiguration des eingesetzten Werkzeuges sollte zu Beginn des Projektes zentral erstellt und an die Entwickler verteilt werden, so dass der gesamte Code immer auf die gleichen Qualitätsziele gep
```suggestion
Die Konfiguration des eingesetzten Werkzeuges sollte zu Beginn des Projektes zentral erstellt und an das gesamte Entwicklungsteam verteilt werden, so dass der gesamte Code immer auf die gleichen Qualitätsziele geprüft wird.
```

2021-03-29 06:56 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Falls die automatisierte Prüfung durch ein CI-Tool nicht möglich sein sollte, muss darauf geachtet werden, dass die Entwickler die Werkzeuge selbst einsetzen.
```suggestion
Falls die automatisierte Prüfung durch ein CI-Tool nicht möglich sein sollte, muss darauf geachtet werden, dass das gesamte Entwicklungsteam die Werkzeuge selbst einsetzt.
```

2021-03-29 07:18 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Das Ergebnis dieses Prozesses sind ein oder mehrere Artefakte, die auf dieselbe Art gebaut und zusammengestellt werden, wie die Release-Artefakte für das Produktisystem.
```suggestion
Das Ergebnis dieses Prozesses sind ein oder mehrere Artefakte, die auf dieselbe Art gebaut und zusammengestellt werden, wie die Release-Artefakte für das Produktivsystem.
```

2021-03-29 07:19 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Diese Version sollte anschließend automatisiert abgelegt werden (z.B. im Nexus oder Artifactory), um weiteren nachgelagerten Prozessen den Zugriff darauf zu ermöglichen.
```suggestion
Das erstellte Artefakt dieser Version sollte anschließend automatisiert abgelegt werden (z.B. im Nexus oder Artifactory), um weiteren nachgelagerten Prozessen den Zugriff darauf zu ermöglichen.
```

2021-03-29 07:22 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Im besten Fall können die mit dieser Version erstellten Artefakte als Release Candidate bezeichnet werden und nach erfolgreichen Tests direkt als Release ausgeliefert werden.
```suggestion
Im besten Fall können die mit dieser Version erstellten Artefakte als Release Candidate bezeichnet und nach erfolgreichen Tests direkt als Release ausgeliefert werden.
```

2021-03-29 07:27 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Zusätzlich sollte ein weiterer Job regelmäßig nach jedem Release eine Umgebung mit der aktuell in Produktion ausgerollten Version bereitstellen, um hierauf jederzeit gemeldete Fehler nachstellen zu k
```suggestion
Zusätzlich sollte ein weiterer Job regelmäßig nach jedem Release eine Umgebung mit der aktuell in Produktion ausgerollten Version bereitstellen, um hierauf jederzeit gemeldete Fehler nachstellen und Hotfixes bearbeiten zu können.
```

2021-03-29 07:34 UTC, jo2 commented on _posts/2021-03-15-wartbarkeit-von-software-teil-3.md
> +Außerdem haben wir anhand eines Beispiel-Projektes gezeigt, welche Prozesse automatisiert werden sollten, um die Produktivität bei der Entwicklung zu erhöhen und dabei Fehler zu vermeiden.
Überarbeite bitte dein Fazit etwas. Du schreibst hier hauptsächlich, wie Code-Qualität gewärleistet werden kann und nicht, aus welchen messbaren Kriterien sich Code-Qualität ergibt. Außerdem erwarte ich Beispiel-Code, wenn von einem Beispiel-Projekt die Rede ist. Der Abschnitt zu CI/CD liest sich ein bisschen, als würdest du ein Jenkins-File Job für Job beschreiben. Gib hier dann doch eine entsprechende Datei als Beispiel an, hangel dich daran entlang und gib Verweise auf den Code.

2021-03-29 09:27 UTC, jo2 requested changes
Der Artikel liest sich schon recht gut. Einige Sachen habe ich noch angemerkt. Achte bitte außerdem auf die einheitliche Schreibweise von CI/CD und Code-Qualität.

Für das PDF:
* Z. 1: Komma nach "ist es"
* Z. 6: Als Maß gilt dabei der gesunde Menschenverstand
* Z. 8: Komma nach "Prozesses"
* 1.1. erster Spigelstrich: Liste der Anwendungsfälle mit jeweils mindestens 2-3 Sätzen Beschreibung
* 1.3. Entwicklungsdokumentation statt Entwicklerdokumentation (im ganzen Absatz)
* 1.3. 6. Spiegelstrich: Branchmodell, das n fehlt
* 2.2. Kategorie A: Sie sind dauerhaft in Verwendung
* 2.3. Z. 2: nicht-funktionalen
* 2.3. Z. 4: bleiben im vorgegebenen Bereich
* 2.4. Z. 2: nicht-funktionalen
* 4.1. Z. 1: ein Bereich auf dem zentralen Build-Server

2021-03-29 11:56 UTC, ThiloLange commented
Hallo @jo2 , vielen Dank für Dein Review... ich habe soweit alle Deine Korrekturen, Anmerkungen und Vorschläge umgesetzt. Wir finden kurzfristig keine Zeit, den Abschnitt CI/CD auf ein Beispiel-Jenkinsfile umzuarbeiten. Es wäre eine gute Idee, das war jedoch initial für die Reihe so nicht vorgesehen. Wir haben in den ersten beiden Teilen ebenfalls keine konkreten Code-Beispiele, da wir die Entwicklungsprojekte eher organisatorisch aufschlauen bzw. erinnern wollten, woran grundsätzlich zu denken ist. Ich habe das Fazit entsprechend angepasst. Schöne Grüße, Thilo

2021-03-30 06:44 UTC, jo2 approved these changes

2021-03-30 06:44 UTC, jo2 commented
@acetous machst du noch eine inhaltliche Review?

2021-04-30 08:09 UTC, acetous approved these changes

2021-04-30 08:11 UTC, merged