2021-03-29-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung
adessoAG/devblog pull request #196
Opened 2021-04-26 08:04 UTC by viktor-mucha

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-05-03 12:47 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Von zentraler Bedeutung für die Softwareentwicklung ist die Modellierung der Anwenderdomäne.
```suggestion
Von zentraler Bedeutung für die Softwareentwicklung ist die Modellierung der Anwendungsdomäne.
```
oder
```suggestion
Von zentraler Bedeutung für die Softwareentwicklung ist die Modellierung der Fachdomäne.
```

2021-05-03 12:48 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +In dem adesso Blog _Herausforderungen in der Domänenmodellierung_ werden einige Herausforderungen in der Domänenmodellierung nach DDD beschrieben.
Kannst du den Post hier verlinken?

2021-05-03 13:37 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Zudem wird auf eine mögliche hohe Domänen-Komplexität hingewiesen.
```suggestion
Zudem wird auf die Möglichkeit einer hohen Domänenkomplexität hingewiesen.
```

2021-05-03 13:38 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Zudem wird auf eine mögliche hohe Domänenkomplexität hingewiesen.
```suggestion
Zudem wird auf die Möglichkeit einer hohen Domänenkomplexität hingewiesen.
```

2021-05-03 13:39 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Weiterhin wird am Beispiel dargelegt, wie die Werkzeuge angewendet werden können.
Genau diese Aussagen triffst du bereits in Zeile 022. Bitte ändere diese Zeilen entsprechend oder entferne sie.

2021-05-03 13:39 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Dies sind insbesondere die Entwickler, die das fachliche Modell erstellen und die Domänenexperten, die zur Anforderungsanalyse zur Verfügung stehen.
```suggestion
Dies sind insbesondere die Teams aus der Entwicklung, die das fachliche Modell erstellen, und der Domänenexpertise, die zur Anforderungsanalyse zur Verfügung stehen.
```

2021-05-03 13:40 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Sowohl die Domänenexperten, als auch die Entwickler, müssen ein gemeinsames Verständnis für die fachlichen Eigenschaften einer Reisebuchung haben.
```suggestion
Sowohl die Teams aus der Entwicklung als auch aus der Domänenexpertise müssen ein gemeinsames Verständnis für die fachlichen Eigenschaften einer Reisebuchung haben.
```

2021-05-03 13:40 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Die _Ubiquitous Language_ kann durch wiederkehrenden Meetings zwischen den Domänenexperten und den Entwicklern aufgebaut werden.
Gehe bitte noch etwas näher darauf ein, wie die Ubiquitous Language entsteht. Sie bildet sich ja aus den Gemeinsamkeiten in der Kommunikation zwischen Experten auf vollkommen verschiedenen Gebieten. Da wäre es gut zu wissen, wie eine einheitliche Sprache erreicht werden kann.

2021-05-03 13:41 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +In DDD wird in diesem Fall die Unterteilung in einzelne Teilbereiche empfohlen, die als _Subdomains_ bezeichnet werden.
```suggestion
Ab einer gewissen Größe und Komplexität wird auch die Modellierung mit DDD zunehmend komplexer.
Für diesen Fall wird in DDD die Unterteilung in einzelne Teilbereiche empfohlen, die als _Subdomains_ bezeichnet werden.
```

2021-05-03 13:41 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +_Entities_ haben nun in der Fachlichkeit eine eindeutige Identität, deren Eigenschaften in der Regel veränderbar sind.
```suggestion
_Entities_ haben in der Fachlichkeit eine eindeutige Identität, deren Eigenschaften in der Regel veränderbar sind.
```
Außerdem: Meinst du hier, dass die Eigenschaften der Entity verändert werden können, oder dass, der Wert des Identitätsattributs verändert werden kann? Den Satz musst du umforlmulieren.

2021-05-03 13:42 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Ein _Verkehrsmittel_ habe die Eigenschaften _Verkehrs-Typ_, _Start-Ziel_ und _End-Ziel_.
```suggestion
_Verkehrsmittel_ haben die Eigenschaften _Verkehrs-Typ_, _Start-Ziel_ und _End-Ziel_.
```
oder
```suggestion
Ein _Verkehrsmittel_ hat die Eigenschaften _Verkehrs-Typ_, _Start-Ziel_ und _End-Ziel_.
```

2021-05-03 13:42 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Die lose Kopplung wird dadurch erreicht, dass nur ein _Aggregate-Root_ für Abhängigkeiten außerhalb des _Aggregates_ verwendet wird.
```suggestion
Die lose Kopplung wird dadurch erreicht, dass nur das _Aggregate-Root_ für Abhängigkeiten außerhalb des _Aggregates_ verwendet wird.
```

2021-05-03 13:43 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Eine mögliche hohe Domänenkomplexität wird durch Verwendung mehrerer _Subdomains_ begegnet.
```suggestion
Der Möglichkeit einer hohen Domänenkomplexität wird mit Verwendung mehrerer _Subdomains_ begegnet.
```

2021-05-03 13:46 UTC, jo2 requested changes
Der Artikel liest sich schon sehr gut. Ein paar Sachen habe ich noch angemerkt. Außerdem:
* Achte bitte auf gendergerechte Formulierungen. Ich habe zu Beginn einige Stellen angemerkt, du müsstest aber nochmal deinen ganzen Text überarbeiten, da da noch einiges zu tun ist.
* Die Namenswahl bei Start und Ziel bei einer Reisebuchung und einem Verkehrsmittel (z.B. Start-Ziel) ist mMn. nicht so gut gelungen, verwende hier doch jeweils Startpunkt und Endpunkt bzw. Zielpunkt.

2021-05-17 06:45 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Es wird die Notwendigkeit für ein gemeinsames Domänenverständnis bei den Teilnehmerinnen und Teilnehmern eines Projekts aufgezeigt.
```suggestion
Es wird die Notwendigkeit für ein gemeinsames Domänenverständnis bei innerhalb des Projektteams aufgezeigt.
```
klingt, finde ich, runder, kannst du aber auch so lassen wie du es hattest

2021-05-17 06:47 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Die Begriffe und Funktionen können wir unter den Mitarbeiterinnen und Mitarbeitern bekannt machen, die in der Softwareentwicklung beteiligt sind.
```suggestion
Die Begriffe und Funktionen können wir im Entwicklungsteam bekannt machen.
```
gleiches wie oben

2021-05-17 06:50 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Dies sind insbesondere die Teams aus der Entwicklung, die das fachliche Modell erstellen, und die Teams aus der Fachabteilung mit Domänenexpertise, die zur Anforderungsanalyse zur Verfügung stehen.
```suggestion
Die Begriffe und Funktionen werden dann in die einzelnen Teams, insbesondere die Teams aus der Entwicklung, die das fachliche Modell erstellen, und die Teams aus der Fachabteilung mit Domänenexpertise, die zur Anforderungsanalyse zur Verfügung stehen, gegeben.
```
Nach der Umstellung passt die Verbindung zwischen den beiden Sätzen nicht mehr, der obere Satz ist quasi doppelt.

2021-05-17 06:56 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Die _Ubiquitous Language_ kann durch wiederkehrenden Meetings zwischen den Teams aus der Fachabteilung und den Teams aus der Entwicklung aufgebaut werden.
```suggestion
Die _Ubiquitous Language_ kann durch wiederkehrenden Meetings zwischen den Teams aus der Fachabteilung und der Entwicklung aufgebaut werden. 
```

2021-05-17 07:02 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +In unserem vereinfachten Beispiel dient das Element lediglich zu optionalen Planungszwecken für den Kunden.
```suggestion
In unserem vereinfachten Beispiel dient das Element lediglich zu optionalen Planungszwecken in der Endanwendung.
```

2021-05-17 07:03 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Die Fachabteilung benötigt keine eindeutige Identifikation und das _Verkehrsmittel_ kann als _Value_ modelliert werden.
```suggestion
Die Fachabteilung benötigt hier keine eindeutige Identifikation und das _Verkehrsmittel_ kann als _Value_ modelliert werden.
```

2021-05-17 07:17 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Jedoch ist auch möglich, dass eine _Entity_ oder ein _Value_ nur dann fachlich relevant ist, wenn bereits eine andere _Entity_ betrachtet wird.
```suggestion
Jedoch ist es auch möglich, dass eine _Entity_ oder ein _Value_ nur dann fachlich relevant ist, wenn bereits eine andere _Entity_ betrachtet wird.
```

2021-05-17 07:20 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Die Verwendung von _Aggregates_ ermöglicht eine fachliche Gruppierung der Domänenelemente, sowie eine lose Kopplung dieser innerhalb einer _Subdomain_.
```suggestion
Die Verwendung von _Aggregates_ ermöglicht eine fachliche Gruppierung der Domänenelemente sowie eine lose Kopplung dieser innerhalb einer _Subdomain_.
```

2021-05-17 07:21 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Außerdem wird die fachliche Konsistenz erhöht, da eine Invarianten-Prüfung in den _Aggregates_ angewandt wird.
```suggestion
Außerdem wird die fachliche Konsistenz erhöht, da eine Invariantenprüfung in den _Aggregates_ angewandt wird.
```

2021-05-17 07:21 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +In diesem Blog wurden wiederkehrende Herausforderungen in der Domänenmodellierung nach DDD aufgegriffen.
```suggestion
In diesem Blogartikel wurden wiederkehrende Herausforderungen in der Domänenmodellierung nach DDD aufgegriffen.
```

2021-05-17 07:23 UTC, jo2 requested changes
Ein paar Kleinigkeiten habe ich noch angemerkt, ansonsten liest sich der Artikel schon sehr gut.

2021-05-25 06:40 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +Es kann aber auch zu Ergänzungen neuer Begriffe und Funktionen kommen.
```suggestion
Es kann aber auch zur Ergänzung neuer Begriffe und Funktionen kommen.
```

2021-05-25 06:41 UTC, jo2 commented on _posts/2021-05-02-Adressierung_von_Herausforderungen_in_der_Domaenenmodellierung.md
> +So kann sich im Verlaufe der Gespräche unseres Beispiels herausstellen, dass ein _Verkehrsmittel_ zu Planungszwecken relevant sein kann.
```suggestion
So kann sich im Verlauf der Gespräche unseres Beispiels herausstellen, dass ein _Verkehrsmittel_ zu Planungszwecken relevant sein kann.
```

2021-05-25 06:41 UTC, jo2 requested changes
Zwei Kleinigkeiten habe ich noch angemerkt, danach ist der Artikel von meiner Seite aus in Ordnung.

2021-05-25 06:47 UTC, jo2 submitted a review, later dismissed

2021-06-16 11:36 UTC, acetous approved these changes

2021-06-16 11:37 UTC, merged