Konvertierung einer REST API zu einer SOAP Schnittstelle mithilfe von Kong
adessoAG/devblog pull request #198
Opened 2021-05-10 11:09 UTC by DanielKraft

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [x] Rechtschreibung korrigiert
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
  - [x] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-05-17 07:51 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Zum Beispiel eine REST API, da diese heutzutage häufig verwendet wird.
```suggestion
Um diese Probleme zu vermeiden, könnte man für den Service nur eine Schnittstelle implementieren, zum Beispiel eine REST API, da diese heutzutage häufig verwendet wird.
```

2021-05-17 07:51 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Für die Realisierung beider Schnittstellen wird eine [Kong API Gateway](https://konghq.com/kong/) Instanz mit dem Kong Plugin [soap2rest](https://github.com/adessoAG/kong-plugin-soap2rest) sowie ein
```suggestion
Für die Realisierung beider Schnittstellen wird ein [Kong API Gateway](https://konghq.com/kong/) mit dem Kong Plugin [soap2rest](https://github.com/adessoAG/kong-plugin-soap2rest) sowie ein REST Service benötigt.
```

2021-05-17 07:52 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Angenommen, die nutzende Person stellt an die SOAP Schnittstelle folgende Anfrage.
```suggestion
Angenommen, folgende Anfrage wird an die SOAP Schnittstelle gestellt.
```

2021-05-17 07:52 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Diese Antwort wird der nutzenden Person zurückgegeben.
```suggestion
Anschließend wird diese Antwort vom Plugin in gültiges XML umgewandelt und in eine SOAP Antwort eingesetzt, welche anschließend zurückgegeben wird.
```

2021-05-17 07:52 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Sie wird nur einmal vor der ersten Anfrage an die SOAP Schnittstelle ausgeführt, um die Schnittstelle zu konfigurieren.
Gehört die Generierung der Schnittstelle dann zur Berechnungszeit der Antwort? Wie lange dauert die Generierung ca? Wie wirkt sich das auf die Antwortzeit für diese Anfrage aus?

2021-05-17 07:53 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Dabei werden den SOAP Operationen die passenden Pfade der REST API zugeordnet.
Wie erfolgt die Zuordnung? Muss das manuell gemacht werden oder geht das automatisch?

2021-05-17 07:53 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Damit die HTTP-Header bei der Weiterleitung der Anfragen an die REST API korrekt gesetzt werden können.
```suggestion
Außerdem werden jeder Operation die passenden Content-Types zugeordnet, damit die HTTP-Header bei der Weiterleitung der Anfragen an die REST API korrekt gesetzt werden können.
```

2021-05-17 07:54 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Für den Lasttest wurden die gleichen Anfragen wie beim zu vorigen Performancetest verwendet.
Dieser Satz passt so nicht, den müsstest du umformulieren.

2021-05-17 07:55 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Auf den ersten Blick fällt auf, dass bei vielen parallelen Anfragen die SOAP Schnittstelle stärker darunter leidet als die REST API.
```suggestion
Auf den ersten Blick fällt auf, dass die SOAP Schnittstelle bei vielen parallelen Anfragen längere Antwortzeiten aufweist, als die REST API.
```

2021-05-17 08:22 UTC, jo2 requested changes
Der Artikel liest sich schon recht gut, ein paar Sachen habe ich noch angemerkt. Außerdem:
* Achte generell bitte auf eine einheitliche Schreibweise zusammengesetzter Begriffe (z.B. SOAP-Schnittstelle / SOAP Schnittstelle). Ich würde ersteres bevorzugen, letzteres geht aber auch.
* Achte bitte durchgehend auf gendergerechte Formulierungen. Je nach Kontext kannst du dazu verschiedene Formulierungen verwenden, bspw. eine Formulierung im Passiv oder eine Formulierung mit "wir".
* Irgendwas scheint mit der Generierung der PR Vorschau nicht zu klappen, wenn du deine Änderungen gemacht hast gucke ich mir das nochmal an.

2021-05-17 08:36 UTC, jo2 commented
Das mit der Deploy Preview ist gelöst, Netlify hat die Seitenstruktur umgebaut und der Link zur Preview befindet sich nun auf einer anderen Seite.

2021-05-17 10:03 UTC, jo2 commented on _posts/2021-04-12-Konvertierung-einer-REST-API-zu-einer-SOAP-Schnittstelle-mithilfe-von-Kong.md
> +Diese Abbildung zeigt den Fall, dass eine Anfrage über die SOAP-Schnittstelle stellt wird.
```suggestion
Diese Abbildung zeigt den Fall, dass eine Anfrage über die SOAP-Schnittstelle gestellt wird.
```

2021-05-17 10:07 UTC, jo2 requested changes
Eine Sache ist noch drin, danach ist der Artikel von meiner Seite aus fertig.

2021-05-17 10:40 UTC, jo2 approved these changes

2021-05-17 10:41 UTC, jo2 commented
@acetous machst du noch eine inhaltliche Review?

2021-06-18 14:23 UTC, acetous approved these changes

2021-06-18 14:24 UTC, merged