Diversitäts Blog Beitrag
adessoAG/devblog pull request #199
Opened 2021-05-10 14:29 UTC by VivienEmily

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-05-10 14:42 UTC, VivienEmily commented
Am 18. Mai ist der Diversity Tag, vielleicht passt es ja den Beitrag an diesem Tag zu posten :)

2021-05-17 08:37 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Diese Vielfalt lässt sich durch weitere Dimensionen ergänzen und aufteilen. Weitere Informationen bietet die Seite [Charta der Vielfalt](https://www.charta-der-vielfalt.de).
Hier reicht entweder das Bild oder die Verlinung.

2021-05-17 08:38 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Softwareentwicklung entwickelt sich ständig weiter und neue Technologien rücken in den Fokus, wie z.B Künstliche Intelligenz (KI).
```suggestion
Softwareentwicklung entwickelt sich ständig weiter und neue Technologien rücken in den Fokus wie z.B. künstliche Intelligenz (KI). 
```

2021-05-17 08:39 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Wo vorher in der Softwareentwicklung in diesem Ausmaß keine unbewussten kognitiven Verzerrungen (Unconscious Bias) erkennbar waren, wird sie gerade bei KI Software deutlich.
```suggestion
Wo vorher in der Softwareentwicklung in diesem Ausmaß keine unbewussten kognitiven Verzerrungen (Unconscious Bias) erkennbar waren, werden sie gerade bei KI Software deutlich. 
```

2021-05-17 08:40 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +* Softwarelösungen, die nicht barrierefrei sind und z.B für Sehbehinderte nicht erreichbar
```suggestion
* Softwarelösungen, die nicht barrierefrei und z.B. für Sehbehinderte nicht erreichbar sind
```

2021-05-17 08:44 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Jedoch sollte ähnlich wie bei der IT-Sicherheit, die Anforderung der Sicherheit (der Daten) der Nutzenden, kein Luxusgut sein.
```suggestion
Jedoch sollte die Barrierefreiheit, ähnlich wie bei der IT-Sicherheit die Anforderung der Sicherheit (der Daten) der Nutzenden, kein Luxusgut sein. 
```

2021-05-17 08:44 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Keiner möchte in der Presse landen, mit der Schlagzeile, dass die angebotene Software, Webseite, etc. diskriminierend ist.
```suggestion
Keiner möchte in der Presse landen, mit der Schlagzeile, dass die angebotene Software, Webseite etc. diskriminierend ist. 
```

2021-05-17 08:48 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +So greift die KI Strategie der Bundesregierung zusammen mit Forschungsgruppen der Gesellschaft der Informatik und der Plattform lernende Systeme das Prinzip der Gerechtigkeit (Diskriminierung, Gleich
```suggestion
So greift die KI-Strategie der Bundesregierung zusammen mit Forschungsgruppen der Gesellschaft der Informatik und der Plattform lernende Systeme das Prinzip der Gerechtigkeit (Diskriminierung, Gleichheit etc.) auf und bietet verschiedene Vorschläge zu Gegenmaßnahmen an. 
```

2021-05-17 08:54 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +[Diversität und Vielfalt im Bereich der KI](https://www.plattform-lernende-systeme.de/files/Downloads/Publikationen/AG3_Whitepaper_EB_200831.pdf): Diversität und Vielfalt im Bereich der KI beziehen
```suggestion
[Diversität und Vielfalt im Bereich der KI](https://www.plattform-lernende-systeme.de/files/Downloads/Publikationen/AG3_Whitepaper_EB_200831.pdf): Diversität und Vielfalt im Bereich der KI beziehen sich sowohl auf diverse Teams, bestehend aus Entwicklerinnen und Entwicklern mit unterschiedlichen Perspektiven und Erfahrungshintergründen, als auch auf die Betrachtung der Zielgruppe als heterogene Gruppe. Auch die Einbindung von Perspektiven, die möglichst breit gesellschaftliche Strukturen abbilden, ist aus Perspektive der Diversität wichtig. Für das Training von KI-Systemen muss auf eine Repräsentierung der vielfältigen gesellschaftlichen Gruppen in den Trainingsdaten geachtet werden.
```

2021-05-17 08:54 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Die Beschreibung bezieht sich auf die Entwicklung von KI, jedoch können einige Punkte auch auf Software ohne KI Einsatz angewandt werden.
```suggestion
Die Beschreibung bezieht sich auf die Entwicklung von KI, jedoch können einige Punkte auch auf Software ohne KI-Einsatz angewandt werden. 
```

2021-05-17 08:58 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Aktuell ist es leider kaum möglich, alle Diversitätsdimensionen in einem Team zusammenzustellen, dafür gibt es z.B noch zu wenig Frauen in der Softwareentwicklung.
```suggestion
Aktuell ist es leider kaum möglich, alle Diversitätsdimensionen in einem Team zusammenzustellen, dafür gibt es z.B. noch zu wenig Frauen in der Softwareentwicklung. 
```

2021-05-17 08:59 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Wenn wir beispielsweise auch barrierefreie Software entwickeln möchten/müssen/wollen, wäre es ebenfalls eine Option, Menschen mit einer Sehbeeinträchtigung oder -behinderung als Tester zu beschäftige
Tester bitte gendern

2021-05-17 08:59 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Wir als IT-Dienstleister entwickeln maßgeschneiderte Software für unsere Kunden und erfüllen dahingehend ihre Wünsche und Anforderungen.
Kunden bitte gendern

2021-05-17 09:00 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +## Die Diversitäts Expertin, der Diversitäts Experte
```suggestion
## Die Diversitätsexpertin, der Diversitätsexperte
```

2021-05-17 09:00 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Eine andere Möglichkeit wäre es, dass eine Diversitäts Expertin oder ein Experte, den Prozess der Softwareentwicklung begleitet.
```suggestion
Eine andere Möglichkeit wäre es, dass eine Diversitätsexpertin oder -experte den Prozess der Softwareentwicklung begleitet. 
```

2021-05-17 09:01 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Dafür ist eine Diversitäts Richtlinie oder Guideline hilfreich.
```suggestion
Dafür ist eine Diversitätsrichtlinie oder -guideline hilfreich. 
```

2021-05-17 09:01 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Diese kann Handlungsempfehlungen und Entscheidungsmöglichkeiten zu Beginn des Softwareentwicklungsprozess aufzeigen.
```suggestion
Diese kann Handlungsempfehlungen und Entscheidungsmöglichkeiten zu Beginn des Softwareentwicklungsprozesses aufzeigen. 
```

2021-05-17 09:02 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Solche Richtlinien und Guidelines können sich aus den verschiedenen Vielfältigkeitsdimensionen ableiten lassen und auch in Anforderungen einfließen.
```suggestion
Solche Richtlinien und Guidelines können sich aus den verschiedenen Vielfältigkeitsdimensionen ableiten lassen und auch in die Anforderungen einfließen. 
```

2021-05-17 09:03 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Im Bereich der KI Entwicklung gibt es bereits konkrete Vorschläge für Richtlinien, die der Bund gemeinsam mit der [Plattform lernender Systeme](https://www.plattform-lernende-systeme.de/files/Downloa
```suggestion
Im Bereich der KI-Entwicklung gibt es bereits konkrete Vorschläge für Richtlinien, die der Bund gemeinsam mit der [Plattform lernender Systeme](https://www.plattform-lernende-systeme.de/files/Downloads/Publikationen/AG3_Whitepaper_EB_200831.pdf) erarbeitet hat. 
```

2021-05-17 09:06 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Von Anfang an Diversitätsdimensionen in der Softwareentwicklung zu denken, reduziert auch Kosten, die für evtl. nachträgliche Änderungen in der Software aufkommen könnten. Eine Software nachträglich
```suggestion
Von Anfang an Diversitätsdimensionen in der Softwareentwicklung zu denken, reduziert auch Kosten, die für evtl. nachträgliche Änderungen in der Software aufkommen könnten. Eine Software nachträglich an die Barrierefreiheit anzupassen ist mit höherem Aufwand verbunden. 
```

2021-05-17 09:11 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Zudem werden durch verschiede Perspektiven und breiteres Wissen, sowie verschiedenen Lösungsvorschlägen ein besseres Verständnis für Zielgruppen erzielt und somit auch eine bessere Softwarelösung für
```suggestion
Zudem werden durch verschiede Perspektiven und breiteres Wissen sowie verschiedenen Lösungsvorschlägen ein besseres Verständnis für Zielgruppen erzielt und somit auch eine bessere Softwarelösung für die Kunden. 
```
Kunden bitte gendern

2021-05-17 09:11 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Der ethische Wert des Schutzes der Privatheit und der Persönlichkeit sollte im Vordergrund stehen, daher arbeiten IT Sicherheitsarbeitsgruppen, Recht und Ethikrat in diesem Thema zusammen.
```suggestion
Der ethische Wert des Schutzes der Privatheit und der Persönlichkeit sollte im Vordergrund stehen, daher arbeiten IT-Sicherheitsarbeitsgruppen, Recht und Ethikrat in diesem Thema zusammen. 
```

2021-05-17 09:16 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Zudem haben die Arbeitsgruppen lernender Systeme Umfragen in Unternehmen durchgeführt, bei denen bereits heute viele von ihnen Wert auf einen ethisch basierten Entwicklungs- und Anwendungsprozess von
Ist der Name der Arbeitsgruppe hier ein Eigenename? Dann müsstest du die Schreibweise wahrscheinlich auf lernende anpassen.

2021-05-17 09:18 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +Zudem kamen viele zu dem Entschluss, dass die Umsetzung ethischer Werte für viele Unternehmen kein Wettbewerbshindernis ist, sondern vielmehr zum Verkaufsargument werden kann.
Bezieht sich das viele auf die befragten Unternehmen? Dann müsste es im zweiten Teil des Satzes für sie heißen. Wenn nicht, auf was bezieht sich das viele dann?

2021-05-17 09:27 UTC, jo2 commented on _posts/2021-05-18-Diverstaet-in-der-Softwareentwicklung.md
> +* Das Buch „Unsichtbare Frauen: Wie eine von Daten beherrschte Welt die Hälfte der Bevölkerung ignoriert“ von Caroline Criado-Perez
```suggestion
* Der Film "Coded Bias" auf Netflix 
* Das Buch "Keine Panik, ist nur Technik: Warum man auf Algorithmen super tanzen kann und wie wir ihnen den Takt vorgeben" von Kenza Ait Si Abbou
* Das Buch "Unsichtbare Frauen: Wie eine von Daten beherrschte Welt die Hälfte der Bevölkerung ignoriert" von Caroline Criado-Perez
```

2021-05-17 09:28 UTC, jo2 requested changes
Der Artikel liest sich schon recht gut, einige Sachen habe ich noch angemerkt.

2021-05-17 11:22 UTC, jo2 submitted a review, later dismissed

2021-05-17 11:50 UTC, VivienEmily commented
Wie ich sehe hast du alle Anmerkungen doch schon eingearbeitet, insbesondere die Stellen, die ich beim gendern übersehen habe. Ist für mich noch etwas zu tun?

2021-05-17 12:22 UTC, jo2 commented
Du kannst über meine Änderungen nochmal drüber gucken, ob du da noch was verändern möchtest, ansonsten ist nichts mehr zu tun. Ich hatte das auf Drängen von Sebastian hin gemacht, er meinte der Artikel soll morgen veröffentlicht werden und er wusste nicht, ob du heute noch zur Korrektur kommst.

2021-05-17 12:39 UTC, VivienEmily commented
Für mich passt das so. Ich hätte den Link zur Charta der Vielfalt noch dringelassen, da es dort generell noch mehr Informationen zu Diversität gibt, als nur das Bild.

2021-05-17 14:54 UTC, acetous approved these changes

2021-05-17 15:17 UTC, merged