Stencil Einführung Artikel
adessoAG/devblog pull request #200
Opened 2021-05-15 16:47 UTC by parideis

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [:heavy_check_mark: ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ]:heavy_check_mark: [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [:heavy_check_mark: ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [:heavy_check_mark: ] "title" vergeben
    - [ :heavy_check_mark:] "author" angegeben
    - [:heavy_check_mark: ] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [:heavy_check_mark: ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [:heavy_check_mark: ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [:heavy_check_mark: ] Rechtschreibung korrigiert
  - [ :heavy_check_mark:] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [:heavy_check_mark: ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [:heavy_check_mark: ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ :heavy_check_mark:] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ :heavy_check_mark:] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-05-17 09:30 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +In diesem Artikel werfen wir gemeinsam einen Blick auf Stencil und vergleichen welche Vorteile diese Compiler-Lösung zu den gängigen Laufzeit-JavaScript-Frameworks bietet.
```suggestion
In diesem Artikel werfen wir gemeinsam einen Blick auf Stencil und vergleichen, welche Vorteile diese Compiler-Lösung zu den gängigen Laufzeit-JavaScript-Frameworks bietet. 
```

2021-05-17 09:31 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Anschließend werden wir eine Stencil-Umgebung aufsetzen und eine passende Komponente erstellen. Stencil stammt von den Ionic-Framework-EntwicklerInnen und auch große Unternehmen wie Apple, Amazon und
```suggestion
Anschließend werden wir eine Stencil-Umgebung aufsetzen und eine passende Komponente erstellen. Stencil stammt aus dem Hause Ionic und auch große Unternehmen wie Apple, Amazon und Microsoft nutzen Stencil in ihren Produkten.  
```

2021-05-17 09:32 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Dieser Artikel richtet sich an WebentwicklerInnen, die schon erste Erfahrungen mit JavaScript-Frameworks wie Angular und Vue oder der Bibliothek React gemacht haben.
```suggestion
Dieser Artikel richtet sich an alle, die schon erste Erfahrungen mit JavaScript-Frameworks wie Angular und Vue oder der Bibliothek React gemacht haben.
```

2021-05-17 09:33 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Mit Stencil lassen sich plattformunabhängige Web-Components generieren, die in allen [gängigen Frameworks eingebunden](https://stenciljs.com/docs/overview) werden können, sowie auf allen [aktuellen B
```suggestion
Mit Stencil lassen sich plattformunabhängige Web-Components generieren, die in allen [gängigen Frameworks eingebunden](https://stenciljs.com/docs/overview) werden können, sowie in allen [aktuellen Browsern](https://stenciljs.com/docs/browser-support) laufen.
```

2021-05-17 09:35 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Somit bietet Stencil eine neue Herangehensweise an eine beliebte Idee: die Erstellung schneller und funktionsreicher Anwendungen im Browser. Dabei machen sich die AnwenderInnen die Vorteile wichtiger
```suggestion
Somit bietet Stencil eine neue Herangehensweise an eine beliebte Idee: die Erstellung schneller und funktionsreicher Anwendungen im Browser. Dabei machen wir uns bei der Entwicklung die Vorteile wichtiger neuer Funktionen zu Nutzen, die nativ im Browser zur Verfügung stehen ( z.B. [Custom Elements v1](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements)). 
```

2021-05-17 09:35 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Hierdurch können EntwicklerInnen weitaus weniger Code ausliefern und schnellere Anwendungen erstellen, die mit allen Frameworks kompatibel sind.
```suggestion
Hierdurch können wir weitaus weniger Code ausliefern und schnellere Anwendungen erstellen, die mit allen Frameworks kompatibel sind. 
```

2021-05-17 09:36 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Die gängigen Frameworks wie Angular oder Bibliotheken wie React, brauchen zusätzlichen clientseitiges JavaScript, welches von Nutzende heruntergeladen und geparst werden muss, damit die Applikation f
```suggestion
Die gängigen Frameworks wie Angular oder Bibliotheken wie React brauchen zusätzliches clientseitiges JavaScript, welches von im Browser heruntergeladen und geparst werden muss, damit die Applikation funktioniert. 
```

2021-05-17 09:36 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Dennoch verzichtet Stencil nicht auf die beliebten Funktionen, die wir als EntwicklerInnen von den Frameworks gewöhnt sind.
```suggestion
Dennoch verzichtet Stencil nicht auf die beliebten Funktionen, die wir von den Frameworks gewöhnt sind. 
```

2021-05-17 09:37 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Im folgenden Abschnitt werden wir uns die einzelnen Funktionalitäten anschauen die Stencil bietet.
```suggestion
Im folgenden Abschnitt werden wir uns die einzelnen Funktionalitäten, die Stencil bietet, anschauen.
```

2021-05-17 09:37 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Durch **asynchrones Rendering** wird außerdem eine Möglichkeit geboten einen Platzhalter anzuzeigen, bis die Komponente eingebunden werden kann.
```suggestion
Durch **asynchrones Rendering** wird außerdem eine Möglichkeit geboten, einen Platzhalter anzuzeigen, bis die Komponente eingebunden werden kann. 
```

2021-05-17 09:37 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Diese Funktion ist stark angelehnt an der Implementation von React-„Fiber“.
```suggestion
Diese Funktion ist stark angelehnt an der Implementation von React-"Fiber". 
```

2021-05-17 09:38 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Stencil bietet des weiteren ein **reaktives Data-Binding** ein, sodass die Daten zwischen der Komponente und im DOM selbst reaktiv miteinander gebunden werden.
```suggestion
Stencil bietet des weiteren ein **reaktives Data-Binding** an, sodass die Daten zwischen der Komponente und dem DOM reaktiv miteinander verbunden werden. 
```

2021-05-17 09:39 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Ein weiteres für React-EntwicklerInnen bekanntes Feature ist **JSX**, welches eine XML-artige Syntax anbietet, die JavaScript-Code erstellt und von Typescript unterstützt wird.
```suggestion
Ein weiteres aus React bekanntes Feature ist **JSX**, welches eine XML-artige Syntax anbietet, die JavaScript-Code erstellt und von Typescript unterstützt wird.  
```

2021-05-17 09:48 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Nun sehen wir wie unser Projekt zum ersten Mal gebaut wird:
```suggestion
Nun sehen wir, wie unser Projekt zum ersten Mal gebaut wird:
```

2021-05-17 09:50 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Was in unserem Fall das h1-Element mit dem Inhalt “Willkommen” ist.
```suggestion
Was in unserem Fall das h1-Element mit dem Inhalt "Willkommen" ist.
```

2021-05-17 09:52 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Zum Schluss müssen wir im HTML unseren Custom-Element noch den Attribut *name* einfügen und einen Namen setzen:
```suggestion
Zum Schluss müssen wir im HTML unserem Custom Element noch das Attribut *name* hinzufügen und dessen Wert setzen:
```

2021-05-17 09:58 UTC, jo2 requested changes
Der Artikel ist sehr interessant und liest sich schon sehr gut. Ein paar Sachen habe ich noch angemerkt. Außerdem fände ich es noch interessant, wenn du kurz auf das Kompilat und die Unterschiede zwischen den nativ nutzbaren Custom Components und bspw. einer React- oder Vue-Komponente eingehen könntest.

2021-05-20 06:21 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Die gängigen Frameworks wie Angular oder Bibliotheken wie React brauchen zusätzliches clientseitiges JavaScript, welches von im Browser heruntergeladen und geparst werden muss, damit die Applikation
```suggestion
Die gängigen Frameworks wie Angular oder Bibliotheken wie React brauchen zusätzliches clientseitiges JavaScript, welches im Browser heruntergeladen und geparst werden muss, damit die Applikation funktioniert. 
```

2021-05-20 06:21 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Die gängigen Frameworks wie Angular oder Bibliotheken wie React brauchen zusätzliches clientseitiges JavaScript, welches von im Browser heruntergeladen und geparst werden muss, damit die Applikation
Sorry, mein Fehler.

2021-05-20 06:31 UTC, jo2 approved these changes

2021-05-20 06:33 UTC, jo2 requested changes
Eine Sache hab ich noch gefunden

2021-05-20 06:34 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Somit bietet Stencil eine neue Herangehensweise an eine beliebte Idee: die Erstellung schneller und funktionsreicher Anwendungen im Browser. Dabei machen wir uns bei der Entwicklung die Vorteile wich
```suggestion
Somit bietet Stencil eine neue Herangehensweise an eine beliebte Idee: die Erstellung schneller und funktionsreicher Anwendungen im Browser. Dabei machen wir uns bei der Entwicklung die Vorteile wichtiger neuer Funktionen zu Nutzen, die nativ im Browser zur Verfügung stehen (z.B. [Custom Elements v1](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements)). 
```

2021-05-20 13:13 UTC, parideis commented
Vielen Dank für den tollen Input! 🥳
Ich habe einen Vergleich mit Angular 11 Elements, React und Vue nachgereicht.

2021-05-20 15:44 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Die gängigen Frameworks wie Angular oder Bibliotheken wie React brauchen zusätzliches clientseitiges JavaScript, welches im Browser heruntergeladen und geparst werden muss, damit die Applikation funk
```suggestion
Die gängigen Frameworks wie Angular oder Bibliotheken wie React brauchen, anders als Stencil, zusätzliches clientseitiges JavaScript, welches im Browser heruntergeladen und geparst werden muss, damit die Applikation funktioniert. 
```

2021-05-20 15:45 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Die React Lösung ist mit 128kb zehn mal so groß, wie die mit Stencil und die Angular 11 Elements ist mit 176kb noch größer, als beide zusammen.
```suggestion
Die React Lösung ist mit 128kb zehnmal so groß, wie die Stencil-Komponente, die Komponente von Angular 11 Elements ist mit 176kb sogar noch deutlich größer.
```

2021-05-20 15:47 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +[Vergleich von Codierungsstil, Paketgröße und Leistung: https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/](https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/)
```suggestion
[Vergleich von Codierungsstil, Paketgröße und Leistung](https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/)
```
oder 
```suggestion
[https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/](https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/)
```

2021-05-20 15:48 UTC, jo2 requested changes
Bei den Änderungen habe ich nochmal drei kleine Sachen angemerkt.

2021-05-25 06:13 UTC, jo2 approved these changes

2021-05-25 06:13 UTC, jo2 commented
@acetous rechtschreibtechnisch passt der Artikel soweit.

2021-07-08 12:55 UTC, acetous requested changes

2021-07-08 12:55 UTC, acetous commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Die statische Seitengenerierung (**SSG**) bezeichnet das Erstellen und Rendern der Komponenten und Routen zur Build-Time, welches auch als Prerendering bekannt ist.
"Buid-Time" bitte auf Deutsch formulieren und englische Fachbegriffe dort wo nötig verwenden.

2021-07-08 12:55 UTC, acetous commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +__Stencil erfordert eine aktuelle LTS-Version von NodeJS und mindestens npm in der Version 6 oder höher.__
```suggestion
Stencil in Version ??? erfordert NodeJS in der LTS-Version ??? und npm in der Version 6 oder höher.
```
Die LTS-Version von NodeJS solltest Du noch konkretisieren. Zudem wird das ja irgendwo dokumentiert sein, worauf Du verlinken kannst. ;)

2021-07-08 12:55 UTC, acetous commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +![Stencil im Browser: Unser Komponente begrüßt uns mit den übergeben Namen](/assets/images/posts/Stencil-Einfuehrung/stencil-browser-3.png)
Kannst Du den Code bitte als Listing einbinden?

2021-07-08 12:55 UTC, acetous commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +![Stencil Code: Überblick über den generierten Code](/assets/images/posts/Stencil-Einfuehrung/stencil-code-1.png)
Den relevanten Code zeigst Du schon darüber. Kannst Du ggf. hier einfach einen größeren Codeblock einbinden und den Screenshot ersetzen?

2021-07-22 06:32 UTC, acetous commented
Hi @parideis! Wie besprochen warten wir noch mit der Veröffentlichung, damit Du das Testing-Thema einbauen kannst.

2021-09-01 10:37 UTC, parideis commented
> 
> 
> Hi @parideis! Wie besprochen warten wir noch mit der Veröffentlichung, damit Du das Testing-Thema einbauen kannst.

Testing Thema ist eingebaut :) 👍

2021-09-09 15:22 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Mit den Parameter “—watchAll” werden die Tests automatisch neu durchlaufen, sobald sich die Testdateien geändert haben.
```suggestion
Mit dem Parameter “—watchAll” werden die Tests automatisch neu durchgeführt, sobald sich die Testdateien geändert haben.
```

2021-09-09 15:25 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Daraufhin wollen wir testen, ob die Komponente den angegebenen Namen von dem Attribut korrekt begrüßt:
```suggestion
Daraufhin wollen wir testen, ob die Komponente den angegebenen Namen aus dem mitgegebenen Attribut ausliest und korrekt verwendet:
```

2021-09-09 15:25 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Mit den "durchdringenden"  Selektor ``>>>`` kann nach einem Objekt innerhalb des Shadow-root einer Komponente gesucht werden.
```suggestion
Mit dem "durchdringenden"  Selektor ``>>>`` kann nach einem Objekt innerhalb des Shadow-root einer Komponente gesucht werden.
```

2021-09-09 15:26 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Zum Schluss testen wir die Kombination aus den mitgegebenen Namen und der Kindkomponente:
```suggestion
Zum Schluss testen wir die Kombination aus dem mitgegebenen Namen und der Kindkomponente:
```

2021-09-09 15:27 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Im Vergleich zur direkten Verwendung von Custom Elements bietet Stencil zusätzliche APIs, die das Entwickeln schneller Komponenten vereinfachen.
Sind hier die Komponenten schnell oder ist vielmehr der Entwicklungsprozess schnell?

2021-09-09 15:28 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Im Gegensatz zu den beliebten JavaScript-Frameworks werden keine zusätzlichen Codelasten zur Laufzeit eingebunden, da 100% Webkomponenten zur Kompilierzeit generiert werden, die nativ vom Browser gen
```suggestion
Im Gegensatz zu den beliebten JavaScript-Frameworks werden keine zusätzlichen Codelasten zur Laufzeit eingebunden, da reine Webkomponenten zur Kompilierzeit generiert werden, die nativ vom Browser genutzt werden können. 
```

2021-09-09 15:28 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Durch die breite Browserkompatibilität und Möglichkeit in den beliebten Frameworks integriert zu werden, bietet sich Stencil als Tool an, um Design-Systeme bzw. Komponentenbibliotheken zu entwickeln.
```suggestion
Durch die breite Browserkompatibilität und die Möglichkeit, in die beliebten Frameworks integriert zu werden, bietet sich Stencil als Tool an, um Design-Systeme bzw. Komponentenbibliotheken zu entwickeln.
```

2021-09-09 15:29 UTC, jo2 commented on _data/authors.yml
> +  bio: "Denis Paris arbeitet bei adesso als Werkstudent in Köln und entwickelt Full-Stack JavaScript Applikationen. Er hat Erfahrung mit Angular, React, Stencil, Svelte und Vue gesammelt. In seiner F
```suggestion
  bio: "Denis Paris arbeitet bei adesso als Werkstudent in Köln und entwickelt Full-Stack-JavaScript-Applikationen. Er hat Erfahrung mit Angular, React, Stencil, Svelte und Vue gesammelt. In seiner Freizeit spielt er gerne Basketball 🏀 und hält JavaScript-Vorträge auf Meetups und Konferenzen."
```

2021-09-09 15:29 UTC, jo2 requested changes
Ein paar Kleinigkeiten sind noch drin, aber die Testmöglichkeiten sehen sehr gut und übersichtlich aus.

2021-09-12 07:47 UTC, parideis commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +Im Vergleich zur direkten Verwendung von Custom Elements bietet Stencil zusätzliche APIs, die das Entwickeln schneller Komponenten vereinfachen.
Sehr guter Punkt! :+1: 
Ich habe nun klar gemacht, dass der Entwicklungsprozess beschleunigt wird.

2021-09-13 12:44 UTC, parideis commented
@jo2 dein tolles Feedback wurde eingebaut! :)

2021-09-16 15:40 UTC, jo2 approved these changes

2021-09-16 15:40 UTC, jo2 commented
@acetous von meiner Seite aus ist der Artikel soweit in Ordung.

2021-09-16 16:39 UTC, jo2 commented on _posts/2021-05-15-Stencil-Einfuehrung.md
> +author:			parideis												    # Pflichtfeld. Es muss in der "authors.yml" einen Eintrag mit diesem Namen geben.
```suggestion
author_ids:			[parideis]												    # Pflichtfeld. Es muss in der "authors.yml" einen Eintrag mit diesem Namen geben.
```
Es gibt ein Update in der Schreibweise der Metadaten, genaueres dazu [hier](https://github.com/adessoAG/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#wichtig-update-23082021).

2021-09-16 16:40 UTC, jo2 requested changes
Eine Sache ist noch (relativ) neu, daran hatte ich garnicht gedacht.

2021-09-17 08:33 UTC, parideis commented
> 
> 
> Eine Sache ist noch (relativ) neu, daran hatte ich garnicht gedacht.

Habe die neue Autoren Syntax commited 👍

2021-09-27 06:16 UTC, jo2 approved these changes

2021-09-28 09:00 UTC, acetous approved these changes

2021-10-01 06:39 UTC, acetous approved these changes

2021-10-01 06:42 UTC, merged