Blog Post - A Series of Rust Posts
adessoAG/devblog pull request #201
Opened 2021-05-18 14:18 UTC by reenigneEsrever92

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-05-20 06:48 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +The end result of this blog post is a working implementation of a lambda function to run on AWS services.
Die beiden Sätze sagen das gleiche aus, bitte formuliere sie um.

2021-05-20 06:49 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +- AWS CLI: <https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html>
Bitte verwende hier die Link-Schreibweise von MarkDown. Meinst du bei Punkt 2 Visual Studio Code?

2021-05-20 06:51 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +The musl target is required for our rust installation:
Bitte erkläre hier etwas genauer was musl ist.

2021-05-20 06:53 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +I also did not attach the policy to my user directly but to a group that I put my user in.
Schreibe das bitte in einem Satz oder zumindest so, dass du nicht sagst ich mache A, nein ich mache B.

2021-05-20 06:54 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +To start with our project we can use cargo for us to generate an initial crate:
```suggestion
To start with our project we can use cargo to generate an initial crate:
```

2021-05-20 06:54 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +Now, we can open the folder that cargo created in Visual Code:
Meinst du hier Visual Studio Code?

2021-05-20 06:56 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +Lets build first:
```suggestion
Lets build our application:
```

2021-05-20 07:10 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +[--handler] the handler is usually a reference to the corresponding handler function. In our case we provide the runtime (and poll on the API our selfs as you will see in the next blog post) in our e
```suggestion
[--handler] the handler is usually a reference to the corresponding handler function. In our case we provide the runtime (and poll on the API our selfs as you will see in the next blog post) in our executable so this wouldn't matter so we set it to `doesnt.matter` \
```

2021-05-20 07:12 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +[--function-name] denotes the name of the function we wish to create \
Verwende für diese Aufzählungen bitte die Aufzählungsschreibweise von MarkDown.

2021-05-20 07:13 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +(Probably ¯\\\_(ツ)\_/¯)
Diese Zeile kannst du streichen, das sind ja die Sachen die du verwendest.

2021-05-20 07:14 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +    lambda_runtime::run(func).await?;
kann das hier nicht auch in einer Zeile gemacht werden?

2021-05-20 07:23 UTC, jo2 requested changes
Der Artikel liest sich schon recht gut, ein paar Sachen habe ich noch angemerkt. Außerdem:
* Gestalte das Beispiel doch etwas umfangreicher. Zumindest eine Funktion, der ein Name übergeben wird und die dann ein Greeting zurück gibt, sollte es schon sein. Schließlich geht es in deinem Artikel um Rust und das kommt mMn. zu kurz.
* Du setzt ziemlich viel Vorwissen im Umgang mit AWS vorraus. Das ist OK, da es ja nicht darum gehen soll, du solltest aber bei Contents noch schreiben, dass jegliches Wissen über AWS und Lambda vorrausgesetzt wird. Falls da jemand defizite hat, kann er für das, was man in deinem Artikel braucht hier(<- ist dann ein Link) nachlesen.

2021-05-20 08:05 UTC, reenigneEsrever92 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +- AWS CLI: <https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html>
Was genau meinst du damit? Und, ja.

2021-05-20 08:25 UTC, reenigneEsrever92 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +    lambda_runtime::run(func).await?;
Ja, klar. Im nächsten blogpost würde ich gerne erläutern, was die lambda-runtime für uns erledigt und so kann ich aufTeile explizit eingehen, indem ich auf die Zeile verweise.

2021-05-20 10:37 UTC, jo2 commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +    lambda_runtime::run(func).await?;
ok

2021-05-20 10:38 UTC, jo2 requested changes
Eine Kleinigkeit habe ich noch angemerkt. Gestalte außerdem das Beispiel doch etwas umfangreicher. Zumindest eine Funktion, der ein Name übergeben wird und die dann ein Greeting zurück gibt, sollte es schon sein. Schließlich geht es in deinem Artikel um Rust und das kommt mMn. zu kurz.

2021-05-20 11:39 UTC, reenigneEsrever92 commented
Ich würde ich im nächsten Blogpost gerne auf die Laufzeit eingehen, was der Grund dafür ist, dass ich das Beispiel in diesem so simpel wie möglich gemacht habe. Auf die Art und weise stehen mir Details, was die Implementierung der Funktion angeht, im nächsten Post nicht im weg und ich kann auf die Laufzeit selber eingehen. Das war zumindest der Plan. Andere Bibliotheken und Integration mit anderen AWS services, das erweitern unserer Funktion und so würde ich mir dann für den dritten Teil aufheben. Ein Kompromiss wäre für mich wenn ich das kurz anreiße (im Fließtext) und dann halt darauf aufmerksam mache, dass ich genaueres später behandeln.

Was hältst du davon?

2021-05-20 11:51 UTC, jo2 commented
Ich kenne mich selbst nicht mit Rust aus, so wie ich deinen Code verstehe ist das Java-Pendant dazu:
```
public void method() {
    return;
}
```
Das ist für ein Beispiel zu wenig. Wenn ich das falsch verstanden habe, korrigiere mich bitte. Laufzeittechnisch sollte ein 
```
public void method(String name) {
    return "hello " + name;
}
```
ja nicht viel aufwändiger sein, oder?

2021-05-20 12:17 UTC, reenigneEsrever92 commented
Der Value Typ wird halt von Serde geparst und von der Laufzeit zur Verfügung gestellt die Funktion returned dann einfach genau das wieder als "Result". Was auch nen Interressantes Thema sein könnte. Eben das war halt der Plan, einige Stellen auch ein bisschen offen zu lassen, weil man die als gute Einleitung für das nächste Thema nehmen kann. Es gibt da so viele spinn offs, die irgendwie darein passen. Meiner Meinung nach macht es das ja halt auch aus. Der Leser sieht halt Rust geht für Lambda ohne Rust zu kennen. Und dann nimm ich das mit dem Leser auseinander, was das zum einen interressant macht für den, der Rust schon kennt aber auch sogar für jemanden, der das als Einstieg verwendet. Oder so. Ich würde natürlich auch die Losen Enden in Zukunft dann gerne Verlinken. Ist das Möglich?

2021-05-20 15:39 UTC, jo2 approved these changes

2021-07-19 14:12 UTC, acetous requested changes

2021-07-19 14:12 UTC, acetous commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +cargo build --release --target x86_64-unknown-linux-musl
Kannst Du in wenigen Worten vorab erklären, was `cargo` ist?

2021-07-19 14:12 UTC, acetous commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +cp ./target/x86_64-unknown-linux-musl/release/adesso-echo ./bootstrap
Diese drei Commands kannst Du gerne in einen Code-Block packen.

2021-07-19 14:12 UTC, acetous commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +* [--function-name] denotes the name of the function we wish to create \
Prüf doch bitte einmal, dass hieraus wirklich eine Stichpunktliste wird. Das `\` am Ende kann dann auch weg, oder?

2021-07-19 14:12 UTC, acetous commented on _posts/2021-05-17-A-Series-of-Rust-Blog-Posts-Exploring-Rust-For-AWS-Lambda-1.md
> +Output: {"message": "Hello, Felix!"}
Pack die Konsolenausgabe doch in den vorherigen Code-Block.

2021-07-22 06:35 UTC, acetous approved these changes

2021-07-22 06:39 UTC, acetous approved these changes

2021-07-22 06:39 UTC, merged