Contract-Driven Development: Hands-On am Beispiel von Spring Cloud Contract
adessoAG/devblog pull request #202
Opened 2021-05-19 07:06 UTC by g-stone7

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-05-20 10:24 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Führt eine Partei eine nicht kompatible Änderung einer angebotenen Schnittstelle durch, so führt dies zwangsweise zu Fehlern, im schlimmsten Falle sogar zum Gesamtausfall des Gesamtsystems.
```suggestion
Führt eine Partei eine nicht kompatible Änderung einer angebotenen Schnittstelle durch, so führt dies zwangsweise zu Fehlern, im schlimmsten Falle sogar zum Ausfall des Gesamtsystems.
```

2021-05-20 10:24 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Ein Service benötigt in seinem Kontext die Information, ein bestimmtes Jahr ein Schaltjahr ist.
```suggestion
Ein Service benötigt in seinem Kontext die Information, dass ein bestimmtes Jahr ein Schaltjahr ist.
```

2021-05-20 10:25 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Zu Demonstrationszwecken bietet der Consumer auch eine Schnittstelle an, die lediglich das Ergebnis der Anfrage an den Producer zurückgibt.
```suggestion
Zu Demonstrationszwecken bietet der Consumer auch eine Schnittstelle an, die lediglich das Ergebnis der Anfrage an den Client zurückgibt.
```

2021-05-20 10:25 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +*Für eine **GET-Anfrage** unter der URL`/leap-year` mit dem Parameter `year` Parameter, welcher eine Ganzzahl sein muss, besteht die **Antwort** aus dem HTTP-Status 200 und einem JSON, welches das At
```suggestion
*Für eine **GET-Anfrage** unter der URL`/leap-year` mit dem Parameter `year`, welcher eine Ganzzahl sein muss, besteht die **Antwort** aus dem HTTP-Status 200 und einem JSON, welches das Attribut `leap` mit einem booleschen Wert enthalten muss.*
```

2021-05-20 10:25 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Es geht stattdessen darum sicherzustellen, dass das Antwortformat sichergestellt ist.
```suggestion
Es geht stattdessen darum, dass das Antwortformat sichergestellt ist.
```

2021-05-20 10:26 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Dazu bietet Spring Cloud Contract die Möglichkeit von sogenannten [Contract Stub Runner](https://cloud.spring.io/spring-cloud-contract/2.1.x/multi/multi__spring_cloud_contract_stub_runner.html).
```suggestion
Dazu bietet Spring Cloud Contract die Möglichkeit von sogenannten [Contract Stub Runnern](https://cloud.spring.io/spring-cloud-contract/2.1.x/multi/multi__spring_cloud_contract_stub_runner.html).
```

2021-05-20 10:29 UTC, jo2 requested changes
Der Artikel ist sehr interessant und liest sich schon sehr gut. Ein paar Sachen habe ich noch angemerkt. Außerdem:
* Achte bitte auf gendergerechte Formulierungen
* Achte bitte auf die Schreibweise von zusammengesetzten Begriffen. Als Faustregel gilt: Ist einer der Begriffe ein eigenname oder stammt aus dem Englischen und ist nicht eingedeutscht, dann werden die Begriffe mit einem Bindestrich verbunden. Ansonsten werden die Begriffe als ein Wort geschrieben.

2021-05-25 06:18 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Der Consumer-Service soll nun die Schnittstelle des Producer-Services konsumieren und die generierten Stubs in Tests integrieren.
```suggestion
Der Consumer-Service soll nun die Schnittstelle des Producer-Service konsumieren und die generierten Stubs in Tests integrieren.
```

2021-05-25 06:18 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Wir implementieren nun zu Demonstrationszwecken eine GET-Schnittstelle, welche die Schnittstelle des Producer-Services konsumiert:
```suggestion
Wir implementieren nun zu Demonstrationszwecken eine GET-Schnittstelle, welche die Schnittstelle des Producer-Service konsumiert: 
```

2021-05-25 06:18 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Außerdem benötigen wir noch die Abhängigkeiten zum [spring-cloud-contract-stub-runner](https://cloud.spring.io/spring-cloud-contract/2.1.x/multi/multi__spring_cloud_contract_stub_runner.html) und zu
```suggestion
Außerdem benötigen wir noch die Abhängigkeiten zum [spring-cloud-contract-stub-runner](https://cloud.spring.io/spring-cloud-contract/2.1.x/multi/multi__spring_cloud_contract_stub_runner.html) und zu den Stubs des Producer-Service:
```

2021-05-25 06:19 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Stattdessen verwenden wir für die Mocks aber die generierten Stubs des Producer-Services.
```suggestion
Stattdessen verwenden wir für die Mocks aber die generierten Stubs des Producer-Service.
```

2021-05-25 06:19 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Wie man sieht, benötigen wir kein händisches Mocking des Producer-Services.
```suggestion
Wie man sieht, benötigen wir kein händisches Mocking des Producer-Service.
```

2021-05-25 06:19 UTC, jo2 commented on _posts/2021-05-19-Contract-Driven-Development_Hands-On-am-Beispiel-von-Spring-Cloud-Contract.md
> +Dadurch fällt nun jede Änderung aufseiten des Producer-Services bei Ausführung der Consumer-Tests auf.
```suggestion
Dadurch fällt nun jede Änderung aufseiten des Producer-Service bei Ausführung der Consumer-Tests auf.
```

2021-05-25 06:22 UTC, jo2 requested changes
Ein paar Kleinigkeiten sind mir jetzt noch aufgefallen, danach ist der Artikel von meiner Seite aus in Ordnung.

2021-06-10 06:28 UTC, jo2 approved these changes

2021-06-10 06:28 UTC, jo2 commented
@acetous passt das auch von deiner Seite aus?

2021-06-15 11:22 UTC, acetous commented on _data/authors.yml
> +tgraefenstein:
Bitte mach zum Autor alle Angaben. Es fehlt: github_username und github.

2021-06-24 06:03 UTC, jo2 approved these changes

2021-07-15 06:59 UTC, acetous approved these changes

2021-07-15 07:00 UTC, merged