Create 2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
adessoAG/devblog pull request #203
Opened 2021-06-18 08:20 UTC by VivienEmily

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [x] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-06-21 06:51 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Und in der Welt der IT-Sicherheit müssen viele Entscheidungen getroffen werden: Als Mensch, in der Zusammenarbeit, in der Implementierung von Software und insbesondere KI Lösungen.
```suggestion
Und in der Welt der IT-Sicherheit müssen viele Entscheidungen getroffen werden: Als Mensch, in der Zusammenarbeit, in der Implementierung von Software und insbesondere von KI-Lösungen. 
```

2021-06-21 06:59 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Eventuell treffen wir Entscheidungen mit System eins, aufgrund von „Weil wir das schon immer so getan haben“, unserem Bauchgefühl oder unserer Intuition und hinterfragen diese nicht weiter, sondern v
```suggestion
Eventuell treffen wir Entscheidungen mit System eins "Weil wir das schon immer so getan haben" oder wegen unserem Bauchgefühl oder unserer Intuition und hinterfragen die Entscheidung nicht weiter, sondern vertrauen darauf. 
```

2021-06-21 07:04 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +System eins ist immer schneller, als dass wir es wirklich hinterfragen könnten.
```suggestion
System eins ist zu schnell, als dass wir es wirklich hinterfragen könnten. 
```

2021-06-21 07:12 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Diese kognitive Verzerrung beschreibt die menschliche Neigung, Informationen so auszuwählen und zu interpretieren, dass sie die eigenen Erwartungen, Meinungen und Überzeugungen bestätigen. Informatio
```suggestion
Diese kognitive Verzerrung beschreibt die menschliche Neigung, Informationen so auszuwählen und zu interpretieren, dass sie die eigenen Erwartungen, Meinungen und Überzeugungen bestätigen.
Informationen, die diesem Standpunkt widersprechen, werden hingegen völlig ausgeblendet.
Somit werden Informationen nach subjektiven Maßstäben gefiltert.
```

2021-06-21 07:15 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Der Dunning Kruger Effekt ist eine Form der Selbstüberschätzung, dabei beschreibt er die Tendenz von wenig kompetenten Menschen, das eigene Können zu überschätzen und die Kompetenz anderer zu untersc
```suggestion
Der Dunning Kruger Effekt ist eine Form der Selbstüberschätzung.
Er beschreibt die Tendenz von weniger kompetenten Menschen, das eigene Können zu überschätzen und die Kompetenz anderer zu unterschätzen. 
```

2021-06-21 07:36 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +## Dunning Kruger Effekt (Overconfidence Bias)
```suggestion
## Dunning-Kruger-Effekt (Overconfidence Bias)
```

2021-06-21 07:36 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Der Dunning Kruger Effekt ist eine Form der Selbstüberschätzung, dabei beschreibt er die Tendenz von wenig kompetenten Menschen, das eigene Können zu überschätzen und die Kompetenz anderer zu untersc
```suggestion
Der Dunning-Kruger-Effekt ist eine Form der Selbstüberschätzung, dabei beschreibt er die Tendenz von wenig kompetenten Menschen, das eigene Können zu überschätzen und die Kompetenz anderer zu unterschätzen. 
```

2021-06-21 07:36 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +## Framing Effekt
```suggestion
## Framing-Effekt
```

2021-06-21 07:36 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Der Framing Effekt bedeutet, dass unterschiedliche Formulierungen einer gleichen Information das Verhalten des Empfängers unterschiedlich beeinflussen kann.
```suggestion
Der Framing-Effekt bedeutet, dass unterschiedliche Formulierungen einer gleichen Information das Verhalten des Empfängers unterschiedlich beeinflussen kann. 
```

2021-06-21 07:37 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Der Bias Blind Spot ist der gravierendste aller kognitiver Verzerrungen.
```suggestion
Der Bias Blind Spot ist die gravierendste aller kognitiven Verzerrungen. 
```

2021-06-21 07:38 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Man glaubt, selbst eine Ausnahme zu sein und von diesen Effekten unberührt zu bleiben.
```suggestion
Wir glauben dabei, eine Ausnahme zu sein und von diesen Effekten unberührt zu bleiben. 
```

2021-06-21 07:39 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Die eigenen Einschätzungen werden als objektiv beurteilet und man glaubt, weniger als andere von solchen Verzerrungen betroffen zu sein.
```suggestion
Die eigenen Einschätzungen werden als objektiv beurteilet und wir glauben, weniger als andere von solchen Verzerrungen betroffen zu sein. 
```
Dieser Satz und der davor überschneiden sich inhaltliche stark. Kannst du hier einen von beiden Sätzen umformulieren oder sie zusammenfassen?

2021-06-21 07:41 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Social Engineering beschreibt dabei eine Technik menschliche Eigenschaften, insbesondere kognitive Verzerrungen systematisch auszunutzen und zu manipulieren, sodass das Zielobjekt bereitwillig Aktion
```suggestion
Social Engineering beschreibt dabei eine Technik menschliche Eigenschaften, insbesondere kognitive Verzerrungen, systematisch auszunutzen und zu manipulieren, sodass das Zielobjekt bereitwillig Aktionen ausführt, die sie normalerweise nicht vornehmen würde oder dürfte.
Dabei kann es sich um die Herausgabe von Informationen, aber auch die Installation von Schadsoftware oder das Aufhalten der Tür zum Firmengebäude handeln.
```

2021-06-21 07:42 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Ein Werkzeug eines Social Engineers sind Spear Phishing E-Mails.
```suggestion
Ein Werkzeug eines Social Engineers sind Spear-Phishing-E-Mails. 
```

2021-06-21 07:43 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Bei wirklich sehr gut gemachten Phishing E-Mails kann anschließend der Confirmation Bias wirken.
```suggestion
Bei wirklich sehr gut gemachten Phishing-E-Mails kann anschließend der Confirmation Bias wirken. 
```

2021-06-21 07:43 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Ich erwarte evtl. eine ähnliche E-Mail und klicke schnell auf den Link oder die Datei und denke gar nicht länger nach, ob es eine Phishing E-Mail hätte sein können oder nicht.
```suggestion
Ich erwarte evtl. eine ähnliche E-Mail und klicke schnell auf den Link oder die Datei und denke gar nicht länger nach, ob es eine Phishing-E-Mail hätte sein können oder nicht. 
```

2021-06-21 07:44 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Oftmals wird das Verhalten diesbezüglich nicht hinterfragt, weil man denkt, dass man auf eine Phishing E-Mail niemals hereinfallen würde (Overconfidence Bias), oder auch weil es in der Vergangenheit
```suggestion
Oftmals wird das Verhalten diesbezüglich nicht hinterfragt, weil wir denken, dass man auf eine Phishing-E-Mail niemals hereinfallen würde (Overconfidence Bias), oder auch weil es in der Vergangenheit noch nicht passiert ist (Verfügbarkeitsheuristik) und die Wahrscheinlichkeit dementsprechend unterschätzt wird. 
```

2021-06-21 07:44 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Wie erfolgreich jedoch Spear Phishing bzw. eine Phishing Kampagne sein kann, könnt ihr in meinen vergangenen [Blog Beitrag](https://www.adesso.de/de/news/blog/phishing-kampagne-bei-adesso.jsp) nachle
```suggestion
Wie erfolgreich jedoch Spear Phishing bzw. eine Phishing-Kampagne sein kann, könnt ihr in meinen vergangenen [Blog Beitrag](https://www.adesso.de/de/news/blog/phishing-kampagne-bei-adesso.jsp) nachlesen. 
```

2021-06-21 07:46 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Oder ist es unwahrscheinlich, dass Barack Obama Donald Trump als [Idioten](https://www.youtube.com/watch?v=cQ54GDm1eL0) bezeichnet?
```suggestion
Oder ist es unwahrscheinlich, dass [Barack Obama Donald Trump als Idioten bezeichnet](https://www.youtube.com/watch?v=cQ54GDm1eL0)? 
```

2021-06-21 07:47 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Wenn nun gezielt FakeNews mithilfe solcher Videos verbreitet und nicht hinterfragt werden, können diese FakeNews unsere Meinung oder Haltung beeinflussen.
```suggestion
Wenn nun gezielt Fake News mithilfe solcher Videos verbreitet und nicht hinterfragt werden, können diese Fake News unsere Meinung oder Haltung beeinflussen. 
```

2021-06-21 07:48 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Dies kann so weit führen, dass Meinungen radikalisiert werden können und eine Situation wie bei [Pizzagate](https://www.sueddeutsche.de/politik/neuer-us-praesident-wie-trumps-team-fake-news-streut-1.
Kannst du hier vielleicht noch einen Satz zu Pizzagate schreiben, in dem du ganz kurz erklärst was passiert ist?

2021-06-21 07:49 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Jedoch braucht es dafür nicht nur DeepFakes und Fake News oder Social Engineering.
```suggestion
Jedoch braucht es dafür nicht nur DeepFakes, Fake News oder Social Engineering. 
```

2021-06-21 07:49 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Doch noch einmal zurück zu den Social Engineers und ihre neuen Möglichkeiten durch den Einsatz von Künstlicher Intelligenz.
```suggestion
Doch noch einmal zurück zu den Social Engineers und ihren neuen Möglichkeiten durch den Einsatz von Künstlicher Intelligenz.
```

2021-06-21 07:50 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Wenn DeepFakes immer besser werden und auch in Echtzeit erstellt und verwendet werden können, können sie auch in Online Meetings Tool eingesetzt werden.
```suggestion
Wenn DeepFakes immer besser werden und auch in Echtzeit erstellt und verwendet werden können, können sie auch in Online-Meeting-Tools eingesetzt werden. 
```

2021-06-21 07:50 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Und je glaubhafter die Situation, umso eher besteht die Gefahr auf den Social Engineer hereinzufallen und seinen Forderungen nachzugehen.
```suggestion
Und je glaubhafter die Situation, umso eher besteht die Gefahr, auf den Social Engineer hereinzufallen und seinen Forderungen nachzugehen. 
```

2021-06-21 07:51 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Dies kann somit auf die IT-Sicherheit verschiedenster Unternehmen (ohne entsprechende Gegenmaßnahme) treffen, daher stuft das BSI in ihrem [Lagebericht](https://www.bsi.bund.de/DE/Service-Navi/Publik
```suggestion
Dies kann somit auf die IT-Sicherheit verschiedenster Unternehmen (ohne entsprechende Gegenmaßnahme) treffen, daher stuft das BSI in seinem [Lagebericht](https://www.bsi.bund.de/DE/Service-Navi/Publikationen/Lagebericht/lagebericht_node.html) und die [BaFin Cybercrime Perspektive](https://www.bafin.de/SharedDocs/Downloads/DE/BaFinPerspektiven/2020/bp_20-1_cybersicherheit.pdf?__blob=publicationFile&v=5 ) DeepFakes als ein großes Sicherheitsrisiko für die Zukunft ein. 
```

2021-06-21 07:52 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Außerdem wird darauf eingegangen, was getan werden kann, dass die Wahrnehmungen des Menschen nicht zur Sicherheitslücke werden.
```suggestion
Außerdem wird darauf eingegangen, was getan werden kann, damit die Wahrnehmungen des Menschen nicht zur Sicherheitslücke werden. 
```

2021-06-21 07:53 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Wer in der Zwischenzeit mehr über unsere Denksysteme erfahren möchte, dem sei das Buch „Schnelles Denken, langsames Denken“ von Daniel Kahnemann empfohlen.
```suggestion
Wer in der Zwischenzeit mehr über unsere Denksysteme erfahren möchte, dem sei das Buch "Schnelles Denken, langsames Denken" von Daniel Kahnemann empfohlen.
```

2021-06-21 07:53 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Weitere Informationen zu DeepFakes gibt es in den Videos von [Leschs Kosmos](https://www.zdf.de/wissen/leschs-kosmos/deepfakes-der-manipulation-ausgeliefert-100.html) und im Youtube Video von [funk](
```suggestion
Weitere Informationen zu DeepFakes gibt es in den Videos von [Leschs Kosmos](https://www.zdf.de/wissen/leschs-kosmos/deepfakes-der-manipulation-ausgeliefert-100.html) und im Youtube-Video von [funk](https://www.youtube.com/watch?v=EFR1XYZXhdU) zu sehen. 
```

2021-06-21 07:53 UTC, jo2 commented on _posts/2021-06-25-kognitive-Verzerrungen-IT-Sicherheit.md
> +Wie Manipulation in den sozialen Netzwerken eingesetzt werden kann, zeigt zudem die Dokumentation „The Social Dilemma“ von Netflix.
```suggestion
Wie Manipulation in den sozialen Netzwerken eingesetzt werden kann, zeigt zudem die Dokumentation "The Social Dilemma" von Netflix.
```

2021-06-21 07:56 UTC, jo2 requested changes
Der Artikel liest sich schon recht gut und ist mMn. sehr interessant, ich freue mich schon auf Teil 2, den du unten angeteasert hast. Könntest du oben im Artikel noch einen Satz schreiben wie "Dies ist Teil 1, es geht um ... in Teil 2 wird es um ... gehen." So wird direkt klar, dass es sich um eine Serie handelt. Ein paar Kleinigkeiten habe ich noch angemerkt.

2021-07-07 09:52 UTC, VivienEmily commented
Vielen lieben Dank für dein Review! Leider werde ich den Pull Request löschen oder löschen lassen müssen, da er nun als Artikel in einer Fachzeitschrift erscheinen soll und diese sich wünscht, dass der Artikel nicht doppelt in unserem Blog erscheint......

2021-07-07 09:53 UTC, closed without merging