Functional Kotlin - Eine Einführung
adessoAG/devblog pull request #206
Opened 2021-07-11 11:46 UTC by VolkertF

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Methodik, Architekturen, Softwareentwicklung, Branchen, Inside adesso)
    - [ ] "tags" enthält (beliebige) passende Tags
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-07-19 11:20 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +# Functional Kotlin -- Eine Einführung
Der Blogbeitrag benötigt einen Teaser. Die Zeilen 23-25 sind dafür gut geeignet, du müsstest entsprechend die Überschrift hier entfernen, die wird automatisch durch den Blog gesetzt und wäre sonst auch doppelt.

2021-07-19 11:21 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +2017 wurde sie von Google offiziell zur Entwicklung von Android-Apps unterstützt und ist seit 2019 Googles bevorzugte Sprache für diese Plattform.
```suggestion
Seit 2017 wird sie von Google offiziell zur Entwicklung von Android-Apps unterstützt und ist seit 2019 Googles bevorzugte Sprache für diese Plattform.
```

2021-07-19 11:25 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Folgendes Beispiel zeigt ein kleines in Kotlin geschriebenes Programm, welches zuerst das Ergebnis einer Instanzmethode und dann das einer statischen Methode ausgibt:
```suggestion
Folgendes Beispiel zeigt ein kleines, in Kotlin geschriebenes Programm, welches zuerst das Ergebnis einer Instanzmethode und dann das einer statischen Methode ausgibt:
```

2021-07-19 11:29 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Auf den Unterschied komme ich im Abschnitt [Immutabilität](#Immutabilitt_80) zu sprechen.
Der Link hier funktioniert in der Vorschau nicht, muss du ggf. die Zeilennummer anpassen?

2021-07-19 11:30 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Eine Ärgerlichkeit, mit der wir uns als Entwicklerinnen und Entwickler im Alltag häufig auseinandersetzen müssen ist das Behandeln von Nullpointer-Exceptions;
```suggestion
Eine Ärgerlichkeit, mit der wir uns im Entwicklungsalltag häufig auseinandersetzen müssen ist das Behandeln von Nullpointer-Exceptions; 
```

2021-07-19 11:31 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Also das Fehlen von Daten an Stellen, an denen das Programm welche erwartet hat.
Hier fehlt ein Verb, entweder verbindest du diesen Satz mit dem davor, indem du ein Komma statt eines Punkts verwendest, oder du formulierst den Satz hier um.

2021-07-19 11:33 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +([My billion-dollar mistake](https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare/))
Gehe bitte auf diesen Link ein. Er steht ansonsten kommentarlos ohne eine wirkliche Daseinsberechtigung im Text.

2021-07-19 11:34 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +So sind wir als Entwickler immer informiert, wann Daten potentiell undefinierte Zustände annehmen würden:
```suggestion
So werden wir bei der Entwicklung immer informiert, wenn Daten potentiell undefinierte Zustände annehmen könnten:
```

2021-07-19 11:35 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Manchmal lässt es sich allerdings auch nicht vermeiden, oder ist erwünscht, dass ein null Wert übernommen wird;
```suggestion
Manchmal lässt es sich allerdings auch nicht vermeiden oder ist erwünscht, dass ein null Wert übernommen wird;
```

2021-07-19 11:35 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Zum Beispiel an Schnittstellen, wenn kein Default-Wert Sinn ergibt.
Dies ist auch kein ganzer Satz, s.o.

2021-07-19 11:36 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Dazu kann die Entwicklerin oder der Entwickler Werte mit einem `?` markieren, dass sie null (*nullable*) sein dürfen:
```suggestion
Wir können den Wert mit einem `?` markieren, um kenntlich zu machen, dass sie null (*nullable*) sein dürfen: 
```

2021-07-19 11:37 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +So sind wir gezwungen uns um diesen Fall zu kümmern und entweder vorher sicherzustellen, dass `vat` nicht null sein kann, oder einen null-Wert als Eingabeparameter zu erlauben, wodurch sich die Fehle
```suggestion
So sind wir gezwungen, uns um diesen Fall zu kümmern und entweder vorher sicherzustellen, dass `vat` nicht null sein kann, oder einen null-Wert als Eingabeparameter zu erlauben, wodurch sich die Fehlermeldung auf nachfolgende Aufrufe von `vat` verbreitet.
```

2021-07-19 11:43 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Ein anderes Beispiel zeigt, wie wir uns beim Programmieren mit Nullwerten in Kotlin viel Boilerplate-Code sparen können:
Kannst du hier für das bessere Verständnis noch einen Satz ergänzen wir "Zunächst gucken wir uns das Problem in Java an, anschließend folgt die Lösung in Kotlin."

2021-07-19 11:54 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Immutabilität hilft Entwicklerinnen und Entwicklern Nebeneffekte im Code auf ein Minimum zu reduzieren und schafft so Sicherheit vor allem für Parallelität.
```suggestion
Immutabilität hilft während der Entwicklung Nebeneffekte im Code auf ein Minimum zu reduzieren und schafft so Sicherheit vor allem für Parallelität.
```

2021-07-19 11:58 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +- Sicherheit vor Nullwerten (Wenn ein Wert einmal überprüft wurde, behält er seine Gültigkeit)
Oben schreibst du null-Werten, mach das bitte einheitlich.

2021-07-19 11:59 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +- Leichteres Chaching (Wenn ein Wert einmal geladen wurde und sich Rahmenbedingungen ändern, ist sichergestellt, dass dieser Wert nach wie vor gültig ist und nicht neu geladen werden muss)
Meinst du Caching?

2021-07-19 12:00 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +- Einfacher zu Testen (Durch feste Werte und fehlende Nebeneffekte sind die Punkte, die es bei Fehlern zu überprüfen gilt weniger und einfacher)
```suggestion
- Einfacher zu Testen (Durch feste Werte und fehlende Nebeneffekte sind die Punkte, die es bei Fehlern zu überprüfen gilt, weniger und einfacher)
```

2021-07-19 12:04 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Ich denke diese kurze Übersicht ergibt Sinn und spricht für sich selbst, dass der Aufwand für Immutabilität im Verältnis zu den Vorteilen in den meisten Fällen gering ausfallen dürfte.
```suggestion
Diese Auflistung zeigt, dass der Aufwand für Immutabilität im Verältnis zu den Vorteilen in den meisten Fällen gering ausfällt.
```

2021-07-19 12:37 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Also statt das wir ein Problem aus der Perspektive betrachten, jeden Schritt einzeln durchzugehen, arbeiten wir mit einer Menge von Daten, auf die Operationen angewandt werden und die mitunter eine n
```suggestion
Also statt dass wir ein Problem aus der Perspektive betrachten, jeden Schritt einzeln durchzugehen, arbeiten wir mit einer Menge von Daten, auf die Operationen angewandt werden und die mitunter eine neue Menge von Daten erzeugt.
```

2021-07-19 12:38 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Lambda-Ausdrücke kennt man als Entwicklerin oder Entwickler im Java-Kontext hauptsächlich in Form von Lambda-Ausdrücken (ab Java 8 in 2014).
```suggestion
Lambda-Ausdrücke kennen wir aus der Entwicklung im Java-Kontext hauptsächlich in Form von Lambda-Ausdrücken (ab Java 8 in 2014). 
```

2021-07-19 12:40 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Die zwei wichtigen anderen Methoden, die häufig eingesetzt werden sind die `map`- und die `reduce`-Methode.
```suggestion
Die zwei wichtigen anderen Methoden, die häufig eingesetzt werden, sind die `map`- und die `reduce`-Methode.
```

2021-07-19 12:41 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +`Map` iteriert über jedes Element einer Menge von Daten und wendet eine Funktion auf dieses an.
```suggestion
`map` iteriert über jedes Element einer Menge von Daten und wendet eine Funktion auf dieses an. 
```

2021-07-19 12:42 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Obiges Beispiel zeigt, wie eine Liste von Produkten in eine Liste von Preisen konvertiert wird, in dem von jedem Produkt-Element der Konsumentenpreis geholt wird.
```suggestion
Obiges Beispiel zeigt, wie eine Liste von Produkten in eine Liste von Preisen konvertiert wird, indem von jedem Produkt-Element der Konsumentenpreis geholt wird.
```

2021-07-19 12:43 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Im zweiten Parameter wird die Funktion mit `price` als Laufwert aus der Liste vorgegeben.
Was möchtest du hiermit genau ausdrücken? Vorgegeben passt als Verb hier mMn. nicht.

2021-07-19 12:44 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +`Map`, `filter` und `reduce` sind Beispiele für sogenannte [Funktionen höherer Ordnung](https://kotlinlang.org/docs/lambdas.html), denn sie nehmen nicht nur einfache Werte als Parameter entgegen, son
```suggestion
`map`, `filter` und `reduce` sind Beispiele für sogenannte [Funktionen höherer Ordnung](https://kotlinlang.org/docs/lambdas.html), denn sie nehmen nicht nur einfache Werte als Parameter entgegen, sondern erwarten Funktionen, die sie während ihrer Ausführung aufrufen können.
```

2021-07-19 12:45 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Zwei Dinge, die an dem obigen Beispiel auffallen sind der Einsatz von Generics zur Verallgemeinerung der Anwendbarkeit der Funktion;
```suggestion
Zwei Dinge, die an dem obigen Beispiel auffallen, sind der Einsatz von Generics zur Verallgemeinerung der Anwendbarkeit der Funktion;
```

2021-07-19 12:46 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Und das es sich hierbei um eine sogenannte [*Extension-Function*](https://kotlinlang.org/docs/extensions.html) handelt, die -- in diesem Fall -- Iterable um eine Methode erweitert.
```suggestion
Und dass es sich hierbei um eine sogenannte [*Extension-Function*](https://kotlinlang.org/docs/extensions.html) handelt, die -- in diesem Fall -- Iterable um eine Methode erweitert.
```

2021-07-19 12:47 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +(Mehr Informationen zu [inline-Funktionen](https://kotlinlang.org/docs/inline-functions.html))
```suggestion
Hier gibt es ehr Informationen zu [inline-Funktionen](https://kotlinlang.org/docs/inline-functions.html).
```

2021-07-19 12:47 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Hier ein Beispiel aus einem Projekt in dem ich gearbeitet habe.
```suggestion
Hier ist ein Beispiel aus einem Projekt in dem ich gearbeitet habe. 
```

2021-07-19 12:47 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Dort haben wir Extension-Functions häufig genutzt um vor allem die Lesbarkeit unseres Codes zu erhöhen.
```suggestion
Dort haben wir Extension-Functions häufig genutzt, um vor allem die Lesbarkeit unseres Codes zu erhöhen.
```

2021-07-19 12:48 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +(Das Schlüsselwort `suspend` kann ignoriert werden.
```suggestion
(Das Schlüsselwort `suspend` kann ignoriert werden. 
```

2021-07-19 12:49 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Bei Interesse empfehle ich die Einführung in [Coroutines](https://kotlinlang.org/docs/coroutines-basics.html))
```suggestion
Bei Interesse empfehle ich die Einführung in [Coroutines](https://kotlinlang.org/docs/coroutines-basics.html).)
```

2021-07-19 12:57 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +In klassischer Herangehensweise würde man beim Testen neben den Grenzfällen (leerer String, Nullstring), einen "normalen" Methodenaufruf testen.
```suggestion
In klassischer Herangehensweise würden wir beim Testen neben den Grenzfällen (leerer String, Nullstring), einen "normalen" Methodenaufruf testen.
```

2021-07-19 12:57 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Eine andere Art und Weise an den Test heranszugehen, ist sich zu überlegen, welche Eigenschaft die Ergebnisse des Methodenaufrufs gemein haben.
```suggestion
Eine andere Art und Weise an den Test heranszugehen ist, sich zu überlegen, welche Eigenschaft die Ergebnisse des Methodenaufrufs gemein haben.
```

2021-07-19 12:59 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +*Für alle Strings string1 und string2 gilt, dass die Konkatenation von string1 und string2 mit string1 anfängt und mit string2 endet*\
Gehören die \ hier zum Ausdruck?

2021-07-19 13:47 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Sicherlich wird dabei auch das noch recht junge Alter der Sprache und die Erfahrungen, die in sie hineingeflossen sind, eine Rolle spielen, das dem wirklich so ist.
```suggestion
Sicherlich wird dabei auch das noch recht junge Alter der Sprache und die Erfahrungen, die in sie hineingeflossen sind, eine Rolle spielen,.
```

2021-07-19 13:48 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Das funktionale Paradigma und Kotlin in seiner Ausprägung, ich habe es schon vorher geschrieben, kommen mir häufig leichtgängiger vor und es bereitet mir viel Freude so zu programmieren.
```suggestion
Das funktionale Paradigma und Kotlin in seiner Ausprägung, ich habe es schon vorher geschrieben, kommen mir häufig leichtgängiger vor und es bereitet mir viel Freude, so zu programmieren.
```

2021-07-19 13:51 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Der Preis, den wir hier zahlen, sind Effizienzeinbußen (Die in vielen Projekten allerdings vernachlässigbar sein werden), gegenüber zum Beispiel einer optimierten Programmierlösung in C, sowie der Au
```suggestion
Der Preis, den wir hier zahlen, sind Effizienzeinbußen (die in vielen Projekten allerdings vernachlässigbar sein werden) gegenüber zum Beispiel einer optimierten Programmierlösung in C, sowie der Aufwand, den es für uns mit sich bringt, sich an diese *neue* Art zu denken zu gewöhnen.
```

2021-07-19 13:57 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Es hat einen Grund, dass viele Sprachen sind heutzutage an diesen Aspekten orientieren und diese bei den Entwicklerinnen und Entwicklern populär sind und ich hoffe, dass ich euch einen kleinen Einbli
```suggestion
Es hat einen Grund, dass sich viele Sprachen heutzutage an funktionaler Programmierung orientieren und diese sehr populär ist.
Ich hoffe, dass ich euch einen kleinen Einblick in Kotlin und die funktionale Welt geben konnte.
```

2021-07-19 13:59 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Eine sehr gute offizielle Tutorial-Reihe die sich unter anderem mit den Inhalten beschäftigt, die wir hier nur oberflächlich betrachten konnten und auch noch viel weiter in die Details der Sprache ei
```suggestion
Kotlin Koans sind sehr gute offizielle Tutorial-Reihe, die sich unter anderem mit den Inhalten beschäftigt, die wir hier nur oberflächlich betrachten konnten, und auch noch viel weiter in die Details der Sprache eintaucht.
```

2021-07-19 14:01 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Ein anderer spannender Blogeintrag zum Thema Kotlin bei adesso, wenn ihr direkt weiterlesen wollt, was sonst noch so in der Kotlin Welt passiert:
```suggestion
Ein anderer spannender Blogeintrag zum Thema Kotlin bei adesso zum direkt Weiterlesen:
```

2021-07-19 14:03 UTC, jo2 requested changes
Der Blogbeitrag liest sich schon sehr gut. Ein paar Kleinigkeiten habe ich noch angemerkt.

2021-07-19 14:34 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Auf den Unterschied komme ich im Abschnitt [Immutabilität](#Immutabilität) zu sprechen.
```suggestion
Auf den Unterschied komme ich im Abschnitt [Immutabilität](#immutabilität) zu sprechen.
```
Damit sollte der Link funktionieren.

2021-07-19 14:35 UTC, VolkertF commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Auf den Unterschied komme ich im Abschnitt [Immutabilität](#Immutabilität) zu sprechen.
Habe auch gerade gesehen, wie die id aufgelöst wird und geändert 👍🏻

2021-07-19 14:36 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Eine Ärgerlichkeit, mit der wir uns im Entwicklungsalltag häufig auseinandersetzen müssen ist das Behandeln von Nullpointer-Exceptions, also dem Fehlen von Daten an Stellen, an denen das Programm wel
```suggestion
Eine Ärgerlichkeit, mit der wir uns im Entwicklungsalltag häufig auseinandersetzen müssen, ist das Behandeln von Nullpointer-Exceptions, also dem Fehlen von Daten an Stellen, an denen das Programm welche erwartet hat.
```
Das habe ich übersehen..

2021-07-19 14:38 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Das kann zum Beispiel an Schnittstellen der Fall sein, an denen ein Standardwert keinen Sinn ergibt (Auch wenn sich hier wieder darüber streiten lässt, ob ein Standardwert wirklich nicht die bessere
```suggestion
Das kann zum Beispiel an Schnittstellen der Fall sein, an denen ein Standardwert keinen Sinn ergibt (auch wenn sich hier wieder darüber streiten lässt, ob ein Standardwert wirklich nicht die bessere Entscheidung ist).
```

2021-07-19 14:38 UTC, jo2 commented on _posts/2021-07-11-functional-kotlin-eine-einführung.md
> +Wir können den Wert mit einem `?` markieren, um kenntlich zu machen, dass sie null (*nullable*) sein dürfen:
```suggestion
Wir können die Werte mit einem `?` markieren, um kenntlich zu machen, dass sie null (*nullable*) sein dürfen: 
```

2021-07-19 14:50 UTC, jo2 submitted a review, later dismissed

2021-07-19 14:51 UTC, jo2 commented
@acetous von meiner Warte aus ist der Artikel soweit in Ordnung.

2021-07-19 14:51 UTC, VolkertF commented
@jo2 Danke erstmal für dein Review und deine Kommentare. Da habe ich ja doch ein, zwei Dinge übersehen.

2021-08-19 14:18 UTC, acetous approved these changes

2021-08-19 14:20 UTC, merged