Blog-Artikel zum adesso testing day 2021
adessoAG/devblog pull request #216
Opened 2021-10-22 06:06 UTC by stwacker

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-11-02 11:30 UTC, jo2 requested changes
Auch ich bin mit der Zeit manchmal ein bisschen betriebsblind, 3 Sachen habe ich übersehen. Danach ist der Artikel von meiner Seite aus fertig.

2021-11-02 11:30 UTC, jo2 commented on _posts/2021-10-04-adesso-testing-day-2021.md
> +Fachlich kamen die adessi aus 10 LoBs (Lines of Business) bzw. Branchen sowie von 4 adesso-Töchtergesellschaften.
```suggestion
Fachlich kamen die adessi aus 10 LoBs (Lines of Business) bzw. Branchen sowie von 4 adesso-Tochtergesellschaften. 
```

2021-11-02 11:30 UTC, jo2 commented on _posts/2021-10-04-adesso-testing-day-2021.md
> +Neben einer expliziten Networking-Session im Speeddating-Format hatten die Teilnehmer die Möglichkeit, sich vor und nach dem Event untereinander und mit den Referentinnen und Referenten in [GatherTow
```suggestion
Neben einer expliziten Networking-Session im Speeddating-Format bestand die Möglichkeit, sich vor und nach dem Event untereinander und mit den Referentinnen und Referenten in [GatherTown](https://gather.town) auszutauschen.
```

2021-11-02 11:30 UTC, jo2 commented on _posts/2021-10-04-adesso-testing-day-2021.md
> +Inzwischen hat man eher die Qual der Wahl in einem oft unübersehbaren Werkzeugfeld.
```suggestion
Inzwischen hat man eher die Qual der Wahl in einem oft unübersichtlichen Werkzeugfeld. 
```

2021-11-02 11:57 UTC, stwacker commented
> Auch ich bin mit der Zeit manchmal ein bisschen betriebsblind, 3 Sachen habe ich übersehen. Danach ist der Artikel von meiner Seite aus fertig.

Kein Thema. Ich habs direkt commited.

2021-11-04 14:52 UTC, jo2 submitted a review, later dismissed

2021-11-25 11:04 UTC, acetous approved these changes

2021-11-25 11:05 UTC, merged