Welcher Config-Server ist der richtige für mein Projekt?
adessoAG/devblog pull request #218
Opened 2021-11-03 11:43 UTC by kthielma

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-11-04 15:33 UTC, jo2 commented on _data/authors.yml
> +  bio: "Kay Thielmann arbeitet als Software Architect bei Adesso in Dortmund. Seine Schwerpunkte liegen zur Zeit im Bereich e-Commerce, wo er diverse Applikation in der AWS-Cloud mit betreut und weit
```suggestion
  bio: "Kay Thielmann arbeitet als Software Architect bei Adesso in Dortmund. Seine Schwerpunkte liegen zur Zeit im Bereich e-Commerce, wo er diverse Applikationen in der AWS-Cloud mit betreut und weiterentwickelt."
```

2021-11-04 16:00 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Consul aus dem Hause Hashicorp ist eigentlich weit mehr als nur ein Config-Server.
```suggestion
Consul aus dem Hause Hashicorp ist eigentlich weit mehr als nur ein Config Server.
```

2021-11-04 16:00 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Der als Speicher für Umgebungsvariablen dienende KV-Store ist am Ende nur "eine" der Kernkomponenten.
```suggestion
Der als Speicher für Umgebungsvariablen dienende Key Value Store ist am Ende nur "eine" der Kernkomponenten.
```

2021-11-04 16:02 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Hat man über diese hinaus weitere Anforderungen im Projekt, kann Consul sehr interessant werden.
```suggestion
Hat man über diesen hinaus weitere Anforderungen im Projekt, kann Consul sehr interessant werden.
```

2021-11-04 16:03 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +So unterstützt Consul durch seine Serviceregistry wenn selbst gemanagte Loadbalancern im Projekt eingesetzt werden müssen, die sich ohne einen solchen Service sonst schnell zu einem Single-Point-Of-F
```suggestion
So unterstützt Consul durch seine Service Registry, wenn selbst gemanagte Load Balancer im Projekt eingesetzt werden müssen, die sich ohne einen solchen Service sonst schnell zu einem Single Point Of Failure entwickeln können.
```

2021-11-04 16:03 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Quasi selbstverständlich ist die Möglichkeit Consul mit Hilfe von Terraform zu managen.
```suggestion
Quasi selbstverständlich ist die Möglichkeit, Consul mit Hilfe von Terraform zu managen.
```

2021-11-04 16:04 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Um Consul zu betreiben ist zum Beispiel ein Deployment in Kubernetes via Helm vorgesehen.
```suggestion
Um Consul zu betreiben, ist zum Beispiel ein Deployment in Kubernetes via Helm vorgesehen.
```

2021-11-04 16:05 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Die Integration in ein vorhandenes Sping-Boot-Projekt erfolgt auch hier nahezu vollständig transparent über spring-cloud-starter und bootstrap.properties.
```suggestion
Die Integration in ein vorhandenes Sping-Boot-Projekt erfolgt auch hier nahezu vollständig transparent über Spring Cloud Starter und bootstrap.properties.
```

2021-11-04 16:05 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Consul bietet uns zusätzlich eine Pflege-Oberfläche an, mit der viele Einstellungen schnell und einfach zu erledigen sind.
```suggestion
Consul bietet uns zusätzlich eine Pflegeoberfläche an, mit der viele Einstellungen schnell und einfach zu erledigen sind.
```

2021-11-04 16:06 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Auch in diesem Fall ist es denkbar das System selbst zu betreiben und man sollte sich analog zu den anderen Systemen Gedanken zu den Themen Ausfallsicherheit, Performance aber auch Authentifizierung
```suggestion
Auch in diesem Fall ist es denkbar, das System selbst zu betreiben, und man sollte sich analog zu den anderen Systemen Gedanken zu den Themen Ausfallsicherheit, Performance aber auch Authentifizierung machen.
```

2021-11-04 16:07 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Wenn die eigene Software bereits in der Cloud läuft, ist es natürlich interessant zu gucken was vom jeweiligen Cloud-Provider bereits angeboten wird.
```suggestion
Wenn die eigene Software bereits in der Cloud läuft, ist es natürlich interessant zu gucken, was vom jeweiligen Cloud-Provider bereits angeboten wird.
```

2021-11-04 16:08 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Umgebungsvariablen werden hier in einer Baumstruktur abgelegt, die es ermöglicht diverse Projekte mit ihren jeweiligen Stages in Teilbäumen zu verwalten, welche dann einzeln abgefragt werden können.
```suggestion
Umgebungsvariablen werden hier in einer Baumstruktur abgelegt, die es ermöglicht, diverse Projekte mit ihren jeweiligen Stages in Teilbäumen zu verwalten, welche dann einzeln abgefragt werden können.
```

2021-11-04 16:09 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +So könnte ein Pfad in der Form ```<projektname>/<stage>/db/url``` die Daten für die Connection-URL zu einer Datenbank enthalten.
```suggestion
So könnte ein Pfad in der Form ```<projektname>/<stage>/db/url``` die Daten für die Connection URL zu einer Datenbank enthalten.
```

2021-11-04 16:09 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Ein Vorteil gegenüber selbst gehosteten Lösungen ist die vorbereitete Integration in andere von AWS angebotene Services, wie ECS, EC2, Lambda, Cloudformation, CodeBuild oder CodeDeploy.
```suggestion
Ein Vorteil gegenüber selbst gehosteten Lösungen ist die vorbereitete Integration in andere von AWS angebotene Services wie ECS, EC2, Lambda, Cloudformation, CodeBuild oder CodeDeploy.
```

2021-11-04 16:09 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Automatisierungen bzw. Runbooks ermöglichen es uns zum Beispiel den Betrieb abzusichern.
```suggestion
Automatisierungen bzw. Runbooks ermöglichen es uns zum Beispiel, den Betrieb abzusichern.
```

2021-11-04 16:11 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Validierung können wir nutzen, um sicherzustellen, dass die Anforderungen für den Start und Betrieb einer angeschlossenen Applikationen immer erfüllt sind.
```suggestion
Validierung können wir nutzen, um sicherzustellen, dass die Anforderungen für den Start und Betrieb einer angeschlossenen Applikation immer erfüllt sind.
```

2021-11-04 16:12 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Dadurch wird es uns möglich ohne weiteren Aufwand auf alte Stände zurückzurollen oder für Fehleranalysen zu bestimmen, welche Konfiguration zum fraglichen Zeitpunkt genutzt wurde.
```suggestion
Dadurch wird es uns möglich, ohne weiteren Aufwand auf alte Stände zurückzurollen oder für Fehleranalysen zu bestimmen, welche Konfiguration zum fraglichen Zeitpunkt genutzt wurde.
```

2021-11-04 16:12 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Natürlich sind damit dann aber Kosten für uns verbunden, die mit dem Betrieb eigener Instanzen einer anderen Lösung abgleichen werden sollten.
```suggestion
Natürlich sind damit dann aber Kosten für uns verbunden, die mit dem Betrieb eigener Instanzen einer anderen Lösung abgeglichen werden sollten.
```

2021-11-04 16:13 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Auch im Parameter Store von AWS lassen sich Passwörter oder andere schützenswerte Properties entsprechend verschlüsselt ablegen.
```suggestion
Im Parameter Store von AWS lassen sich Passwörter oder andere schützenswerte Properties auch entsprechend verschlüsselt ablegen.
```

2021-11-04 16:15 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Nur über die Nutzung eines [Scripts](https://github.com/wobondar/ssm-dotenv) für die Manipulation der Daten in den ebextensions soll dies dennoch machbar sein.
Soll hier tatsächlich ebextensions stehen? Wenn ja müsste es groß geschrieben werden, wenn nicht, bitte anpassen.

2021-11-04 16:16 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Ein bestimmtes Projekt an dieser Stelle allgemein zu empfehlen ist in Anbetracht unterschiedlicher Anforderungen sowie dem Einsatz von Zeit und Geld gar nicht möglich.
```suggestion
Einen Config Server für ein bestimmtes Projekt an dieser Stelle allgemein zu empfehlen ist in Anbetracht unterschiedlicher Anforderungen sowie dem jeweils nötigen Einsatz von Zeit und Geld gar nicht möglich.
```

2021-11-04 16:16 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Hier sei nur die Empfehlung ausgesprochen sich mit den Fragen auseinander zu setzen, was mein Projekt für Anforderungen mitbringt und welcher Aufwand für Integration und Betrieb vom Team gestemmt wer
```suggestion
Hier sei nur die Empfehlung ausgesprochen, sich mit den Fragen auseinander zu setzen, was mein Projekt für Anforderungen mitbringt und welcher Aufwand für Integration und Betrieb vom Team gestemmt werden kann.
```

2021-11-04 16:20 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Gerade der Betrieb sowie die gut vorbereitete Integration machen es interessant sich die Lösungen von Cloud-Providern wie AWS trotz der damit verbundenen laufenden Kosten genau anzugucken.
Kannst du hier noch darauf eingehen, das selbst gehostete Lösungen ja auch irgendwie bezahlt werden müssen? Im Vergleich zu einer selbst gehosteten Lösung mit Wartungspersonal, Redundanz, Verfügbarkeit etc. ist meiner Erfahrung nach in der Regel teurer als eine Lösung in der Cloud.

2021-11-05 06:41 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +So unterstützt Consul durch seine Serviceregistry wenn selbst gemanagte Loadbalancern im Projekt eingesetzt werden müssen, die sich ohne einen solchen Service sonst schnell zu einem Single-Point-Of-F
Überall Bindestriche, aber hier nicht?
Wäre diese Variante, dann nicht konsistenter:

```suggestion
So unterstützt Consul durch seine Service-Registry, wenn selbst gemanagte Load-Balancern im Projekt eingesetzt werden müssen, die sich ohne einen solchen Service sonst schnell zu einem Single-Point-Of-Failure entwickeln können.
```

2021-11-05 07:00 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Die Anbindung von Unleash erfolgt über einen der zahlreichen Client-SDKs, die für diverse Programmiersprachen zur Verfügung stehen.
Darüber kann man streiten. Der oder das SDK? Am Ende eine Frage davon wie man "Kit" übersetzt. Für mich war es der Baukasten und ich würde behaupten, dass das die gebräuchlichere Form ist. Wobei das Kit sicherlich auch nicht verkehrt ist. Sollte das im Kontext des Blogs von Adesso konsistenter sein, dann verwende ich auch geren "das".

2021-11-05 07:03 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Dabei liegt die Logik für die Bedingungen, die eine Variable beeinflussen, in Unleash und können dort kurzfristig angepasst werden.
Gegenvorschlag:
Dabei liegt die Logik für die Bedingungen, die eine Variable beeinflussen, in Unleash und es ist möglich diese Bedingungen dort kurzfristig anzupassen.

2021-11-05 07:05 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +So lassen sich z.B. Szenarien für ein AB-Testing, ein automatisiertes zeitgesteuertes Umschalten von Featuren oder sogar Berechtigungen von Usern dynamisch steuern.
Konkret sind es ja eigentlich die Switches, die umgeschaltet werden. Hier also vielleicht:
```suggestion
So lassen sich z.B. Szenarien für ein AB-Testing, ein automatisiertes zeitgesteuertes Umschalten von Feature-Switches oder sogar Berechtigungen von Usern dynamisch steuern.
```

2021-11-05 07:06 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Wir müssen jede Stelle im Code identifizieren, die von einer Variablen abhängig ist und dort ein Request an Unleash über den SDK auszulösen.
Ich bleibe erstmal bei "der", aber du kannst gerne Versuchen mich zu überzeugen ;-)

2021-11-05 07:20 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Der als Speicher für Umgebungsvariablen dienende KV-Store ist am Ende nur "eine" der Kernkomponenten.
Hashicorp selbst benennt die Komponente als KV-Store oder Consul KV. Vorschlag:
```suggestion
Der als Speicher für Umgebungsvariablen dienende Key-Value-Store Consul KV ist am Ende nur "eine" der Kernkomponenten.
```

2021-11-05 07:23 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Die Integration in ein vorhandenes Sping-Boot-Projekt erfolgt auch hier nahezu vollständig transparent über spring-cloud-starter und bootstrap.properties.
Wieder die Bindestriche, aber natürlich groß geschrieben:
```suggestion
Die Integration in ein vorhandenes Sping-Boot-Projekt erfolgt auch hier nahezu vollständig transparent über Spring-Cloud-Starter und bootstrap.properties.
```

2021-11-05 07:24 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +So könnte ein Pfad in der Form ```<projektname>/<stage>/db/url``` die Daten für die Connection-URL zu einer Datenbank enthalten.
OK, gib mir irgendeine Regel: Wann sollen die Bindestriche hin und wann nicht?

2021-11-05 07:28 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Nur über die Nutzung eines [Scripts](https://github.com/wobondar/ssm-dotenv) für die Manipulation der Daten in den ebextensions soll dies dennoch machbar sein.
War zu unklar formuliert. Es handelt sich um ein Konfigurationsverzeichnis für Elastic Beanstalk. Evtl. so besser:
Nur über die Nutzung eines [Scripts](https://github.com/wobondar/ssm-dotenv) für die Manipulation der Daten, welches in das für Elastic Beanstalk genutzte Konfigurationsverzeichnis ```ebextensions``` integriert werden muss, soll dies dennoch machbar sein.

2021-11-05 07:55 UTC, kthielma commented
Moin @jo2 ,
danke für deinen Input. Die Anzahl der Kommata, die ich in meinen tendenziell zu langen Sätzen vergessen habe, war erschreckend. 
Ich habe dir auch ein paar Kommentare hinterlassen. Im Wesentlichen war mir nicht klar, wir wir mit Bindestrichen umgehen sollen. Ich habe versucht es jetzt konsistent so durchzuziehen, dass alle zusammengesetzen (meist englischen) Begriffe durchgängig mit Bindestrichen geschrieben sind. Es sei denn es handelt sich 1:1 um Produktnamen wie "Consul KV" oder "Spring Cloud Config Server". Ich hoffe das passt für dich so.

2021-11-05 08:11 UTC, kthielma commented
@jo2 : Bzgl der Katgorisierung schwanke ich. Sollte das evtl. doch besser zu "Architektur" passen. Die Grenzen sind da glaube ich fließend.

2021-11-08 07:52 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +So könnte ein Pfad in der Form ```<projektname>/<stage>/db/url``` die Daten für die Connection-URL zu einer Datenbank enthalten.
Bindestriche werden verwendet wenn ein Eigenname oder ein Begriff aus dem Englischen mit einem deutschen Wort verbunden werden (Turing-Test bzw. Controller-Dokumentation). Werden nur englische Begriffe verwendet, werden sie ohne Bindestriche geschrieben (Artificial Intelligence). Handelt es sich ausschließlich um deutsche Begriffe, werden diese ohne Bindestriche als ein Wort geschrieben.

2021-11-08 07:55 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Die Anbindung von Unleash erfolgt über einen der zahlreichen Client-SDKs, die für diverse Programmiersprachen zur Verfügung stehen.
Kit existiert auch so im deutschen, man kann es aber tatsächlich sowohl mit der als auch mit das schreiben, das wusste ich so nicht. Eine Einheitlichkeit über alle Beiträge finden zu wollen, wäre utopisch. Solange es in deinem Artikel einheitlich ist, passt es so.

2021-11-08 08:20 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +So könnte ein Pfad in der Form ```<projektname>/<stage>/db/url``` die Daten für die Connection-URL zu einer Datenbank enthalten.
Ich habe grade mal über die korrekturen geguckt, ich glaube, ich weiß wo die verwirrung herkommt. Bei Config Server kommt es drauf an, ob Server als englischer oder deutscher Begriff gemeint ist. Aber da du den deutschen Genitiv verwendet hast, hätte mir eigentlich auffallen müssen, dass es als deutscher Begriff gemeint war. Das war mein Fehler.

2021-11-08 08:25 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Dabei liegt die Logik für die Bedingungen, die eine Variable beeinflussen, in Unleash und können dort kurzfristig angepasst werden.
Das geht auch, allerdings brauchst du dann hinter möglich noch ein Komma.

2021-11-08 08:26 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +So lassen sich z.B. Szenarien für ein AB-Testing, ein automatisiertes zeitgesteuertes Umschalten von Featuren oder sogar Berechtigungen von Usern dynamisch steuern.
Ja, das ist besser.

2021-11-08 08:31 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Der als Speicher für Umgebungsvariablen dienende KV-Store ist am Ende nur "eine" der Kernkomponenten.
Das klingt noch besser, mir war hier wichtig, dass klar wird, dass es ein Key Value Store ist. Je nach dem, ob du Store als deutschen oder englischen Begriff sehen willst, es geht beides, müsstest du die Bindestriche noch entfernen.

2021-11-08 08:35 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +So unterstützt Consul durch seine Serviceregistry wenn selbst gemanagte Loadbalancern im Projekt eingesetzt werden müssen, die sich ohne einen solchen Service sonst schnell zu einem Single-Point-Of-F
siehe mein Kommentar zu Zeile 108

2021-11-08 08:36 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Die Integration in ein vorhandenes Sping-Boot-Projekt erfolgt auch hier nahezu vollständig transparent über spring-cloud-starter und bootstrap.properties.
siehe mein Kommentar zu Zeile 108

2021-11-08 08:44 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Nur über die Nutzung eines [Scripts](https://github.com/wobondar/ssm-dotenv) für die Manipulation der Daten in den ebextensions soll dies dennoch machbar sein.
ja, so ist es gut.

2021-11-08 08:50 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Im Vergleich zu den entstehenden Kosten für den Betrieb eines ausreichend performanten und ausfallsicheren Clusters von Config-Servern, können gemanagte Lösungen wie der AWS Systems Manager durchaus
```suggestion
Mit den entstehenden Kosten für den Betrieb eines ausreichend performanten und ausfallsicheren Clusters von Config-Servern können gemanagte Lösungen wie der AWS Systems Manager durchaus mithalten.
```

2021-11-08 08:51 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Dabei sind nicht nur die jeweils aktuellsten und sichersten Versionen der eingesetzen Software zu betrachten, sondern auch die Deployment-Scripte, wie zum Beispiel Helm, oder auch eventuell benötigte
```suggestion
Dabei sind nicht nur die jeweils aktuellsten und sichersten Versionen der eingesetzen Software zu betrachten, sondern auch die Versionen der Deployment-Scripte wie zum Beispiel Helm oder auch eventuell benötigte Versionen von Terraform, die stetigen Aktualisierungen unterliegen.
```

2021-11-08 08:52 UTC, jo2 commented on _posts/2021-10-24-configserver.md
> +Trotzdem können spezielle Anforderungen, wie dynamische Feature-Switches oder der Bedarf an einem Service-Mesh, den Einsatz von Unleash oder Consul trotz höherer Aufwände bei Integration und Betrieb
```suggestion
Trotzdem können spezielle Anforderungen wie dynamische Feature-Switches oder der Bedarf an einem Service-Mesh den Einsatz von Unleash oder Consul trotz höherer Aufwände bei Integration und Betrieb am Ende dennoch rechtfertigen.
```

2021-11-08 08:55 UTC, jo2 requested changes
Ein paar Sachen habe ich dir noch angemerkt, das mit dem Config-Server passt so.

2021-11-08 12:03 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Dabei liegt die Logik für die Bedingungen, die eine Variable beeinflussen, in Unleash und können dort kurzfristig angepasst werden.
Komma ergänzt.

2021-11-08 12:09 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +So unterstützt Consul durch seine Serviceregistry wenn selbst gemanagte Loadbalancern im Projekt eingesetzt werden müssen, die sich ohne einen solchen Service sonst schnell zu einem Single-Point-Of-F
Bindestriche entfernt.

2021-11-08 12:11 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Die Integration in ein vorhandenes Sping-Boot-Projekt erfolgt auch hier nahezu vollständig transparent über spring-cloud-starter und bootstrap.properties.
Done.

2021-11-08 12:15 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +So könnte ein Pfad in der Form ```<projektname>/<stage>/db/url``` die Daten für die Connection-URL zu einer Datenbank enthalten.
Done

2021-11-08 12:37 UTC, kthielma commented on _posts/2021-10-24-configserver.md
> +Der als Speicher für Umgebungsvariablen dienende KV-Store ist am Ende nur "eine" der Kernkomponenten.
Done

2021-11-08 12:40 UTC, kthielma commented
Bin nochmal durch den Text gegangen und habe die Regel bzgl. der Bindestriche nochmal überprüft. Etwas seltsame kamen mir dabei so Redewendungen wir "out of the box" oder "on the fly" vor, aber auch die sind jetzt konsequent ohne Bindestriche geschrieben.

2021-11-11 09:20 UTC, jo2 approved these changes

2021-11-11 09:22 UTC, jo2 commented
Jetzt passt es. Die Kategorie kannst du auch noch ändern, wenn du möchtest. Die Übergänge sind teilweise fließend, du beleuchtest das Thema mMn. aber aus einer architektonischen Sicht. Auf Einzelheiten zur Einbindung, die in der Softwareentwicklung vielleicht interessant werden, gehst du zum Beispiel nicht ein.

2021-11-11 10:15 UTC, kthielma commented
@jo2 : Wie geht es nach dem Review weiter?

2021-11-11 15:44 UTC, jo2 commented
Sebastian (@acetous) wird noch einmal abschließend über den Artikel gucken und ihn dann als Release-bereit markieren. Dann wird der Artikel gemergt und sollte einen Tag später auf [blog.adesso.de](https://www.adesso.de/de/news/blog/index.jsp) veröffentlicht sein.

2021-11-25 09:17 UTC, jo2 commented
@acetous wie sieht es mit diesem Beitrag aus?

2021-11-29 09:32 UTC, acetous submitted a review, later dismissed

2021-12-02 08:14 UTC, kthielma commented
@jo2  @acetous Besteht bzgl. des Checks ein Todo bei mir?

2021-12-02 09:08 UTC, jo2 commented
Nein, da funktioniert die Pipeline noch nicht korrekt, wir arbeiten da dran.

2021-12-15 12:22 UTC, acetous approved these changes

2021-12-15 12:24 UTC, merged