Fügt Spring SAP Artikel hinzu
adessoAG/devblog pull request #219
Opened 2021-11-03 18:57 UTC by janstefan42

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [X] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [X] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [X] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [X] "title" vergeben
    - [X] "author_ids" angegeben
    - [X] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [X] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [X] Rechtschreibung korrigiert
  - [X] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [X] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [X] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [X] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [x] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

Nach bestem Wissen. Diverse erklärende Links der Checkliste laufen leider ins Leere.

2021-11-04 15:29 UTC, jo2 requested changes
Kannst du dein Bild bitte in ein quadratisches Format bringen. Andernfalls ist es in der Darstellung gestaucht.

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Das bedeutet auch, dass *SAP JCo* nicht (bzw. nur in veralteten oder nicht offiziellen Versionen) im Maven Repository enthalten ist und während bes Build Prozesses nicht automatisch geladen werden ka
```suggestion
Das bedeutet auch, dass *SAP JCo* nicht (bzw. nur in veralteten oder nicht offiziellen Versionen) im zentralen Maven Repository enthalten ist und während bes Build Prozesses nicht automatisch geladen werden kann.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Was der ungewöhnliche system Scope bedeutet und warum er an dieser Stelle sogar mehr als nur eine Notlösung ist, zeigt sich wenn das ausführbare [Artefakt gebaut](#Das Repackage Problem) werden soll.
```suggestion
Was der ungewöhnliche system Scope bedeutet und warum er an dieser Stelle sogar mehr als nur eine Notlösung ist, zeigt sich, wenn das ausführbare [Artefakt gebaut](#Das Repackage Problem) werden soll.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Die Klasse `SapConfigurationProperties` nutzt die Spring Annotation `@ConfigurationProperties(prefix = "jco.client")`, um die Konfiguration zu lesen un innerhalb der Setter in die erforderlichen Prop
```suggestion
Die Klasse `SapConfigurationProperties` nutzt die Spring Annotation `@ConfigurationProperties(prefix = "jco.client")`, um die Konfiguration zu lesen und innerhalb der Setter in die erforderlichen Properties zu schreiben.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Der `SapDestinationProvider` stellt *SAP JCo* diese Konfiguration als ein Ziel zur Verfügung. Ein Ziel ist die Darstellung eines SAP Systems innerhalb von *SAP JCo*.
```suggestion
Der `SapDestinationProvider` stellt *SAP JCo* diese Konfiguration als ein Ziel zur Verfügung. Ein Ziel ist die Darstellung eines SAP-Systems innerhalb von *SAP JCo*.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Durch die Direktive `<packaging>jar</packaging>` entsteht in diesem Beispiel ein `jar`Archiv.
```suggestion
Durch die Direktive `<packaging>jar</packaging>` entsteht in diesem Beispiel ein `jar`-Archiv.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Wenn wir (oder das Spring Maven Plugin) ihn ändern führt es zu einem Fehler in der Art von *JCo initialization fails with java.lang.ExceptionInInitializerError: Illegal JCo archive "sap-jco-3.0.11.ja
```suggestion
Wenn wir oder das Spring Maven Plugin ihn ändern, führt das zu einem Fehler in der Art von *JCo initialization fails with java.lang.ExceptionInInitializerError: Illegal JCo archive "sap-jco-3.0.11.jar".
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Die augenblickliche Lösung ist die Verwendung des system Scopes für die Abhängigkeit.
```suggestion
Die augenblickliche Lösung ist die Verwendung des Scope `system` für die Abhängigkeit. 
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Augenblicklich deswegen, weil der Scope deprecated also als veraltet markiert ist.
```suggestion
Augenblicklich deswegen, weil der Scope `deprecated` also als veraltet markiert ist. 
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Das Spring Boot Plugin kennt sie nicht und kann sie nicht umbenennen.
```suggestion
Das Spring-Boot-Plugin kennt die jar-Datei somit nicht, sie wird folglich auch nicht umbenannt.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Das Dockerfile Plugin von Spotify verwendet ein externes Dockerfile zur Erzeugung eines Images.
```suggestion
Das Dockerfile Plugin von Spotify verwendet ein externes Dockerfile zur Erzeugung eines Image. 
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Somit ermöglicht es, aus dem Docker Umfeld gewohnte Mechanismen auch innerhalb eines Maven Build Prozesses zu verwenden.
```suggestion
Somit können aus dem Docker-Umfeld gewohnte Mechanismen auch innerhalb eines Maven-Build-Prozesses verwendet werden. 
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Das Plugin erwartet des `DOCKERFILE` im selben Verzeichnis wie die `pom.xml`.
```suggestion
Das Plugin erwartet das `DOCKERFILE` im selben Verzeichnis wie die `pom.xml`.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Das Ergebnis des vorherigen Build wird über das BuildArgument `JAR_FILE` an des Dockerfile übergeben.
```suggestion
Das Ergebnis des vorherigen Build wird über das BuildArgument `JAR_FILE` an das Dockerfile übergeben. 
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Der Versuch, das bis hier hin entstandenen `spring-sap.jar` auszuführen, scheitert daran, dass genau die Klassen der *SAP JCo* Bibliothek nicht gefunden werden.
```suggestion
Der Versuch, das bis hier hin entstandenen `spring-sap.jar` auszuführen, scheitert daran, dass die Klassen der *SAP-JCo*-Bibliothek nicht gefunden werden. 
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Die Zeile `COPY libs/* /libs/` übernimmt alle *SAP JCo* Dateien aus dem Projekt in das Docker Image.
```suggestion
Die Zeile `COPY libs/* /libs/` übernimmt alle *SAP-JCo*-Dateien aus dem Projekt in das Docker Image. 
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Der Parameter `-Dloader.path=/libs/` des `java` Aufrufs sogt dann dafür, dass sie alle Teil des Classpath werden und die Applikation sie verwenden kann.
```suggestion
Der Parameter `-Dloader.path=/libs/` des `java`-Aufrufs sogt dann dafür, dass sie alle Teil des Classpath werden und die Applikation sie verwenden kann.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Die letzte Besonderheit ist der `PropertiesLauncher`, der es im Gegensatz zum häufig für Spring Boot Applikationen in Docker Containern verwendeten `ENTRYPOINT java -jar /app.jar` erlaubt, einen eige
```suggestion
Die letzte Besonderheit ist der `PropertiesLauncher`, der es im Gegensatz zum häufig für Spring-Boot-Applikationen in Docker Containern verwendeten `ENTRYPOINT java -jar /app.jar` erlaubt, einen eigenen Classpath zu verwenden.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Wenn das Docker Image weiterverteilt werden soll, erlaubt es die *SAP JCo* Lizenz nicht, die notwendigen Dateien mit auszuliefern.
```suggestion
Wenn das Docker Image weiterverteilt werden soll, erlaubt es die *SAP-JCo*-Lizenz nicht, die notwendigen Dateien mit auszuliefern.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +In diesem Falle ermöglicht es die starke Trennung der eigentlichen Anwendung von der Bibliothek, dieses z.B. in Form eines Volumes nachträglich einzubinden.
```suggestion
In diesem Falle ermöglicht es die starke Trennung der eigentlichen Anwendung von der Bibliothek, dieses z.B. in Form eines Volume nachträglich einzubinden.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Die eigentliche SAP Bibliothek ist als Lizenzgründen nicht Teil des Beispiels, wird aber ebenso wie ein SAP System für die Funktion im Verzeichnis `/libs` des Projekts erwartet.
```suggestion
Die eigentliche SAP-Bibliothek ist aus Lizenzgründen nicht Teil des Beispiels, wird aber ebenso wie ein SAP-System für die Funktion im Verzeichnis `/libs` des Projekts erwartet.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Speziell die Verwendung des system Scopes hinterlässt nicht als allerbester Gefühl, ist aber für mich der beste Weg, mit dem Umbenennungsverbot umzugehen.
```suggestion
Speziell die Verwendung des Scope `system` hinterlässt nicht das allerbeste Gefühl, ist aber für mich der beste Weg mit dem Umbenennungsverbot umzugehen.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Hat man sie aber einmal überwunden, bietet *SAP JCo* einen für Java Entwickler gewohnten Weg, auf Daten aus SAP zuzugreifen oder sie dorthin zu übertragen.
```suggestion
Hat man diese Hürde aber einmal überwunden, bietet *SAP JCo* einen für Java-Entwickler gewohnten Weg, auf Daten aus SAP zuzugreifen oder sie dorthin zu übertragen.
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Die Verbindung bietet ein breites Spektrum an Funktionen, zeigt nach meinen Erfahrungen keine Probleme auch mit größeren Datenmengen und läuft sehr stabil.
```suggestion
Die Verbindung mit SAP bietet ein breites Spektrum an Funktionen, zeigt nach meinen Erfahrungen keine Probleme auch mit größeren Datenmengen und läuft sehr stabil.
```

2021-11-04 15:29 UTC, jo2 commented on _data/authors.yml
> +  bio: "Stefan Carstensen ist Principal Software Engineer bei adesso in Hamburg. Er arbeitet als Entwickler, Anforderungsanalyse und Scrum Master in verschiedenen Projekten im Java Umfeld."
```suggestion
  bio: "Stefan Carstensen ist Principal Software Engineer bei adesso in Hamburg. Er arbeitet in der Entwicklung, der Anforderungsanalyse und als Scrum Master in verschiedenen Projekten im Java-Umfeld."
```

2021-11-04 15:29 UTC, jo2 commented on _data/authors.yml
> +  github_username: parideis
Trage hier bitte noch deinen eigenen GitHub-Nutzernamen ein.

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +#Das Ziel
```suggestion
# Das Ziel
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +#Die Bibliothek
```suggestion
# Die Bibliothek
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +#Die Konfiguration
```suggestion
# Die Konfiguration
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +#Docker - In die Box
```suggestion
# Docker - In die Box
```

2021-11-04 15:29 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +#Das komplette Beispiel
```suggestion
# Das komplette Beispiel
```

2021-11-08 07:38 UTC, jo2 requested changes
Das meinte ich mit Codeblock.

2021-11-08 07:38 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +It is not allowed to rename or repackage the original archive "sapjco3.jar"`
Wenn wir oder das Spring Maven Plugin ihn ändern, führt das zu einem Fehler in der Art von:
```
JCo initialization fails with java.lang.ExceptionInInitializerError: Illegal JCo archive "sap-jco-3.0.11.jar".
It is not allowed to rename or repackage the original archive "sapjco3.jar"
```

2021-11-08 07:45 UTC, janstefan42 commented
> Das meinte ich mit Codeblock.

Das wollte ich eigentlich auch geändert haben

2021-11-11 08:30 UTC, jo2 commented
Die Anzeige passt immer noch nicht. Kannst du dir das nochmal angucken? Für einen Codeblock benötigst du ``` zum öffnen und schließen.

2021-11-11 09:01 UTC, jo2 commented
Jo jetzt passt es.

2021-11-11 09:06 UTC, jo2 submitted a review, later dismissed

2021-11-29 09:53 UTC, acetous requested changes
Klasse Start für den Blogpost!
Kannst Du noch erläutern, wie man mit der SAP-Anbindung in seinen Tests umgeht?

2021-11-29 09:53 UTC, acetous commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +```java
Die Konsolenausgabe brauchst Du nicht als Java-Code zu kennzeichnen.

2021-11-29 09:53 UTC, acetous commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Was der ungewöhnliche system Scope bedeutet und warum er an dieser Stelle sogar mehr als nur eine Notlösung ist, zeigt sich, wenn das ausführbare [Artefakt gebaut](#Das Repackage Problem) werden soll
Kannst Du hier bitte eine Alternative zu dem deprecated-Scope aufzeigen?

2021-11-29 09:53 UTC, acetous commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Die Klasse `SapConfigurationProperties` nutzt die Spring Annotation `@ConfigurationProperties(prefix = "jco.client")`, um die Konfiguration zu lesen und innerhalb der Setter in die erforderlichen Pro
Zeig den Code hier gerne.

2021-11-29 09:53 UTC, acetous commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Der `SapDestinationProvider` stellt *SAP JCo* diese Konfiguration als ein Ziel zur Verfügung. Ein Ziel ist die Darstellung eines SAP-Systems innerhalb von *SAP JCo*.
Der Leser kennt das Codebeispiel ja noch nicht, zeig daher gerne die entsprechenden Komponenten und erläutere diese mit ein paar mehr Wörtern.

2021-11-29 09:56 UTC, jo2 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +```java
Es muss irgendeine Form an language angegeben werden, damit der Blog das als Codeblock identifiziert.

2021-11-29 09:59 UTC, janstefan42 commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Was der ungewöhnliche system Scope bedeutet und warum er an dieser Stelle sogar mehr als nur eine Notlösung ist, zeigt sich, wenn das ausführbare [Artefakt gebaut](#Das Repackage Problem) werden soll
Kann ich leider nicht. 
Außer einem eigenen Repository habe ich keine Lösung dafür.

2021-11-29 11:23 UTC, acetous commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +```java
Ok. Passt.

2021-11-29 11:24 UTC, acetous commented on _posts/2021-10-30-Spring-SAP-Konfiguration.md
> +Was der ungewöhnliche system Scope bedeutet und warum er an dieser Stelle sogar mehr als nur eine Notlösung ist, zeigt sich, wenn das ausführbare [Artefakt gebaut](#Das Repackage Problem) werden soll
Dann lass das so. ;)

2021-12-28 15:38 UTC, acetous submitted a review, later dismissed

2021-12-29 14:22 UTC, merged