New blog post: Upcoming Features in Go 1.18
adessoAG/devblog pull request #220
Opened 2021-11-21 19:16 UTC by SebastianM

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-11-25 09:34 UTC, jo2 requested changes
Ein paar Kleinigkeiten habe ich noch angemerkt, ansonsten liest sich der Artikel recht gut.

2021-11-25 09:34 UTC, jo2 commented on _posts/2021-11-21-upcoming-features-in-go-1-18.md
> +It took some years from the design phase to the actual implementation that will land in Go 1.18.
will land in Go 1.18. hattest du zwei Sätze vorher schon, kannst du das bitte umformulieren?

2021-11-25 09:34 UTC, jo2 commented on _posts/2021-11-21-upcoming-features-in-go-1-18.md
> +The following is my favorite that covers all relevant aspects of it: https://bitfieldconsulting.com/golang/generics.
```suggestion
The following is my favorite that covers all relevant aspects of it: [https://bitfieldconsulting.com/golang/generics](https://bitfieldconsulting.com/golang/generics). 
```

2021-11-25 09:34 UTC, jo2 commented on _posts/2021-11-21-upcoming-features-in-go-1-18.md
> +> Fuzzing is a type of automated testing which continuously manipulates inputs to a program to find issues such as panics or bugs. These semi-random data mutations can discover new code coverage that
Blockquotes sind im adesso-Blog leider nicht implementiert. Du kannst beispielsweise einen Kursivblock verwenden, um das Zitat zu kennzeichnen.

2021-11-25 09:34 UTC, jo2 commented on _posts/2021-11-21-upcoming-features-in-go-1-18.md
> +You can read the design doc by Katie Hockman [here](https://go.googlesource.com/proposal/+/master/design/draft-fuzzing.md). There's also [Go Time podcast episode](https://changelog.com/gotime/187) wi
```suggestion
You can read the design doc by Katie Hockman [here](https://go.googlesource.com/proposal/+/master/design/draft-fuzzing.md). There's also a [Go Time podcast episode](https://changelog.com/gotime/187) with Katie that covers this topic.
```

2021-11-25 09:34 UTC, jo2 commented on _posts/2021-11-21-upcoming-features-in-go-1-18.md
> +## Try out the Upcoming Features
Du erwähnst im vorherigen Absatz bereits gotip, kannst du diesen Absatz zuerst schreiben, damit dann im Absatz zu Faster Runs direkt klar ist, was das ist?

2021-11-26 10:35 UTC, SebastianM commented
@jo2  done

2021-11-29 09:59 UTC, jo2 submitted a review, later dismissed

2021-11-29 10:00 UTC, jo2 commented
@acetous guckst du hier noch drüber?

2021-12-30 12:29 UTC, acetous approved these changes

2021-12-30 12:31 UTC, acetous approved these changes

2021-12-30 12:32 UTC, merged