Aller Anfang ist schwer: Ansätze für Green Software-Engineering
adessoAG/devblog pull request #221
Opened 2021-11-26 09:14 UTC by gaboratarithnea

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-12-02 10:03 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Da ist mit einer Startzeit von über zehn Sekunden zu rechnen, in vielen Fällen sogar deutlich mehr. Das ist nicht wirklich kompatibel mit dem Skalierungsgedanken. Natürlich spricht immer noch viel fü
```suggestion
Bei diesen Technologien ist mit einer Startzeit von über zehn Sekunden zu rechnen, in vielen Fällen sogar deutlich mehr. Das ist nicht wirklich kompatibel mit dem Skalierungsgedanken. Natürlich spricht immer noch viel für den Einsatz von Spring Boot u.ä., bei diesem Aspekt sind aber andere Frameworks wie Quarkus, Micronaut und Ktor überlegen (siehe [hier](https://dzone.com/articles/not-only-spring-boot-a-review-of-alternatives)).
```
Spring Boot kann beispielsweise mit GraalVM ähnlich effizient gestaltet werden (https://blog.codecentric.de/en/2020/05/spring-boot-graalvm/) vielleicht kannst du da noch in einem (Neben-)Satz drauf eingehen.

2021-12-02 10:04 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Webanwendungen verbrauchen z.B. dann viel Speicher, wenn sie Daten cachen müssen. Caching ist prinzipiell aber zu empfehlen, da dadurch gleiche Berechnungen, Datenbank- oder API-Anfragen nicht ständi
```suggestion
Webanwendungen verbrauchen z.B. dann viel Speicher, wenn sie Daten cachen müssen. Caching ist prinzipiell aber zu empfehlen, da dadurch gleiche Berechnungen, Datenbank- oder API-Anfragen nicht ständig wiederholt werden müssen. Caching, das sich über mehrere Instanzen eines Microservice erstreckt, ist hier der beste Weg und würde noch stärker vermeiden (insbesondere bei Skalierungen), dass Berechnungen mehrfach durchgeführt werden.
```

2021-12-02 10:05 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Ansonsten ist anzumerken, dass Microframeworks wie Quarkus und Ktor im Speicherverbrauch deutlich günstiger sind als beispielsweise Platzhirsch Spring Boot.
```suggestion
Ansonsten ist anzumerken, dass Microframeworks wie Quarkus und Ktor im Speicherverbrauch deutlich günstiger sind als beispielsweise der Platzhirsch Spring Boot.
```
siehe mein Kommentar zu GraalVM

2021-12-02 10:07 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Gleichzeitig benötigen asynchrone Frameworks mehr Speicher und die "Organisation" der nicht-blockierenden Prozesse gilt als aufwändig und damit nicht als Ressourcen schonend.
```suggestion
Gleichzeitig benötigen asynchrone Frameworks mehr Speicher und die "Organisation" der nicht-blockierenden Prozesse gilt als aufwändig und damit nicht als ressourcenschonend.
```

2021-12-02 10:09 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +dazu ist hier zu sehen](https://da-14.com/blog/nodejs-vs-java-backend-language-large-software-development)).
```suggestion
In die Java-Community zog vor ein paar Jahren die nicht-blockierende Entwicklung ein.
Der Grund hierfür war, dass andere Technologiefamilien wie NodeJS bei der Verarbeitung von Requests eine bessere Performance zeigten, was vor allem am nicht-blockierenden Ansatz lag ([Ein aktueller Beitrag dazu ist hier zu sehen](https://da-14.com/blog/nodejs-vs-java-backend-language-large-software-development)).
```

2021-12-02 10:11 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Trotzdem sollte man auch im Java- oder JVM-Umfeld reaktiv entwickeln, da dadurch deutlich schnellere Antwortzeiten zu erwarten sind (siehe z.B. [hier](https://dzone.com/articles/spring-boot-20-webflu
```suggestion
Trotzdem sollte man auch im Java- oder JVM-Umfeld reaktiv entwickeln, da dadurch deutlich schnellere Antwortzeiten möglich sind (siehe z.B. [hier](https://dzone.com/articles/spring-boot-20-webflux-reactive-performance-test)) und das dann in der Regel auch Ressourcen spart (weniger Rechenzeit, weniger Speichernutzung, wenige Wartezeit für den Client).
```
Kannst du anstelle von "hier" einen passenden Bezeichner für den Artikel verwenden?

2021-12-02 10:12 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Viel Code wird mit Funktionen beschrieben, die häufig schwer verständlich sind und leicht den Blick auf das Wesentliche, also die Geschäftslogik, versperren. [Der Empfehlung des Autors](https://nexoc
```suggestion
Viel Code wird mit Funktionen beschrieben, die häufig schwer verständlich sind und leicht den Blick auf das Wesentliche, also die Geschäftslogik, versperren. [Der Empfehlung dieses Autors](https://nexocode.com/blog/posts/reactive-streams-vs-coroutines/) kann ich mir anschließen, Kotlin Coroutines wirken deutlich einfacher als die gängigen Java-Bibliotheken.
```

2021-12-02 10:12 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Technologieauswahl und Programmierung spielen eine wichtige Rolle, für den ökologischen Fußabdruck einer Webanwendung.
```suggestion
Technologieauswahl und Programmierung spielen für den ökologischen Fußabdruck einer Webanwendung eine wichtige Rolle.
```

2021-12-02 10:14 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Hier wurde exemplarisch einige Beispiele gezeigt, wie man Ressourcen sparen kann, in dem man auf Microframeworks, moderne Serialisierungsbibliotheken, skalierbare Architekturen, reaktive Entwicklung
```suggestion
Anhand von Beispielen haben wir gesehen, wie wir Ressourcen sparen können, indem wir auf Microframeworks, moderne Serialisierungsbibliotheken, skalierbare Architekturen, reaktive Entwicklung und GraphQL setzen,
```

2021-12-07 10:09 UTC, gaboratarithnea commented
Habe die gewünschten Änderungen vorgenommen.

2021-12-09 09:19 UTC, jo2 requested changes
Die Anpassungen sind gut, eine Sache habe ich noch angemerkt, danach ist der Artikel meiner Meinung nach fertig.

2021-12-09 09:19 UTC, jo2 commented on _posts/2021-11-26-aller-anfang-ist-schwer-ansaetze-fuer-green-software-engineering.md
> +Natürlich spricht immer noch viel für den Einsatz von Spring Boot u.ä., bei diesem Aspekt sind aber andere Frameworks wie Quarkus, Micronaut und Ktor überlegen (siehe [Review of Microservices Framewo
Ich hatte hier eher an so etwas gedacht:
```suggestion
Bei diesen Technologien ist mit einer Startzeit von über zehn Sekunden zu rechnen, in vielen Fällen sogar deutlich mehr. 
Das ist nicht wirklich kompatibel mit dem Skalierungsgedanken. 
Natürlich spricht immer noch viel für den Einsatz von Spring Boot u.ä., bei diesem Aspekt sind aber andere Frameworks wie Quarkus, Micronaut und Ktor überlegen (siehe [Review of Microservices Frameworks](https://dzone.com/articles/not-only-spring-boot-a-review-of-alternatives)).
Durch Ansätze wie die Nutzung von GraalVM kann dieses Problem in Spring Boot umgangen werden und es können Startzeiten im Millisekundenbereich erreicht werden (siehe [Running Spring Boot apps as GraalVM Native Images](https://blog.codecentric.de/en/2020/05/spring-boot-graalvm/)).
```

2021-12-16 08:20 UTC, jo2 submitted a review, later dismissed

2021-12-21 14:28 UTC, acetous commented
Hallo @jo2, schaust Du bitte einmal auf unseren validate-blogpost Workflow?

2022-01-04 07:27 UTC, acetous approved these changes

2022-01-04 07:28 UTC, acetous approved these changes

2022-01-04 07:29 UTC, merged