Create 2021-12-02 phishing training wirksam .md
adessoAG/devblog pull request #222
Opened 2021-12-03 07:13 UTC by VivienEmily

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [x] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2021-12-03 07:25 UTC, VivienEmily commented
Hi! Irgendwas scheint nicht zu klappen, ich weiß aber leider nicht was. Ich kann den Blog leider nicht in der Vorschau sehen. Könntet ihr mir helfen?

2021-12-06 07:40 UTC, jo2 commented
Hi, wahrscheinlich kann der Artikel nicht angezeigt werden, weil ein Leerzeichen im Dateinamen ist. Ein weiterer Grund könnte das falsche modified_date sein.

2021-12-06 08:22 UTC, jo2 requested changes
Der Artikel liest sich schon recht gut. Ein paar Stellen habe ich dir noch angemerkt. Benenne bitte außerdem die Datei um, sodass kein Leerzeichen mehr im Dateinamen steht und korrigiere bitte das modified_at-Feld.

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Somit gibt es nur wenige Studien, die in der Praxis durchgeführt wurden, und wenn dann handelte es sich meistens dabei um ein-phasige Experimente.
```suggestion
Somit gibt es nur wenige Studien, die in der Praxis durchgeführt wurden, und wenn, dann handelte es sich meistens um einphasige Experimente.
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Beispiele für zwei-phasige Studien sind die Studien von [West Point Kadetten](https://www.learntechlib.org/p/103686/) und dem [New York State Office](https://www.wsj.com/articles/SB112424042313615131
```suggestion
Beispiele für zweiphasige Studien sind die Studien von [West-Point-Kadetten](https://www.learntechlib.org/p/103686/) und dem [New York State Office](https://www.wsj.com/articles/SB112424042313615131). 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Ein Ergebnis der Studie war, dass das eingebettete Training effektiv zu sein scheint, aber die Klickraten deutlich niedriger waren als Studien, die im universitären Umfeld durchgeführt wurden:
```suggestion
Ein Ergebnis der Studie war, dass das eingebettete Training effektiv zu sein scheint, aber die Klickraten deutlich niedriger waren als bei Studien, die im universitären Umfeld durchgeführt wurden: 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Ein weiteres Ergebnis der Studie war, dass auch die nicht geschulten Personen ihre Ergebnisse verbessern konnten, was die Forschenden auf die Tatsache zurückführten, dass sich die Mitarbeitenden über
Für mich ist fraglich, inwieweit kann in einem achttägigen Versuch die Wirksamkeit der Schulung gemessen werden? Die Versuchspersonen sind einmal "Opfer" des Phishing-Angriffs geworden und allein dadurch schon sensibilisiert, Dass sie in der nächsten Woche nochmal so unvorsichtig handeln und Links oder Anhänge öffnen, halte ich auch ohne zusätzliche Schulungen für unwahrscheinlich. Wenn du das ähnlich siehst, kannst du das vielleicht noch als Kritikpunkt zu diesen Forschungsergebnissen aufnehmen.

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Eine andere ein-phasige [Studie](https://ieeexplore.ieee.org/abstract/document/6585241/?casa_token=gR_MTQC_7wUAAAAA:dmXsUP0cQSNsv1BMate9-Un15g2hYut02b847gVLlndOJ4RoWt08Pj8HxhPtpklT7QpjHR2cHFyj) unter
```suggestion
Eine andere einphasige [Studie](https://ieeexplore.ieee.org/abstract/document/6585241/?casa_token=gR_MTQC_7wUAAAAA:dmXsUP0cQSNsv1BMate9-Un15g2hYut02b847gVLlndOJ4RoWt08Pj8HxhPtpklT7QpjHR2cHFyj) untersucht ebenfalls Spear-Phishing-E-Mails und die Wirksamkeit von eingebetteten Schulungen in der Praxis. 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Es wurden mehrere E-Mails vorbereitet, einige davon mit kleinen Fehlern, so dass die Probanden die Phishing-E-Mails erkennen konnten, wenn sie (mehr) aufpassten.
```suggestion
Es wurden mehrere E-Mails vorbereitet, einige davon mit kleinen Fehlern, sodass die Probanden die Phishing-E-Mails erkennen konnten, wenn sie (mehr) aufpassten. 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Die Forschenden vermuteten jedoch, dass die Schulungswebsite nicht gut gestaltet war, da die Probanden angaben, dass sie die Website so seltsam fanden, dass sie sie sofort wegklickten.
```suggestion
Die Forschenden vermuteten jedoch, dass die Schulungswebsite nicht gut gestaltet war, da die Teilnehmenden angaben, dass sie die Website so seltsam fanden, dass sie sie sofort wegklickten. 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Auch hier war die Hypothese, dass nach einem Phishing-Training die Klickraten sinken und die Anzahl der gemeldeten verdächtigen E-Mails steigt.
Ist die Studie mit Vorhermessung und Nachhermessung dann nicht auch zweiphasig?

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Interessant ist nicht nur die Wirkung von Phishing (-trainings) über E-Mail, sondern auch über andere Nachrichtendienste.
```suggestion
Interessant ist nicht nur die Wirkung von Phishing (-Trainings) über E-Mail, sondern auch über andere Nachrichtendienste.
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +So nutzte eine andere ein-phasige [Studie](https://link.springer.com/chapter/10.1007/978-3-319-70278-0_39) Social-Media-Plattform, um simulierte Phishing-E-Mails zu versenden.
```suggestion
So nutzte eine andere einphasige [Studie](https://link.springer.com/chapter/10.1007/978-3-319-70278-0_39) Social-Media-Plattformen, um simulierte Phishing-Nachrichten zu versenden. 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Zum Vergleich wurden die Phishing-E-Mails auch per E-Mail verschickt.
```suggestion
Zum Vergleich wurden die Phishing-Nachrichten auch per E-Mail verschickt. 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Tatsächlich waren die Klickraten von Phishing-E-Mails, die über soziale Medien verschickt wurden, deutlich höher:
```suggestion
Tatsächlich waren die Klickraten von Phishing-Nachrichten, die über soziale Medien verschickt wurden, deutlich höher: 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +##Phishing-Training bei adesso
```suggestion
## Phishing-Training bei adesso 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Auch bei adesso wurde 2019 eine ein-phasige Phishing Studie durchgeführt.
```suggestion
Auch bei adesso wurde 2019 eine einphasige Phishing-Studie durchgeführt. 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Wer mehr über die über die Zahlen Daten Fakten dieses Trainings erfahren möchte, kann sich den dazugehörigen [Blog-Beitrag](https://www.adesso.ch/de_ch/news/blog/phishing-kampagne-bei-adesso.jsp) dur
```suggestion
Wer mehr über die über die Zahlen, Daten und Fakten dieses Trainings erfahren möchte, kann sich den dazugehörigen [Blog-Beitrag](https://www.adesso.ch/de_ch/news/blog/phishing-kampagne-bei-adesso.jsp) durchlesen.
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +##Fazit
```suggestion
# Fazit
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +* Durch simuliertes Phishing Training mit eingebetteten Schulungsmaterial lassen sich die Klickraten reduzieren
```suggestion
* Durch simuliertes Phishing-Training mit eingebetteten Schulungsmaterial lassen sich die Klickraten reduzieren 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Phishing-E-Mails als Training zu versenden, scheint bisher eine gute Möglichkeit, doch scheint auch die Nutzung von Social-Media-Plattformen ein hohes Einfallstor für Phishing dazustellen.
```suggestion
Phishing-E-Mails als Training zu versenden, scheint bisher eine gute Möglichkeit, doch scheint auch die Nutzung von Social-Media-Plattformen ein großes Einfallstor für Phishing darzustellen. 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Insbesondere, wenn diese auch auf Betriebsgeräten wie auf dem Firmenhandy oder Firmenlaptop genutzt werden.
```suggestion
Dies gilt insbesondere, wenn diese auch auf Betriebsgeräten wie auf dem Firmenhandy oder Firmenlaptop genutzt werden. 
```

2021-12-06 08:22 UTC, jo2 commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Hierüber lässt sich jedoch kaum ein simuliertes Phishing-Training für Mitarbeitende durchführen.
Warum lässt sich ein solches Training nicht durchführen, kannst du darauf vielleicht noch in einem Satz eingehen? Andererorts war ein solches Training ja scheinbar möglich, wie du oben beschrieben hast.

2021-12-08 07:55 UTC, VivienEmily commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Hierüber lässt sich jedoch kaum ein simuliertes Phishing-Training für Mitarbeitende durchführen.
Guter Punkt, da war ich wohl zu sehr drin! Werde ergänzen, dass wenn ein Unternehmen seine Mitarbeitenden schulen möchte, sie das nicht über die privaten accounts machen können.

2021-12-08 08:12 UTC, VivienEmily commented on _posts/2021-12-02 phishing-training-wirksam .md
> +Auch hier war die Hypothese, dass nach einem Phishing-Training die Klickraten sinken und die Anzahl der gemeldeten verdächtigen E-Mails steigt.
Es wurde nur ein simuliertes Phishing Training durchgeführt. Die "Effektivität" wollten sie daran messen, dass die Mitarbeitenden die verdächtigen realen E-Mails melden und diese Anzahl steigt. Vielleicht sollte ich es ändern in "nach einem Phishing Training die Anzahl der gemeldeten verdächtigten Mails steigt"

2021-12-08 09:43 UTC, VivienEmily commented
Dummerweise erst den Dateinamen angepasst. Deine Änderungen habe ich aber alle eingearbeitet.

2021-12-08 09:43 UTC, VivienEmily commented
Die Vorschau passt jetzt auch!

2021-12-08 09:45 UTC, VivienEmily commented
Also dieser Blogpost Checker will noch nicht, ich weiß leider nicht warum, die Fehlermeldung sagt mir nichts.

2021-12-09 07:46 UTC, jo2 requested changes
2 Sachen hast du glaube ich noch übersehen. Die Pipeline funktioniert momentan noch nicht, da sind wir dran das Problem zu beheben. Da brauchst du dich nicht drum zu kümmern.

2021-12-09 07:46 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam .md
> +Phishing-Angriffe sind auch im Cybercrime Report des [Bundeskriminalamtes](https://www.bka.de/SharedDocs/Downloads/DE/Publikationen/JahresberichteUndLagebilder/Cybercrime/cybercrimeBundeslagebild2020
```suggestion
Phishing-Angriffe sind auch im Cybercrime Report des [Bundeskriminalamtes](https://www.bka.de/SharedDocs/Downloads/DE/Publikationen/JahresberichteUndLagebilder/Cybercrime/cybercrimeBundeslagebild2020.html;jsessionid=E6BA6ABCD9436276B64F2339DA6397DB.live2302?nn=28110) ein großes Thema: Phishing "ist und bleibt DIE (größte) Bedrohung für Unternehmen und öffentliche Einrichtungen". 
```

2021-12-09 07:46 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam .md
> +Somit gibt es nur wenige Studien, die in der Praxis durchgeführt wurden, und wenn dann handelte es sich meistens um einphasige Experimente.
```suggestion
Somit gibt es nur wenige Studien, die in der Praxis durchgeführt wurden, und wenn, dann handelte es sich meistens um einphasige Experimente.
```

2021-12-09 07:47 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam .md
> +Ein weiteres Ergebnis der Studie war, dass auch die nicht geschulten Personen ihre Ergebnisse verbessern konnten, was die Forschenden auf die Tatsache zurückführten, dass sich die Mitarbeitenden über
Für mich ist fraglich, inwieweit kann in einem achttägigen Versuch die Wirksamkeit der Schulung gemessen werden? Die Versuchspersonen sind einmal "Opfer" des Phishing-Angriffs geworden und allein dadurch schon sensibilisiert, Dass sie in der nächsten Woche nochmal so unvorsichtig handeln und Links oder Anhänge öffnen, halte ich auch ohne zusätzliche Schulungen für unwahrscheinlich. Wenn du das ähnlich siehst, kannst du das vielleicht noch als Kritikpunkt zu diesen Forschungsergebnissen aufnehmen.

2021-12-09 07:52 UTC, VivienEmily commented on _posts/2021-12-02-phishing-training-wirksam .md
> +Ein weiteres Ergebnis der Studie war, dass auch die nicht geschulten Personen ihre Ergebnisse verbessern konnten, was die Forschenden auf die Tatsache zurückführten, dass sich die Mitarbeitenden über
Absolut!

2021-12-09 07:52 UTC, jo2 commented
Du wolltest auch noch auf den Unterschied zwischen einphasigen und zweiphasigen Simulationen eingehen (vgl. [dein Kommentar](https://github.com/adessoAG/devblog/pull/222#discussion_r764631840)). Und du hast im Dateinamen immernoch ein Leerzeichen. Das funktioniert jetzt momentan in der Preview, kann aber zu Fehlern beim Export und Import der Daten zum adesso-Blog führen.

2021-12-09 08:24 UTC, VivienEmily commented
> Du wolltest auch noch auf den Unterschied zwischen einphasigen und zweiphasigen Simulationen eingehen (vgl. [dein Kommentar](https://github.com/adessoAG/devblog/pull/222#discussion_r764631840)). Und du hast im Dateinamen immernoch ein Leerzeichen. Das funktioniert jetzt momentan in der Preview, kann aber zu Fehlern beim Export und Import der Daten zum adesso-Blog führen.



> Du wolltest auch noch auf den Unterschied zwischen einphasigen und zweiphasigen Simulationen eingehen (vgl. [dein Kommentar](https://github.com/adessoAG/devblog/pull/222#discussion_r764631840)). Und du hast im Dateinamen immernoch ein Leerzeichen. Das funktioniert jetzt momentan in der Preview, kann aber zu Fehlern beim Export und Import der Daten zum adesso-Blog führen.

Den habe ich eingearbeitet

2021-12-09 08:26 UTC, VivienEmily commented on _posts/2021-12-02-phishing-training-wirksam .md
> +Ein weiteres Ergebnis der Studie war, dass auch die nicht geschulten Personen ihre Ergebnisse verbessern konnten, was die Forschenden auf die Tatsache zurückführten, dass sich die Mitarbeitenden über
Tatsächlich lässt der Trainingseffekt nach, ich habs ergänzt. Was ich übrigens intern bei adesso Interviews sehr interessant fand, war das manche auf die E-Mail reingefallen sind, sie aber trotzdem der Überzeugung waren niemals auf Phishing E-Mails reinzufallen und dass das nur eine Ausnahme war.

2021-12-09 09:39 UTC, jo2 requested changes
Ein paar Sachen habe ich noch angemerkt. Vielleicht kannst du den Punkt der Selbstüberzeugtheit aus deinem Kommentar vielleicht auch noch einbauen. Den Aspekt finde ich sehr interessant. Du hast in der aktuellen Version zwei Dateien committet, einmal eine mit Leerzeichen und einmal eine ohne. Die Verbesserungsvorschläge habe ich in der Datei ohne Leerzeichen gemacht, kannst du die mit Leerzeichen bitte noch entfernen?

2021-12-09 09:39 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam.md
> +Jedoch war ein weiteres Ergebnis der zweiphasigen Studien, dass es weiterhin Personen gab, die sowohl im ersten Durchlauf, als auch im zweiten Durchlauf auf eine simulierte Phishing-E-Mail reinfielen
```suggestion
Jedoch war ein weiteres Ergebnis der zweiphasigen Studien, dass es weiterhin Personen gab, die sowohl im ersten als auch im zweiten Durchlauf auf eine simulierte Phishing-E-Mail reinfielen. 
```

2021-12-09 09:39 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam.md
> +Der Trainingseffekt lässt nach einer gewissen Zeit nach, da die Betroffenheit auf eine Trainings-Phishing-E-Mail reingefallen zu sein nicht mehr präsent ist und das Phishing-Training kein prägendes n
```suggestion
Der Trainingseffekt lässt nach einer gewissen Zeit nach, da die Betroffenheit auf eine Trainings-Phishing-E-Mail reingefallen zu sein, nicht mehr präsent ist und das Phishing-Training kein so negativ prägendes Ereignis ist, wie tatsächlich Opfer eines Phishing-Betrugs zu werden. 
```

2021-12-09 09:39 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam.md
> +Interviewte Teilnehmende, die einen realen Phishing-Betrug im näheren Umkreis hatten bestätigten diesen Effekt.
```suggestion
Interviewte Teilnehmende, die einen realen Phishing-Betrug im näheren Umkreis hatten, bestätigten diesen Effekt.
```

2021-12-09 09:39 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam.md
> +Phishing-E-Mails als Training zu versenden, scheint bisher eine gute Möglichkeit, doch scheint auch die Nutzung von Social-Media-Plattformen ein großes Einfallstor für Phishing darzustellen.
```suggestion
Phishing-E-Mails als Training zu versenden, scheint bisher eine gute Möglichkeit die Awareness hierfür zu steigern, doch scheint auch die Nutzung von Social-Media-Plattformen ein großes Einfallstor für Phishing darzustellen. 
```

2021-12-10 10:21 UTC, VivienEmily commented
Die andere Datei sollte gelöscht sein, die Änderungen sind eingearbeitet :)

2021-12-16 08:18 UTC, jo2 requested changes
2 Kleinigkeiten sind in den Ergänzungen zu der Selbstüberschätzung noch drin, danach sollte der Artikel fertig sein.

2021-12-16 08:18 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam.md
> +Zudem gab es auch in dem adesso Phishing-Training interviewte Mitarbeitende, die obwohl sie auf eine Trainings-Phishing-E-Mail geklickt hatten, der Überzeugung waren, dass sie niemals auf eine Phishi
```suggestion
Zudem gab es auch im adesso-Phishing-Training interviewte Mitarbeitende, die, obwohl sie auf eine Trainings-Phishing-E-Mail geklickt hatten, der Überzeugung waren, dass sie niemals auf eine Phishing E-mail reinfallen würden. 
```

2021-12-16 08:18 UTC, jo2 commented on _posts/2021-12-02-phishing-training-wirksam.md
> +Um den Trainingseffekt über alle Mitarbeitenden zu schärfen und mancher Selbstüberschätzung zu trotzen und weitergehend konstant hoch zu halten, macht es Sinn, variierende Phishing-Simulationen konti
```suggestion
Um den Trainingseffekt über alle Mitarbeitenden zu schärfen, mancher Selbstüberschätzung zu trotzen und die Awareness weitergehend hoch zu halten, macht es Sinn, variierende Phishing-Simulationen kontinuierlich über einen langen Zeitraum durchzuführen und als festen Bestandteil der Security Awareness im Unternehmen zu etablieren. 
```

2021-12-16 13:25 UTC, VivienEmily commented
Habs eingearbeitet :)

2021-12-20 07:12 UTC, jo2 submitted a review, later dismissed

2021-12-28 08:50 UTC, acetous approved these changes

2021-12-28 08:52 UTC, merged