Spiel des Lebens - IT-Security Editionn
adessoAG/devblog pull request #226
Opened 2022-01-29 14:06 UTC by VivienEmily

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-01-29 14:11 UTC, VivienEmily commented
Hallo @acetous & @jo2, am 8. Februar ist der Safer Internet Day. Meint ihr wir schaffen es ihn an diesem Tag zu veröffentlichen? :) Ich weiß etwas kurzfristig, würde mich freuen wenn das klappt!

2022-02-07 06:58 UTC, VivienEmily commented
Ich glaube jetzt wird das zu knapp oder?

2022-02-07 07:40 UTC, acetous commented
Hi! Ich habe die Veröffentlichung bereits eingeplant. Das sollte klappen. :)

2022-02-07 10:04 UTC, jo2 requested changes
@VivienEmily sorry, ich habe den Artikel vollkommen verpennt. Schaffst du es heute noch, die Änderungen einzupflegen, sonst kann ich das gleich noch machen. Sobald du was neues hast, markier mich gerne oder schreib mir nochmal per Teams oder so. Dann kann ich da direkt wieder dran gehen.

2022-02-07 10:04 UTC, jo2 commented on _posts/2022-01-29-Spiel-des-Lebens-IT-Security-Edition.md
> +Ein spielerischer Ansatz ist immer gut, um zu lernen und das ein Leben lang, um ein ernstes Thema wie IT-Sicherheit zu verpacken.
```suggestion
Ein spielerischer Ansatz ist immer gut, um zu lernen, und das ein Leben lang, um ein ernstes Thema wie IT-Sicherheit zu verpacken. 
```

2022-02-07 10:04 UTC, jo2 commented on _posts/2022-01-29-Spiel-des-Lebens-IT-Security-Edition.md
> +Umso wichtiger ist es ein Leben lang zu lernen, und wachsam zu bleiben.
```suggestion
Umso wichtiger ist es, ein Leben lang zu lernen und wachsam zu bleiben. 
```

2022-02-07 10:04 UTC, jo2 commented on _posts/2022-01-29-Spiel-des-Lebens-IT-Security-Edition.md
> +Ob (Online-) Erpressung Minderjähriger, Phishing von Zugangsdaten (im Portmonee die Karte und der Pin oder beim Online Shopping Benutzername und Passwort) oder dem Enkeltrick.
```suggestion
Dies gilt für (Online-)Erpressung Minderjähriger, Phishing von Zugangsdaten (im Portmonee die Karte und der Pin oder beim Online Shopping Benutzername und Passwort) oder den Enkeltrick. 
```

2022-02-07 10:52 UTC, VivienEmily commented on _posts/2022-01-29-Spiel-des-Lebens-IT-Security-Edition.md
> +Dies unterteilt sich in Basistipps zur IT-Sichereheit, digitale Identitäten, sichere Online-Kommunikation, Gaming, IT-Sicherheit bei Wahlen, Alltags Tipps, Cloud Dienste, mobile Zahlungsmittel, smart
Tatsächlich ist es die Schreibweise wie sie auf den Seiten des BSI verwendet wird.

2022-02-07 12:44 UTC, jo2 approved these changes

2022-02-07 12:44 UTC, jo2 commented
Von meiner Seite aus passt dann soweit alles.

2022-02-08 08:06 UTC, acetous approved these changes

2022-02-08 08:10 UTC, merged